Allow the two machines to play for n times. One agent has weights and features and calculates the value and makes the move while the other agent makes random moves. create a dataframe with the moves made and the evaluation score. Once the playing is complete, the actual Vtrain values are populated in the dataframe. If it is the last move (game over move), the Vtrain gets 100,0,-100 (w,d,l). Otherwise, the Vtrain value is the evaluation score (estimate) of the subsequent board state. For instance, the Vtrain value of the last but one board state will be the Vestimate of the last move.

In [1]:
import numpy as np
import pandas as pd
import os
import random
from random import randint
from IPython.display import display, clear_output
import ipywidgets as widgets

In [2]:
from ipywidgets import interact, interactive, fixed, interact_manual

## The below code is for feature extraction

In [3]:
def evalboard(test_board):
    #print("Test board inside evalboard", test_board)
    ## two squares in a row (can be row, column or diagonal) are filled with 1 and the other square is empty
    f1 = []
    
    if((np.count_nonzero(test_board[0,:])==2) & (np.sum(test_board[0,:])==2)):
        f1.append(1)
    if((np.count_nonzero(test_board[1,:])==2) & (np.sum(test_board[1,:])==2)):
        f1.append(1)
    if((np.count_nonzero(test_board[2,:])==2) & (np.sum(test_board[2,:])==2)):
        f1.append(1)
    if((np.count_nonzero(test_board[:,0])==2) & (np.sum(test_board[:,0])==2)):
        f1.append(1)
    if((np.count_nonzero(test_board[:,1])==2) & (np.sum(test_board[:,1])==2)):
        f1.append(1)
    if((np.count_nonzero(test_board[:,2])==2) & (np.sum(test_board[:,2])==2)):
        f1.append(1)
    if((np.count_nonzero(test_board.diagonal())==2) & (np.trace(test_board)==2)):
        f1.append(1)
    if((np.count_nonzero(np.fliplr(test_board).diagonal())==2) & (np.trace(np.fliplr(test_board))==2)):
        f1.append(1)

    
    
    ## two squares in a row (can be row, column or diagonal) are filled with 2 and the other square is empty
    f2 = []

    if((np.count_nonzero(test_board[0,:])==2) & (np.sum(test_board[0,:])==4)):
        f2.append(2)
    if((np.count_nonzero(test_board[1,:])==2) & (np.sum(test_board[1,:])==4)):
        f2.append(2)
    if((np.count_nonzero(test_board[2,:])==2) & (np.sum(test_board[2,:])==4)):
        f2.append(2)
    if((np.count_nonzero(test_board[:,0])==2) & (np.sum(test_board[:,0])==4)):
        f2.append(2)
    if((np.count_nonzero(test_board[:,1])==2) & (np.sum(test_board[:,1])==4)):
        f2.append(2)
    if((np.count_nonzero(test_board[:,2])==2) & (np.sum(test_board[:,2])==4)):
        f2.append(2)
    if((np.count_nonzero(test_board.diagonal())==2) & (np.trace(test_board)==4)):
        f2.append(2)
    if((np.count_nonzero(np.fliplr(test_board).diagonal())==2) & (np.trace(np.fliplr(test_board))==4)):
        f2.append(2)
    
    ## One 2 in an otherwise empty row (column, row or diagonal)
    f4 = []
    
    if((np.count_nonzero(test_board[0,:])==1) & (np.sum(test_board[0,:])==2)):
        f4.append(2)
    if((np.count_nonzero(test_board[1,:])==1) & (np.sum(test_board[1,:])==2)):
        f4.append(2)
    if((np.count_nonzero(test_board[2,:])==1) & (np.sum(test_board[2,:])==2)):
        f4.append(2)
    if((np.count_nonzero(test_board[:,0])==1) & (np.sum(test_board[:,0])==2)):
        f4.append(2)
    if((np.count_nonzero(test_board[:,1])==1) & (np.sum(test_board[:,1])==2)):
        f4.append(2)
    if((np.count_nonzero(test_board[:,2])==1) & (np.sum(test_board[:,2])==2)):
        f4.append(2)
    if((np.count_nonzero(test_board.diagonal())==1) & (np.trace(test_board)==2)):
        f4.append(2)
    if((np.count_nonzero(np.fliplr(test_board).diagonal())==1) & (np.trace(np.fliplr(test_board))==2)):
        f4.append(2)
        
    ## One 1 in an otherwise empty row (column, row or diagonal)
    f3 = []
    
    if(np.sum(test_board[0,:])==1):
        f3.append(1)
        
    if(np.sum(test_board[1,:])==1):
        f3.append(1)
        
    if(np.sum(test_board[2,:])==1):
        f3.append(1)
        
    if(np.sum(test_board[:,0])==1):
        f3.append(1)
        
    if(np.sum(test_board[:,1])==1):
        f3.append(1)
        
    if(np.sum(test_board[:,2])==1):
        f3.append(1)
        
    if(np.trace(test_board)==1):
        f3.append(1)
       
    if(np.trace(np.fliplr(test_board))==1):
        f3.append(1)
       

    

    ## Three cells in a row is filled with 1
    f5 = []
    
    if(test_board[0,:]==1).all():
        f5.append(1)
    if(test_board[1,:]==1).all():
        f5.append(1)
    if(test_board[2,:]==1).all():
        f5.append(1)
    if(test_board.diagonal()==1).all():
        f5.append(1)
    if(np.fliplr(test_board).diagonal()==1).all():
        f5.append(1)

    
    ## Three cells in a row is filled with 2
    f6 = []

    
    if(test_board[0,:]==2).all():
        f6.append(2)
    if(test_board[1,:]==2).all():
        f6.append(2)
    if(test_board[2,:]==2).all():
        f6.append(2)
    if(test_board.diagonal()==2).all():
        f6.append(2)
    if(np.fliplr(test_board).diagonal()==2).all():
        f6.append(2)
    
    return(len(f1),len(f2),len(f3),len(f4),len(f5),len(f6))

### The below function is for making the moves of the machine which is trained to become smart

In [47]:
def machine1_move(old_board_state,w0,w1,w2,w3,w4,w5,w6):
    feature_list = []
    board_state = np.copy(old_board_state)
    x, y = np.where(board_state==0)
    #print("weights are ",w0,w1,w2,w3,w4,w5,w6)
    evalscore = []
    for i in range(len(x)):
        board_state[x[i],y[i]]=1

        ft1, ft2, ft3, ft4, ft5, ft6 = evalboard(board_state)
        feature_list.append([ft1,ft2,ft3,ft4,ft5,ft6])
        
        evalscore.append(w0 + w1*ft1 + w2*ft2 + w3*ft3 + w4*ft4 + w5*ft5 + w6*ft6)
        feature_list[i].extend([w0 + w1*ft1 + w2*ft2 + w3*ft3 + w4*ft4 + w5*ft5 + w6*ft6])
        #print("features",feature_list)
        #print("evalscore",evalscore)
        board_state = np.copy(old_board_state)
        

    position_index = np.argmax(np.asarray(evalscore))
    optimal_feature = feature_list[position_index]
    #print("Optimal feature is ", optimal_feature)
    #print("position_index is ",position_index)

    machine1_position = x[position_index]*3 + y[position_index]
    #moves.append(machine1_position)
    
    return(machine1_position, max(evalscore), optimal_feature)




### the below code is for the machine which doesnt learn - makes random moves 

In [48]:

def machine2_move(game_moves):
    while(True):
        machine2_position = randint(0,8)
        if machine2_position not in game_moves:
            #game_board[machine2_position // 3, machine2_position % 3] = 2
            #moves.append(machine2_position)
            
            #clear_output()
            print("Machine 2's move")
            break
    return(machine2_position)



### Below code is for updating weights after each training game is played

In [52]:
def weight_update(X, y, game_counter,w0,w1,w2,w3,w4,w5,w6):
    print("Game counter", game_counter)
    f1 = [sublist[0] for sublist in X]
    f2 = [sublist[1] for sublist in X]
    f3 = [sublist[2] for sublist in X]
    f4 = [sublist[3] for sublist in X]
    f5 = [sublist[4] for sublist in X]
    f6 = [sublist[5] for sublist in X]
    Vestimate = [sublist[6] for sublist in X]
    Vtrain_flattened = [item for sublist in y for item in sublist]
    #print("Vtrain_flattened is",Vtrain_flattened)
    
    lr = 0.1
    print("length of f1",len(f1))
    w0_old = w0
    w1_old = w1
    w2_old = w2
    w3_old = w3
    w4_old = w4
    w5_old = w5
    w6_old = w6
    
    for i in range(0, len(f1)):
        w0_new = w0_old + lr*(Vtrain_flattened[i] - Vestimate[i])
        w1_new = w1_old + lr*(Vtrain_flattened[i] - Vestimate[i])*f1[i]
        w2_new = w2_old + lr*(Vtrain_flattened[i] - Vestimate[i])*f2[i]
        w3_new = w3_old + lr*(Vtrain_flattened[i] - Vestimate[i])*f3[i]
        w4_new = w4_old + lr*(Vtrain_flattened[i] - Vestimate[i])*f4[i]
        w5_new = w5_old + lr*(Vtrain_flattened[i] - Vestimate[i])*f5[i]
        w6_new = w6_old + lr*(Vtrain_flattened[i] - Vestimate[i])*f6[i]
        #print("Vtrain_flattened",Vtrain_flattened[i])
        w0_old = w0_new
        w1_old = w1_new
        w2_old = w2_new
        w3_old = w3_new
        w4_old = w4_new
        w5_old = w5_new
        w6_old = w6_new
       
        
        if i==(len(f1)-1):
            break

        Vestimate[i+1] = w0_new + w1_new*f1[i+1] + w2_new*f2[i+1] + w3_new*f3[i+1] + w4_new*f4[i+1] + w5_new*f5[i+1] + w6_new*f6[i+1]
    #print(w0_new,w1_new,w2_new,w3_new,w4_new,w5_new,w6_new)
    return(w0_new,w1_new,w2_new,w3_new,w4_new,w5_new,w6_new)




#### For printing the game board

In [53]:
def print_game_board(game_board):
    print_board = np.copy(game_board)
    print_board_list = print_board.ravel().tolist()
    replace_dict = {1:'X',2:'O',0:" "}
    print_board_XO = [replace_dict.get(n) for n in print_board_list]
    
    print("     |     |     ")
    print("  "+print_board_XO[0]+"  |  "+print_board_XO[1]+"  |  "+print_board_XO[2]+"  ")
    print("_____|_____|_____")
    print("     |     |     ")
    print("  "+print_board_XO[3]+"  |  "+print_board_XO[4]+"  |  "+print_board_XO[5]+"  ")
    print("_____|_____|_____")
    print("     |     |     ")
    print("  "+print_board_XO[6]+"  |  "+print_board_XO[7]+"  |  "+print_board_XO[8]+"  ")
    print("     |     |     ")

### Below code is for the whole training process

In [57]:
##List of winning moves - whenever any combination in this achieved it is game over
winning_moves = [[0,1,2],[0,3,6],[0,4,8],[1,4,7],[2,5,8],[2,4,6],[3,4,5],[6,7,8]]
positions = []
start_index = 0
game_feature = []

Vtrain = []

## Initializing weights for the learning. This can be made random also instead of a fixed 0.5
w0 = w1 = w2 = w3 = w4 = w5 = w6 = 0.5
print("intial wights",w0,w1,w2,w3,w4,w5,w6)


for m in range(0,1000):
    
    ##Initializing different lists - moves contain overall moves made by both the agents
    ## This is to prevent repetition of moves
    ## The individual agent moves are to compare with the winning moves list
    ## The board is initialized with zeros
    
    moves = []
    machine1_moves = []
    machine2_moves = []
    Vest = []
    feature_list = []
    game_feature = []
    Vtrain=[]
    game_board = np.zeros([3,3])
    print(game_board)
    
    ## This loop is for the game play - a maximum of 9 moves can be made in a game
    for i in range(0,9):
        #game_feature = []
        ## Initializing a game over flag to 0
        GO = 0
        
        ## Calling the function machine1_move for making the moves of the agent 1
        ## and receiving the move position in machine1_position variable
        ## Passing the weights as function arguments 
        machine1_position, vestimate, feature_list = machine1_move(game_board, w0, w1, w2, w3, w4, w5, w6)
        print("feature_list is", feature_list)
        print("Vestimate is ", vestimate)
        Vest.append(vestimate)
        
        ##Updating the game board with the machine1 move position
        game_board[machine1_position // 3, machine1_position % 3] = 1
        print("Machine 1's move")
        print(game_board)
        
        ## Creating a copy of game board into mc1
        ## Pushing the game board status into the positions list
        ## this will useful later when creating the dataframe of game board positions
        
        #mc1 = np.copy(game_board)
        #positions.append(mc1.ravel().tolist())
        game_feature.append(feature_list)
 
        
        ## Pushing the moves machine 1 into the moves list and the machine1_moves list
        moves.append(machine1_position)
        print("Moves array",moves)
        machine1_moves.append(machine1_position)
        machine1_counter = 0
        
        ## If more than two moves are made, then keep checking in the winning moves list
        if len(machine1_moves) > 2:
            for j in range(len(winning_moves)):
                #human_counter = 0
                ## For each set (3 positions) of winning moves, the values in the machine1_moves
                ## are checked with the winning moves set - and if there is a match of 3, the game is 
                ## declared won by machine 1
                machine1_counter = [a for a in machine1_moves if a in winning_moves[j]]
                if len(machine1_counter)==3:
                    print("Game Over")
                    print("Machine1 won")
                    GO = 1
                    break
        
        ## If game over, the GO flag will be set to 1 in the previous code block and the previous loop is exited.
        ## Now, for all the gameboard arrays in the position list (which includes moves by machine 2 as well)
        ## a 1 is added - to indicate that the game was won by agent 1.
        ## Else if the number of moves is 9 without the GO flag set to 1, then it is a tie game and hence '0' is 
        ## added to the position arrays
        if GO == 1:
            Vest.append(100)
            Vest.pop(0)
            Vtrain.append(Vest)

            break
            
        elif len(machine1_moves)+len(machine2_moves) == 9:
            print("Game Tie")
            Vest.append(0)
            Vest.pop(0)
            Vtrain.append(Vest)
            break
            
            
        ## Calling the function machine2_move for making the moves of the agent 2
        ## and receiving the move position in machine2_position variable
        
        
        machine2_position = machine2_move(moves)
        
        game_board[machine2_position // 3, machine2_position % 3] = 2
        print(game_board)
        
        mc2 = np.copy(game_board)
        #positions.append(mc2.ravel().tolist())
        
        moves.append(machine2_position)
        machine2_moves.append(machine2_position)
        machine2_counter = 0
        
        if len(machine2_moves) > 2:
            for h in range(len(winning_moves)):
                #machine_counter = 0
                machine2_counter = [b for b in machine2_moves if b in winning_moves[h]]
                if len(machine2_counter)==3:
                    print("Game Over")
                    print("Machine2 won")
                    GO = 2
                    break

        if GO == 2:
            Vest.append(-100)
            Vest.pop(0)
            Vtrain.append(Vest)
            break
    #print("GAME FEATURE",game_feature)
    w0,w1,w2,w3,w4,w5,w6 = weight_update(game_feature, Vtrain,m,w0,w1,w2,w3,w4,w5,w6)
    print("weights after update",w0,w1,w2,w3,w4,w5,w6)

intial wights 0.5 0.5 0.5 0.5 0.5 0.5 0.5
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
feature_list is [0, 0, 4, 0, 0, 0, 2.5]
Vestimate is  2.5
Machine 1's move
[[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]
Moves array [4]
Machine 2's move
[[0. 0. 0.]
 [0. 1. 0.]
 [0. 2. 0.]]
feature_list is [1, 0, 4, 1, 0, 0, 3.5]
Vestimate is  3.5
Machine 1's move
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 2. 0.]]
Moves array [4, 7, 0]
Machine 2's move
[[1. 0. 0.]
 [0. 1. 2.]
 [0. 2. 0.]]
feature_list is [2, 0, 2, 2, 0, 0, 3.5]
Vestimate is  3.5
Machine 1's move
[[1. 1. 0.]
 [0. 1. 2.]
 [0. 2. 0.]]
Moves array [4, 7, 0, 5, 1]
Machine 2's move
[[1. 1. 0.]
 [2. 1. 2.]
 [0. 2. 0.]]
feature_list is [2, 0, 0, 1, 1, 0, 2.5]
Vestimate is  2.5
Machine 1's move
[[1. 1. 1.]
 [2. 1. 2.]
 [0. 2. 0.]]
Moves array [4, 7, 0, 5, 1, 3, 2]
Game Over
Machine1 won
Game counter 0
length of f1 4
weights after update 10.247300000000001 19.9646 0.5 0.282 10.1783 10.2863 0.5
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
feature_list is [0, 0, 4, 0, 0, 0, 11.37530

length of f1 5
weights after update 21.225396279950566 -19.918923992048015 -14.895695658518699 -5.098731803083344 -7.1320164017346865 50.02916973576702 0.5
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
feature_list is [0, 0, 2, 0, 0, 0, 11.027932673783878]
Vestimate is  11.027932673783878
Machine 1's move
[[0. 1. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Moves array [1]
Machine 2's move
[[0. 1. 0.]
 [0. 0. 0.]
 [0. 0. 2.]]
feature_list is [0, 0, 3, 2, 0, 0, -8.33483193276884]
Vestimate is  -8.33483193276884
Machine 1's move
[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 2.]]
Moves array [1, 8, 5]
Machine 2's move
[[2. 1. 0.]
 [0. 0. 1.]
 [0. 0. 2.]]
feature_list is [0, 1, 3, 0, 0, 0, -8.966494787818165]
Vestimate is  -8.966494787818165
Machine 1's move
[[2. 1. 0.]
 [0. 0. 1.]
 [1. 0. 2.]]
Moves array [1, 8, 5, 0, 6]
Machine 2's move
[[2. 1. 0.]
 [2. 0. 1.]
 [1. 0. 2.]]
feature_list is [2, 0, 0, 0, 0, 0, -18.612451704145464]
Vestimate is  -18.612451704145464
Machine 1's move
[[2. 1. 0.]
 [2. 1. 1.]
 [1. 0. 2.]]
Moves array

feature_list is [1, 0, 4, 1, 0, 0, 103.97773765956636]
Vestimate is  103.97773765956636
Machine 1's move
[[0. 0. 1.]
 [2. 1. 0.]
 [0. 0. 0.]]
Moves array [4, 3, 2]
Machine 2's move
[[0. 0. 1.]
 [2. 1. 0.]
 [0. 0. 2.]]
feature_list is [0, 0, 2, 0, 1, 0, 98.89342427636701]
Vestimate is  98.89342427636701
Machine 1's move
[[0. 0. 1.]
 [2. 1. 0.]
 [1. 0. 2.]]
Moves array [4, 3, 2, 8, 6]
Game Over
Machine1 won
Game counter 40
length of f1 3
weights after update 46.35035455409267 14.328942059518692 1.0034805732901033 8.676484285195222 -7.459831455047073 31.012685788051186 0.5
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
feature_list is [0, 0, 4, 0, 0, 0, 81.05629169487355]
Vestimate is  81.05629169487355
Machine 1's move
[[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]
Moves array [4]
Machine 2's move
[[0. 0. 0.]
 [2. 1. 0.]
 [0. 0. 0.]]
feature_list is [1, 0, 4, 1, 0, 0, 87.92540229934517]
Vestimate is  87.92540229934517
Machine 1's move
[[0. 0. 1.]
 [2. 1. 0.]
 [0. 0. 0.]]
Moves array [4, 3, 2]
Machine 2's mo

Machine 1's move
[[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]
Moves array [4]
Machine 2's move
[[0. 0. 0.]
 [0. 1. 2.]
 [0. 0. 0.]]
feature_list is [0, 0, 4, 1, 0, 0, 62.858329294315524]
Vestimate is  62.858329294315524
Machine 1's move
[[0. 0. 0.]
 [1. 1. 2.]
 [0. 0. 0.]]
Moves array [4, 5, 3]
Machine 2's move
[[0. 0. 0.]
 [1. 1. 2.]
 [0. 2. 0.]]
feature_list is [0, 0, 4, 2, 0, 0, 69.67913037471304]
Vestimate is  69.67913037471304
Machine 1's move
[[0. 1. 0.]
 [1. 1. 2.]
 [0. 2. 0.]]
Moves array [4, 5, 3, 7, 1]
Machine 2's move
[[2. 1. 0.]
 [1. 1. 2.]
 [0. 2. 0.]]
feature_list is [1, 0, 0, 1, 0, 0, 51.2565756606763]
Vestimate is  51.2565756606763
Machine 1's move
[[2. 1. 1.]
 [1. 1. 2.]
 [0. 2. 0.]]
Moves array [4, 5, 3, 7, 1, 0, 2]
Machine 2's move
[[2. 1. 1.]
 [1. 1. 2.]
 [2. 2. 0.]]
feature_list is [0, 0, 0, 0, 0, 0, 48.15233339395582]
Vestimate is  48.15233339395582
Machine 1's move
[[2. 1. 1.]
 [1. 1. 2.]
 [2. 2. 1.]]
Moves array [4, 5, 3, 7, 1, 0, 2, 6, 8]
Game Tie
Game counter 63
lengt

Game counter 82
length of f1 3
weights after update 65.85539944912782 1.7026308103296266 -25.054019650095412 3.8793255330810794 11.791106681352248 39.99494824045171 0.5
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
feature_list is [0, 0, 4, 0, 0, 0, 81.37270158145213]
Vestimate is  81.37270158145213
Machine 1's move
[[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]
Moves array [4]
Machine 2's move
[[0. 0. 0.]
 [0. 1. 0.]
 [2. 0. 0.]]
feature_list is [0, 0, 5, 2, 0, 0, 108.8342404772377]
Vestimate is  108.8342404772377
Machine 1's move
[[0. 0. 1.]
 [0. 1. 0.]
 [2. 0. 0.]]
Moves array [4, 6, 2]
Machine 2's move
[[0. 0. 1.]
 [0. 1. 0.]
 [2. 0. 2.]]
feature_list is [1, 0, 2, 1, 0, 0, 87.10778800697184]
Vestimate is  87.10778800697184
Machine 1's move
[[0. 0. 1.]
 [0. 1. 0.]
 [2. 1. 2.]]
Moves array [4, 6, 2, 8, 7]
Machine 2's move
[[0. 0. 1.]
 [2. 1. 0.]
 [2. 1. 2.]]
feature_list is [2, 0, 0, 0, 0, 0, 69.26066106978706]
Vestimate is  69.26066106978706
Machine 1's move
[[1. 0. 1.]
 [2. 1. 0.]
 [2. 1. 2.]]
Moves 

length of f1 4
weights after update 76.85675454409224 9.485864956888657 -25.054019650095412 -1.7381034275008385 -0.7619110171174861 14.514384993713362 0.5
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
feature_list is [0, 0, 2, 0, 0, 0, 73.38054768909056]
Vestimate is  73.38054768909056
Machine 1's move
[[0. 1. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Moves array [1]
Machine 2's move
[[0. 1. 0.]
 [0. 0. 0.]
 [2. 0. 0.]]
feature_list is [1, 0, 1, 2, 0, 0, 83.0806940392451]
Vestimate is  83.0806940392451
Machine 1's move
[[0. 1. 0.]
 [0. 0. 0.]
 [2. 1. 0.]]
Moves array [1, 6, 7]
Machine 2's move
[[0. 1. 0.]
 [2. 0. 0.]
 [2. 1. 0.]]
feature_list is [2, 0, 1, 2, 0, 0, 92.56655899613375]
Vestimate is  92.56655899613375
Machine 1's move
[[1. 1. 0.]
 [2. 0. 0.]
 [2. 1. 0.]]
Moves array [1, 6, 7, 3, 0]
Machine 2's move
[[1. 1. 0.]
 [2. 2. 0.]
 [2. 1. 0.]]
feature_list is [0, 1, 1, 0, 1, 0, 64.57901646020935]
Vestimate is  64.57901646020935
Machine 1's move
[[1. 1. 1.]
 [2. 2. 0.]
 [2. 1. 0.]]
Moves array [1, 6, 7, 

Moves array [4, 7, 0]
Machine 2's move
[[1. 0. 2.]
 [0. 1. 0.]
 [0. 2. 0.]]
feature_list is [0, 0, 2, 0, 1, 0, 95.97559103609099]
Vestimate is  95.97559103609099
Machine 1's move
[[1. 0. 2.]
 [0. 1. 0.]
 [0. 2. 1.]]
Moves array [4, 7, 0, 2, 8]
Game Over
Machine1 won
Game counter 122
length of f1 3
weights after update 75.13406159395663 8.164059341317687 -21.21127724200894 3.9618741695825563 -4.528068454126081 14.31583197155457 0.5
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
feature_list is [0, 0, 4, 0, 0, 0, 90.98155827228686]
Vestimate is  90.98155827228686
Machine 1's move
[[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]
Moves array [4]
Machine 2's move
[[0. 2. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]
feature_list is [1, 0, 3, 0, 0, 0, 95.18374344402199]
Vestimate is  95.18374344402199
Machine 1's move
[[1. 2. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]
Moves array [4, 1, 0]
Machine 2's move
[[1. 2. 0.]
 [0. 1. 2.]
 [0. 0. 0.]]
feature_list is [0, 0, 3, 0, 1, 0, 101.33551607425888]
Vestimate is  101.33551607425888
Machine 1's mo

 [2. 1. 0.]]
feature_list is [0, 0, 0, 0, 0, 0, 73.7954719474513]
Vestimate is  73.7954719474513
Machine 1's move
[[2. 1. 1.]
 [1. 2. 2.]
 [2. 1. 1.]]
Moves array [1, 6, 7, 4, 2, 5, 3, 0, 8]
Game Tie
Game counter 143
length of f1 5
weights after update 66.39302476315444 8.214143592554056 -21.21127724200894 0.36953205656777266 -1.7921254344581605 14.718393663019526 0.5
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
feature_list is [0, 0, 4, 0, 0, 0, 67.87115298942554]
Vestimate is  67.87115298942554
Machine 1's move
[[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]
Moves array [4]
Machine 2's move
[[0. 0. 2.]
 [0. 1. 0.]
 [0. 0. 0.]]
feature_list is [1, 0, 3, 1, 0, 0, 73.92363909095366]
Vestimate is  73.92363909095366
Machine 1's move
[[1. 0. 2.]
 [0. 1. 0.]
 [0. 0. 0.]]
Moves array [4, 2, 0]
Machine 2's move
[[1. 0. 2.]
 [0. 1. 2.]
 [0. 0. 0.]]
feature_list is [0, 0, 3, 0, 1, 0, 82.22001459587729]
Vestimate is  82.22001459587729
Machine 1's move
[[1. 0. 2.]
 [0. 1. 2.]
 [0. 0. 1.]]
Moves array [4, 2, 0, 5, 8

feature_list is [0, 0, 0, 0, 0, 0, 72.43620175023023]
Vestimate is  72.43620175023023
Machine 1's move
[[2. 1. 1.]
 [1. 1. 2.]
 [2. 1. 2.]]
Moves array [4, 0, 2, 6, 3, 8, 7, 5, 1]
Game Over
Machine1 won
Game counter 163
length of f1 5
weights after update 73.96753867081752 5.419291046493746 -21.21127724200894 4.113542710784414 -2.893445306766785 17.24927719181801 0.5
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
feature_list is [0, 0, 4, 0, 0, 0, 90.42170951395518]
Vestimate is  90.42170951395518
Machine 1's move
[[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]
Moves array [4]
Machine 2's move
[[0. 0. 2.]
 [0. 1. 0.]
 [0. 0. 0.]]
feature_list is [1, 0, 3, 1, 0, 0, 88.83401254289772]
Vestimate is  88.83401254289772
Machine 1's move
[[1. 0. 2.]
 [0. 1. 0.]
 [0. 0. 0.]]
Moves array [4, 2, 0]
Machine 2's move
[[1. 0. 2.]
 [0. 1. 0.]
 [2. 0. 0.]]
feature_list is [0, 0, 2, 0, 1, 0, 99.44390128420436]
Vestimate is  99.44390128420436
Machine 1's move
[[1. 0. 2.]
 [0. 1. 0.]
 [2. 0. 1.]]
Moves array [4, 2, 0, 6, 8]

Machine 2's move
[[2. 2. 1.]
 [0. 1. 0.]
 [0. 0. 0.]]
feature_list is [3, 0, 0, 1, 0, 0, 101.69359740821766]
Vestimate is  101.69359740821766
Machine 1's move
[[2. 2. 1.]
 [0. 1. 1.]
 [0. 0. 0.]]
Moves array [4, 0, 2, 1, 5]
Machine 2's move
[[2. 2. 1.]
 [0. 1. 1.]
 [0. 2. 0.]]
feature_list is [2, 0, 0, 0, 1, 0, 105.82292328687089]
Vestimate is  105.82292328687089
Machine 1's move
[[2. 2. 1.]
 [0. 1. 1.]
 [1. 2. 0.]]
Moves array [4, 0, 2, 1, 5, 7, 6]
Game Over
Machine1 won
Game counter 184
length of f1 4
weights after update 77.91118395574783 7.6605450687819 -21.21127724200894 5.345179080004574 -1.0349738840852523 10.19413320445492 0.5
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
feature_list is [0, 0, 4, 0, 0, 0, 99.29190027576612]
Vestimate is  99.29190027576612
Machine 1's move
[[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]
Moves array [4]
Machine 2's move
[[0. 0. 0.]
 [0. 1. 0.]
 [2. 0. 0.]]
feature_list is [0, 0, 5, 2, 0, 0, 102.5671315876002]
Vestimate is  102.5671315876002
Machine 1's move
[[0. 0.

Moves array [4]
Machine 2's move
[[0. 0. 0.]
 [0. 1. 2.]
 [0. 0. 0.]]
feature_list is [1, 0, 4, 1, 0, 0, 95.42482456378121]
Vestimate is  95.42482456378121
Machine 1's move
[[1. 0. 0.]
 [0. 1. 2.]
 [0. 0. 0.]]
Moves array [4, 5, 0]
Machine 2's move
[[1. 0. 0.]
 [2. 1. 2.]
 [0. 0. 0.]]
feature_list is [0, 0, 4, 0, 1, 0, 109.99710630730941]
Vestimate is  109.99710630730941
Machine 1's move
[[1. 0. 0.]
 [2. 1. 2.]
 [0. 0. 1.]]
Moves array [4, 5, 0, 3, 8]
Game Over
Machine1 won
Game counter 204
length of f1 3
weights after update 64.20800396191866 8.880366547052922 -21.21127724200894 -0.9445713734101755 -3.361439151257895 15.511045491689915 0.5
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
feature_list is [0, 0, 2, 0, 0, 0, 62.31886121509831]
Vestimate is  62.31886121509831
Machine 1's move
[[0. 1. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Moves array [1]
Machine 2's move
[[0. 1. 0.]
 [0. 0. 2.]
 [0. 0. 0.]]
feature_list is [1, 0, 2, 1, 0, 0, 67.83778861089334]
Vestimate is  67.83778861089334
Machine 1's move
[

Vestimate is  89.09614767828278
Machine 1's move
[[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]
Moves array [4]
Machine 2's move
[[0. 0. 0.]
 [0. 1. 2.]
 [0. 0. 0.]]
feature_list is [1, 0, 4, 1, 0, 0, 93.4990858312672]
Vestimate is  93.4990858312672
Machine 1's move
[[1. 0. 0.]
 [0. 1. 2.]
 [0. 0. 0.]]
Moves array [4, 5, 0]
Machine 2's move
[[1. 0. 2.]
 [0. 1. 2.]
 [0. 0. 0.]]
feature_list is [0, 0, 3, 0, 1, 0, 99.66522020395477]
Vestimate is  99.66522020395477
Machine 1's move
[[1. 0. 2.]
 [0. 1. 2.]
 [0. 0. 1.]]
Moves array [4, 5, 0, 2, 8]
Game Over
Machine1 won
Game counter 225
length of f1 3
weights after update 65.35819233724331 9.9106440849898 -21.21127724200894 6.051002463138564 -5.771478029482571 16.12134815641772 0.5
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
feature_list is [0, 0, 4, 0, 0, 0, 89.56220218979757]
Vestimate is  89.56220218979757
Machine 1's move
[[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]
Moves array [4]
Machine 2's move
[[0. 2. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]
feature_list is [1, 0, 4, 1

weights after update 75.40875897242859 7.960851561810612 -21.21127724200894 5.655384183868745 -3.330089488892524 13.585681566241243 0.5
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
feature_list is [0, 0, 4, 0, 0, 0, 98.03029570790356]
Vestimate is  98.03029570790356
Machine 1's move
[[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]
Moves array [4]
Machine 2's move
[[0. 0. 0.]
 [0. 1. 0.]
 [0. 2. 0.]]
feature_list is [1, 0, 4, 1, 0, 0, 102.66105778082165]
Vestimate is  102.66105778082165
Machine 1's move
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 2. 0.]]
Moves array [4, 7, 0]
Machine 2's move
[[1. 2. 0.]
 [0. 1. 0.]
 [0. 2. 0.]]
feature_list is [0, 0, 4, 0, 1, 0, 111.61597727414481]
Vestimate is  111.61597727414481
Machine 1's move
[[1. 2. 0.]
 [0. 1. 0.]
 [0. 2. 1.]]
Moves array [4, 7, 0, 1, 8]
Game Over
Machine1 won
Game counter 245
length of f1 3
weights after update 73.84722422205446 8.069113958746854 -21.21127724200894 -0.5907548176277206 -3.2218270919562824 11.452808211639077 0.5
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]

Machine 1's move
[[1. 2. 0.]
 [0. 1. 0.]
 [0. 2. 1.]]
Moves array [4, 7, 0, 1, 8]
Game Over
Machine1 won
Game counter 265
length of f1 3
weights after update 78.77475513739772 7.278661365356059 -21.21127724200894 -0.8437230595604026 -3.180528042324037 9.881791218600043 0.5
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
feature_list is [0, 0, 2, 0, 0, 0, 77.08730901827691]
Vestimate is  77.08730901827691
Machine 1's move
[[0. 1. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Moves array [1]
Machine 2's move
[[0. 1. 0.]
 [2. 0. 0.]
 [0. 0. 0.]]
feature_list is [1, 0, 2, 1, 0, 0, 81.18544234130893]
Vestimate is  81.18544234130893
Machine 1's move
[[1. 1. 0.]
 [2. 0. 0.]
 [0. 0. 0.]]
Moves array [1, 3, 0]
Machine 2's move
[[1. 1. 0.]
 [2. 0. 2.]
 [0. 0. 0.]]
feature_list is [3, 0, 1, 1, 0, 0, 96.58648813158145]
Vestimate is  96.58648813158145
Machine 1's move
[[1. 1. 0.]
 [2. 1. 2.]
 [0. 0. 0.]]
Moves array [1, 3, 0, 5, 4]
Machine 2's move
[[1. 1. 2.]
 [2. 1. 2.]
 [0. 0. 0.]]
feature_list is [1, 0, 1, 0, 1, 0, 95.091

Moves array [4, 6, 0]
Machine 2's move
[[1. 0. 0.]
 [0. 1. 2.]
 [2. 0. 0.]]
feature_list is [0, 0, 2, 0, 1, 0, 96.36708575209221]
Vestimate is  96.36708575209221
Machine 1's move
[[1. 0. 0.]
 [0. 1. 2.]
 [2. 0. 1.]]
Moves array [4, 6, 0, 5, 8]
Game Over
Machine1 won
Game counter 287
length of f1 3
weights after update 82.90838893899426 5.490096770079289 -21.21127724200894 3.9148176162466233 -1.5977381160770747 7.926958577237714 0.5
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
feature_list is [0, 0, 4, 0, 0, 0, 98.56765940398076]
Vestimate is  98.56765940398076
Machine 1's move
[[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]
Moves array [4]
Machine 2's move
[[0. 0. 2.]
 [0. 1. 0.]
 [0. 0. 0.]]
feature_list is [0, 0, 5, 2, 0, 0, 99.28700078807323]
Vestimate is  99.28700078807323
Machine 1's move
[[0. 0. 2.]
 [0. 1. 0.]
 [1. 0. 0.]]
Moves array [4, 2, 6]
Machine 2's move
[[0. 0. 2.]
 [2. 1. 0.]
 [1. 0. 0.]]
feature_list is [2, 0, 1, 1, 0, 0, 96.2056619793224]
Vestimate is  96.2056619793224
Machine 1's move


weights after update 63.27802698165199 9.35020075690182 -16.80953060377987 8.734250020735688 -6.057532295781507 15.24191689155991 0.5
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
feature_list is [0, 0, 4, 0, 0, 0, 98.21502706459475]
Vestimate is  98.21502706459475
Machine 1's move
[[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]
Moves array [4]
Machine 2's move
[[0. 0. 0.]
 [0. 1. 0.]
 [0. 2. 0.]]
feature_list is [1, 0, 4, 1, 0, 0, 101.50769552571505]
Vestimate is  101.50769552571505
Machine 1's move
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 2. 0.]]
Moves array [4, 7, 0]
Machine 2's move
[[1. 2. 0.]
 [0. 1. 0.]
 [0. 2. 0.]]
feature_list is [0, 0, 4, 0, 1, 0, 113.45694395615466]
Vestimate is  113.45694395615466
Machine 1's move
[[1. 2. 0.]
 [0. 1. 0.]
 [0. 2. 1.]]
Moves array [4, 7, 0, 1, 8]
Game Over
Machine1 won
Game counter 308
length of f1 3
weights after update 61.25722595050065 9.98537196155533 -16.80953060377987 0.65104589613032 -5.422361091127997 12.256677809643028 0.5
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
featu

Game counter 328
length of f1 5
weights after update 58.642270909537956 6.095434635477875 -14.715143286319453 -0.28493400975544114 -6.806053630003778 16.537887485865305 0.5
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
feature_list is [0, 0, 2, 0, 0, 0, 58.07240289002707]
Vestimate is  58.07240289002707
Machine 1's move
[[0. 1. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Moves array [1]
Machine 2's move
[[0. 1. 0.]
 [2. 0. 0.]
 [0. 0. 0.]]
feature_list is [1, 0, 2, 1, 0, 0, 57.36178389550117]
Vestimate is  57.36178389550117
Machine 1's move
[[1. 1. 0.]
 [2. 0. 0.]
 [0. 0. 0.]]
Moves array [1, 3, 0]
Machine 2's move
[[1. 1. 0.]
 [2. 2. 0.]
 [0. 0. 0.]]
feature_list is [0, 1, 1, 0, 1, 0, 60.18008109932837]
Vestimate is  60.18008109932837
Machine 1's move
[[1. 1. 1.]
 [2. 2. 0.]
 [0. 0. 0.]]
Moves array [1, 3, 0, 4, 2]
Game Over
Machine1 won
Game counter 329
length of f1 3
weights after update 62.79667193906462 6.41279530558689 -10.807041027449218 4.115765790427644 -6.488692959894763 20.44598974473554 0.5
[[0. 0

Moves array [4, 6, 0, 8, 7, 5, 2, 1, 3]
Game Tie
Game counter 349
length of f1 5
weights after update 55.97383064689276 5.884772220767066 -8.332594410277787 5.770597933037418 -4.698712949483619 20.00068075531178 0.5
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
feature_list is [0, 0, 4, 0, 0, 0, 79.05622237904242]
Vestimate is  79.05622237904242
Machine 1's move
[[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]
Moves array [4]
Machine 2's move
[[0. 0. 0.]
 [0. 1. 2.]
 [0. 0. 0.]]
feature_list is [1, 0, 4, 1, 0, 0, 80.24228165032588]
Vestimate is  80.24228165032588
Machine 1's move
[[1. 0. 0.]
 [0. 1. 2.]
 [0. 0. 0.]]
Moves array [4, 5, 0]
Machine 2's move
[[1. 0. 0.]
 [2. 1. 2.]
 [0. 0. 0.]]
feature_list is [0, 0, 4, 0, 1, 0, 99.0569031343542]
Vestimate is  99.0569031343542
Machine 1's move
[[1. 0. 0.]
 [2. 1. 2.]
 [0. 0. 1.]]
Moves array [4, 5, 0, 3, 8]
Game Over
Machine1 won
Game counter 350
length of f1 3
weights after update 54.80923373386824 7.564604293051712 -8.332594410277787 1.1122102809393546 -3.01

weights after update 67.01580825673543 11.600433250151665 -8.332594410277787 6.059962456202519 -3.7711350577061467 18.41408623411473 0.5
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
feature_list is [0, 0, 4, 0, 0, 0, 91.2556580815455]
Vestimate is  91.2556580815455
Machine 1's move
[[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]
Moves array [4]
Machine 2's move
[[0. 0. 0.]
 [0. 1. 0.]
 [0. 2. 0.]]
feature_list is [1, 0, 4, 1, 0, 0, 99.08495627399103]
Vestimate is  99.08495627399103
Machine 1's move
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 2. 0.]]
Moves array [4, 7, 0]
Machine 2's move
[[1. 2. 0.]
 [0. 1. 0.]
 [0. 2. 0.]]
feature_list is [0, 0, 4, 0, 1, 0, 109.66974431566024]
Vestimate is  109.66974431566024
Machine 1's move
[[1. 2. 0.]
 [0. 1. 0.]
 [0. 2. 1.]]
Moves array [4, 7, 0, 1, 8]
Game Over
Machine1 won
Game counter 370
length of f1 3
weights after update 65.6915342736824 11.327931361602849 -8.332594410277787 0.7628665239903665 -4.0436369462549635 16.579384320365957 0.5
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
fe

weights after update 63.59085646211073 -1.1898824173125524 -13.373790952327994 -22.737546327879688 -16.567097460221696 18.876373340276526 0.5
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
feature_list is [0, 0, 2, 0, 0, 0, 18.115763806351353]
Vestimate is  18.115763806351353
Machine 1's move
[[0. 1. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Moves array [1]
Machine 2's move
[[2. 1. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
feature_list is [1, 0, 1, 2, 0, 0, 6.5292327964751]
Vestimate is  6.5292327964751
Machine 1's move
[[2. 1. 0.]
 [0. 0. 0.]
 [0. 1. 0.]]
Moves array [1, 0, 7]
Machine 2's move
[[2. 1. 0.]
 [0. 0. 0.]
 [2. 1. 0.]]
feature_list is [0, 1, 1, 0, 0, 0, 27.479519181903047]
Vestimate is  27.479519181903047
Machine 1's move
[[2. 1. 0.]
 [0. 1. 0.]
 [2. 1. 0.]]
Moves array [1, 0, 7, 6, 4]
Game Over
Machine1 won
Game counter 391
length of f1 3
weights after update 71.98594702830034 1.2527421515265305 -6.262671853989826 -15.501108862677686 -11.68184832254353 18.876373340276526 0.5
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0

Machine 2's move
[[1. 2. 0.]
 [0. 1. 0.]
 [0. 0. 2.]]
feature_list is [2, 0, 1, 1, 0, 0, 88.36020373898822]
Vestimate is  88.36020373898822
Machine 1's move
[[1. 2. 0.]
 [0. 1. 0.]
 [1. 0. 2.]]
Moves array [4, 1, 0, 8, 6]
Machine 2's move
[[1. 2. 0.]
 [0. 1. 0.]
 [1. 2. 2.]]
feature_list is [1, 0, 1, 0, 1, 0, 103.57871880242473]
Vestimate is  103.57871880242473
Machine 1's move
[[1. 2. 1.]
 [0. 1. 0.]
 [1. 2. 2.]]
Moves array [4, 1, 0, 8, 6, 7, 2]
Game Over
Machine1 won
Game counter 410
length of f1 4
weights after update 66.71829527842935 12.60831239827474 -29.611394256034316 4.458656760184575 -1.7033458663947172 21.996679422147995 0.5
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
feature_list is [0, 0, 4, 0, 0, 0, 84.55292231916765]
Vestimate is  84.55292231916765
Machine 1's move
[[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]
Moves array [4]
Machine 2's move
[[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 2.]]
feature_list is [1, 0, 3, 1, 0, 0, 90.9992320908631]
Vestimate is  90.9992320908631
Machine 1's move
[[0. 0.

Moves array [4, 6, 0]
Machine 2's move
[[1. 0. 2.]
 [0. 1. 0.]
 [2. 0. 0.]]
feature_list is [0, 0, 2, 0, 1, 0, 94.6113718286769]
Vestimate is  94.6113718286769
Machine 1's move
[[1. 0. 2.]
 [0. 1. 0.]
 [2. 0. 1.]]
Moves array [4, 6, 0, 2, 8]
Game Over
Machine1 won
Game counter 430
length of f1 3
weights after update 70.74450364007633 8.926183618918841 -29.611394256034316 6.810972982640102 -3.3579164144461657 15.199361855528563 0.5
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
feature_list is [0, 0, 4, 0, 0, 0, 97.98839557063674]
Vestimate is  97.98839557063674
Machine 1's move
[[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]
Moves array [4]
Machine 2's move
[[0. 0. 0.]
 [0. 1. 0.]
 [0. 2. 0.]]
feature_list is [1, 0, 4, 1, 0, 0, 103.55666277510942]
Vestimate is  103.55666277510942
Machine 1's move
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 2. 0.]]
Moves array [4, 7, 0]
Machine 2's move
[[1. 0. 0.]
 [0. 1. 2.]
 [0. 2. 0.]]
feature_list is [0, 0, 3, 0, 1, 0, 106.3767844435252]
Vestimate is  106.3767844435252
Machine 1's mo

Machine 1's move
[[0. 0. 2.]
 [0. 1. 0.]
 [1. 0. 0.]]
Moves array [4, 2, 6]
Machine 2's move
[[0. 0. 2.]
 [2. 1. 0.]
 [1. 0. 0.]]
feature_list is [0, 0, 3, 1, 0, 0, 84.96169816395607]
Vestimate is  84.96169816395607
Machine 1's move
[[0. 0. 2.]
 [2. 1. 1.]
 [1. 0. 0.]]
Moves array [4, 2, 6, 3, 5]
Machine 2's move
[[0. 2. 2.]
 [2. 1. 1.]
 [1. 0. 0.]]
feature_list is [1, 0, 1, 0, 0, 0, 79.87627888829654]
Vestimate is  79.87627888829654
Machine 1's move
[[1. 2. 2.]
 [2. 1. 1.]
 [1. 0. 0.]]
Moves array [4, 2, 6, 3, 5, 1, 0]
Machine 2's move
[[1. 2. 2.]
 [2. 1. 1.]
 [1. 0. 2.]]
feature_list is [0, 0, 0, 0, 0, 0, 67.49712298710719]
Vestimate is  67.49712298710719
Machine 1's move
[[1. 2. 2.]
 [2. 1. 1.]
 [1. 1. 2.]]
Moves array [4, 2, 6, 3, 5, 1, 0, 8, 7]
Game Tie
Game counter 451
length of f1 5
weights after update 60.27064502919817 4.641572586397546 -29.611394256034316 4.429606732055731 -3.2179127198917734 12.934060073431093 0.5
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
feature_list is [0, 0, 4

feature_list is [0, 0, 4, 0, 0, 0, 90.16944062741513]
Vestimate is  90.16944062741513
Machine 1's move
[[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]
Moves array [4]
Machine 2's move
[[2. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]
feature_list is [1, 0, 3, 1, 0, 0, 93.14300674288305]
Vestimate is  93.14300674288305
Machine 1's move
[[2. 0. 1.]
 [0. 1. 0.]
 [0. 0. 0.]]
Moves array [4, 0, 2]
Machine 2's move
[[2. 2. 1.]
 [0. 1. 0.]
 [0. 0. 0.]]
feature_list is [0, 0, 3, 0, 1, 0, 99.32738589759157]
Vestimate is  99.32738589759157
Machine 1's move
[[2. 2. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]
Moves array [4, 0, 2, 1, 6]
Game Over
Machine1 won
Game counter 472
length of f1 3
weights after update 70.04935569843565 10.168029061501029 -29.611394256034316 5.256054730816282 -1.7061794661739933 13.63130360388551 0.5
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
feature_list is [0, 0, 4, 0, 0, 0, 91.07357462170077]
Vestimate is  91.07357462170077
Machine 1's move
[[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]
Moves array [4]
Machine 2's move
[[0

weights after update 69.28106813304109 9.5412623874306 -29.611394256034316 3.852923897863495 -5.003926031389266 18.620831184871008 0.5
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
feature_list is [0, 0, 4, 0, 0, 0, 84.69276372449507]
Vestimate is  84.69276372449507
Machine 1's move
[[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]
Moves array [4]
Machine 2's move
[[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 2.]]
feature_list is [1, 0, 3, 1, 0, 0, 85.37717618267291]
Vestimate is  85.37717618267291
Machine 1's move
[[0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 2.]]
Moves array [4, 8, 2]
Machine 2's move
[[0. 0. 1.]
 [2. 1. 0.]
 [0. 0. 2.]]
feature_list is [0, 0, 2, 0, 1, 0, 95.60774711363909]
Vestimate is  95.60774711363909
Machine 1's move
[[0. 0. 1.]
 [2. 1. 0.]
 [1. 0. 2.]]
Moves array [4, 8, 2, 3, 6]
Game Over
Machine1 won
Game counter 493
length of f1 3
weights after update 70.00736258831901 10.475345860964099 -29.611394256034316 6.376478773588402 -4.069842557855766 18.344600920797642 0.5
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
feat

Vestimate is  83.90727863907495
Machine 1's move
[[1. 1. 1.]
 [2. 2. 1.]
 [1. 2. 2.]]
Moves array [1, 4, 0, 8, 6, 3, 5, 7, 2]
Game Over
Machine1 won
Game counter 513
length of f1 5
weights after update 73.01922879395187 8.18247497680745 -29.611394256034316 0.9364820633662256 -3.056385167757093 14.741522484014538 0.5
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
feature_list is [0, 0, 4, 0, 0, 0, 76.76515704741676]
Vestimate is  76.76515704741676
Machine 1's move
[[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]
Moves array [4]
Machine 2's move
[[2. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]
feature_list is [1, 0, 3, 1, 0, 0, 80.9547647931009]
Vestimate is  80.9547647931009
Machine 1's move
[[2. 0. 1.]
 [0. 1. 0.]
 [0. 0. 0.]]
Moves array [4, 0, 2]
Machine 2's move
[[2. 0. 1.]
 [0. 1. 0.]
 [0. 0. 2.]]
feature_list is [0, 0, 2, 0, 1, 0, 89.63371540469886]
Vestimate is  89.63371540469886
Machine 1's move
[[2. 0. 1.]
 [0. 1. 0.]
 [1. 0. 2.]]
Moves array [4, 0, 2, 8, 6]
Game Over
Machine1 won
Game counter 514
length of f1 

Moves array [1, 3, 0]
Machine 2's move
[[1. 1. 0.]
 [2. 0. 0.]
 [2. 0. 0.]]
feature_list is [3, 0, 0, 1, 0, 0, 8.543361748305655]
Vestimate is  8.543361748305655
Machine 1's move
[[1. 1. 0.]
 [2. 1. 0.]
 [2. 0. 0.]]
Moves array [1, 3, 0, 6, 4]
Machine 2's move
[[1. 1. 2.]
 [2. 1. 0.]
 [2. 0. 0.]]
feature_list is [1, 0, 0, 0, 1, 0, 54.291126106484114]
Vestimate is  54.291126106484114
Machine 1's move
[[1. 1. 2.]
 [2. 1. 0.]
 [2. 0. 1.]]
Moves array [1, 3, 0, 6, 4, 2, 8]
Game Over
Machine1 won
Game counter 534
length of f1 4
weights after update 55.99409530545601 6.050031289441138 -43.47593040410318 -13.73995706027322 -4.34691198707331 17.917722852186447 0.5
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
feature_list is [0, 0, 2, 0, 0, 0, 28.514181184909567]
Vestimate is  28.514181184909567
Machine 1's move
[[0. 1. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Moves array [1]
Machine 2's move
[[0. 1. 0.]
 [2. 0. 0.]
 [0. 0. 0.]]
feature_list is [1, 0, 2, 1, 0, 0, 30.217300487277395]
Vestimate is  30.21730048727739

Machine 1's move
[[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]
Moves array [4]
Machine 2's move
[[0. 0. 2.]
 [0. 1. 0.]
 [0. 0. 0.]]
feature_list is [1, 0, 3, 1, 0, 0, 80.34907047369988]
Vestimate is  80.34907047369988
Machine 1's move
[[1. 0. 2.]
 [0. 1. 0.]
 [0. 0. 0.]]
Moves array [4, 2, 0]
Machine 2's move
[[1. 0. 2.]
 [2. 1. 0.]
 [0. 0. 0.]]
feature_list is [0, 0, 2, 0, 1, 0, 91.4911929565185]
Vestimate is  91.4911929565185
Machine 1's move
[[1. 0. 2.]
 [2. 1. 0.]
 [0. 0. 1.]]
Moves array [4, 2, 0, 3, 8]
Game Over
Machine1 won
Game counter 553
length of f1 3
weights after update 58.12532181383662 13.118760116377754 -57.11743920366478 9.014889106443622 -4.404612164042135 23.55592235571409 0.5
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
feature_list is [0, 0, 4, 0, 0, 0, 94.18487823961111]
Vestimate is  94.18487823961111
Machine 1's move
[[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]
Moves array [4]
Machine 2's move
[[2. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]
feature_list is [0, 0, 5, 2, 0, 0, 94.39054301797046]
Ve

weights after update 54.24292316036607 12.528598216143523 -57.11743920366478 7.608061559424543 -6.2190475478317815 22.191610321018725 0.5
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
feature_list is [0, 0, 4, 0, 0, 0, 84.67516939806424]
Vestimate is  84.67516939806424
Machine 1's move
[[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]
Moves array [4]
Machine 2's move
[[0. 0. 0.]
 [2. 1. 0.]
 [0. 0. 0.]]
feature_list is [1, 0, 4, 1, 0, 0, 90.984720066376]
Vestimate is  90.984720066376
Machine 1's move
[[0. 0. 1.]
 [2. 1. 0.]
 [0. 0. 0.]]
Moves array [4, 3, 2]
Machine 2's move
[[0. 0. 1.]
 [2. 1. 2.]
 [0. 0. 0.]]
feature_list is [0, 0, 4, 0, 1, 0, 106.86677971908297]
Vestimate is  106.86677971908297
Machine 1's move
[[0. 0. 1.]
 [2. 1. 2.]
 [1. 0. 0.]]
Moves array [4, 3, 2, 5, 6]
Game Over
Machine1 won
Game counter 574
length of f1 3
weights after update 52.75366899551556 13.044180567801222 -57.11743920366478 1.6510449000225016 -5.703465196174083 19.55581873767934 0.5
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
feat

 [2. 0. 1.]]
Moves array [4, 6, 0, 1, 8]
Game Over
Machine1 won
Game counter 594
length of f1 3
weights after update 50.17690753981688 13.792590771215139 -57.11743920366478 12.97626414151259 -6.6497624270461175 22.72237822254741 0.5
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
feature_list is [0, 0, 4, 0, 0, 0, 102.08196410586724]
Vestimate is  102.08196410586724
Machine 1's move
[[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]
Moves array [4]
Machine 2's move
[[0. 0. 0.]
 [0. 1. 0.]
 [2. 0. 0.]]
feature_list is [0, 0, 5, 2, 0, 0, 101.75870339328759]
Vestimate is  101.75870339328759
Machine 1's move
[[0. 0. 1.]
 [0. 1. 0.]
 [2. 0. 0.]]
Moves array [4, 6, 2]
Machine 2's move
[[0. 2. 1.]
 [0. 1. 0.]
 [2. 0. 0.]]
feature_list is [2, 0, 1, 1, 0, 0, 84.08859079671363]
Vestimate is  84.08859079671363
Machine 1's move
[[0. 2. 1.]
 [0. 1. 0.]
 [2. 0. 1.]]
Moves array [4, 6, 2, 1, 8]
Machine 2's move
[[0. 2. 1.]
 [0. 1. 2.]
 [2. 0. 1.]]
feature_list is [0, 0, 0, 0, 1, 0, 72.89928576236429]
Vestimate is  72.8992857

feature_list is [0, 0, 4, 0, 0, 0, 99.83706659183359]
Vestimate is  99.83706659183359
Machine 1's move
[[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]
Moves array [4]
Machine 2's move
[[2. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]
feature_list is [0, 0, 5, 2, 0, 0, 101.12935507668908]
Vestimate is  101.12935507668908
Machine 1's move
[[2. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Moves array [4, 0, 8]
Machine 2's move
[[2. 0. 2.]
 [0. 1. 0.]
 [0. 0. 1.]]
feature_list is [1, 0, 2, 1, 0, 0, 84.73744641218316]
Vestimate is  84.73744641218316
Machine 1's move
[[2. 1. 2.]
 [0. 1. 0.]
 [0. 0. 1.]]
Moves array [4, 0, 8, 2, 1]
Machine 2's move
[[2. 1. 2.]
 [0. 1. 0.]
 [2. 0. 1.]]
feature_list is [2, 0, 0, 0, 0, 0, 80.67492815252808]
Vestimate is  80.67492815252808
Machine 1's move
[[2. 1. 2.]
 [1. 1. 0.]
 [2. 0. 1.]]
Moves array [4, 0, 8, 2, 1, 6, 3]
Machine 2's move
[[2. 1. 2.]
 [1. 1. 2.]
 [2. 0. 1.]]
feature_list is [0, 0, 0, 0, 0, 0, 50.519504972430255]
Vestimate is  50.519504972430255
Machine 1's move
[[2. 1. 2.]
 [1. 

Vestimate is  97.56987168783198
Machine 1's move
[[0. 2. 1.]
 [0. 1. 0.]
 [1. 0. 2.]]
Moves array [4, 1, 6, 8, 2]
Game Over
Machine1 won
Game counter 638
length of f1 3
weights after update 56.273811028882854 12.907625651119018 -57.11743920366478 7.023519514070556 -7.829383675682884 23.452431320033025 0.5
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
feature_list is [0, 0, 4, 0, 0, 0, 84.36788908516507]
Vestimate is  84.36788908516507
Machine 1's move
[[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]
Moves array [4]
Machine 2's move
[[0. 0. 2.]
 [0. 1. 0.]
 [0. 0. 0.]]
feature_list is [1, 0, 3, 1, 0, 0, 82.42261154653065]
Vestimate is  82.42261154653065
Machine 1's move
[[1. 0. 2.]
 [0. 1. 0.]
 [0. 0. 0.]]
Moves array [4, 2, 0]
Machine 2's move
[[1. 2. 2.]
 [0. 1. 0.]
 [0. 0. 0.]]
feature_list is [0, 0, 3, 0, 1, 0, 100.79680089112755]
Vestimate is  100.79680089112755
Machine 1's move
[[1. 2. 2.]
 [0. 1. 0.]
 [0. 0. 1.]]
Moves array [4, 2, 0, 1, 8]
Game Over
Machine1 won
Game counter 639
length of f1 3
weigh

Machine 1's move
[[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]
Moves array [4]
Machine 2's move
[[2. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]
feature_list is [1, 0, 3, 1, 0, 0, 83.00889785101324]
Vestimate is  83.00889785101324
Machine 1's move
[[2. 0. 1.]
 [0. 1. 0.]
 [0. 0. 0.]]
Moves array [4, 0, 2]
Machine 2's move
[[2. 0. 1.]
 [2. 1. 0.]
 [0. 0. 0.]]
feature_list is [0, 0, 3, 0, 1, 0, 99.22831731890241]
Vestimate is  99.22831731890241
Machine 1's move
[[2. 0. 1.]
 [2. 1. 0.]
 [1. 0. 0.]]
Moves array [4, 0, 2, 3, 6]
Game Over
Machine1 won
Game counter 658
length of f1 3
weights after update 57.087305396226405 12.201118909356069 -57.11743920366478 6.9034421519676705 -2.7933398170182144 20.657594469191434 0.5
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
feature_list is [0, 0, 4, 0, 0, 0, 84.70107400409708]
Vestimate is  84.70107400409708
Machine 1's move
[[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]
Moves array [4]
Machine 2's move
[[0. 0. 0.]
 [2. 1. 0.]
 [0. 0. 0.]]
feature_list is [1, 0, 4, 1, 0, 0, 94.108853096434

 [0. 0. 0.]]
feature_list is [1, 0, 3, 1, 0, 0, 98.72137466069051]
Vestimate is  98.72137466069051
Machine 1's move
[[2. 0. 1.]
 [0. 1. 0.]
 [0. 0. 0.]]
Moves array [4, 0, 2]
Machine 2's move
[[2. 0. 1.]
 [0. 1. 0.]
 [2. 0. 0.]]
feature_list is [1, 0, 2, 1, 0, 0, 90.55193371290899]
Vestimate is  90.55193371290899
Machine 1's move
[[2. 0. 1.]
 [1. 1. 0.]
 [2. 0. 0.]]
Moves array [4, 0, 2, 6, 3]
Machine 2's move
[[2. 0. 1.]
 [1. 1. 0.]
 [2. 0. 2.]]
feature_list is [2, 0, 0, 0, 0, 0, 92.45872795283748]
Vestimate is  92.45872795283748
Machine 1's move
[[2. 0. 1.]
 [1. 1. 0.]
 [2. 1. 2.]]
Moves array [4, 0, 2, 6, 3, 8, 7]
Machine 2's move
[[2. 0. 1.]
 [1. 1. 2.]
 [2. 1. 2.]]
feature_list is [0, 0, 0, 0, 0, 0, 67.98671224171147]
Vestimate is  67.98671224171147
Machine 1's move
[[2. 1. 1.]
 [1. 1. 2.]
 [2. 1. 2.]]
Moves array [4, 0, 2, 6, 3, 8, 7, 5, 1]
Game Over
Machine1 won
Game counter 679
length of f1 5
weights after update 69.02291679957817 7.504116523119219 -50.510991305847085 7.4461083

Machine 2's move
[[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 2.]]
feature_list is [0, 0, 5, 2, 0, 0, 84.48211293163406]
Vestimate is  84.48211293163406
Machine 1's move
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 2.]]
Moves array [4, 8, 0]
Machine 2's move
[[1. 0. 0.]
 [0. 1. 2.]
 [0. 0. 2.]]
feature_list is [2, 0, 2, 1, 0, 0, 86.43699721622771]
Vestimate is  86.43699721622771
Machine 1's move
[[1. 0. 1.]
 [0. 1. 2.]
 [0. 0. 2.]]
Moves array [4, 8, 0, 5, 2]
Machine 2's move
[[1. 0. 1.]
 [2. 1. 2.]
 [0. 0. 2.]]
feature_list is [1, 0, 1, 0, 1, 0, 94.03210511496758]
Vestimate is  94.03210511496758
Machine 1's move
[[1. 0. 1.]
 [2. 1. 2.]
 [1. 0. 2.]]
Moves array [4, 8, 0, 5, 2, 3, 6]
Game Over
Machine1 won
Game counter 699
length of f1 4
weights after update 59.22912528165928 9.918122824188222 -50.510991305847085 9.59675446307104 -2.9715726332711654 19.74975490155459 0.5
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
feature_list is [0, 0, 4, 0, 0, 0, 97.61614313394344]
Vestimate is  97.61614313394344
Machine 1's move
[[0

Machine 1's move
[[2. 0. 0.]
 [1. 1. 0.]
 [2. 0. 1.]]
Moves array [4, 0, 8, 6, 3]
Machine 2's move
[[2. 0. 2.]
 [1. 1. 0.]
 [2. 0. 1.]]
feature_list is [2, 0, 0, 0, 0, 0, 85.46247558393978]
Vestimate is  85.46247558393978
Machine 1's move
[[2. 1. 2.]
 [1. 1. 0.]
 [2. 0. 1.]]
Moves array [4, 0, 8, 6, 3, 2, 1]
Machine 2's move
[[2. 1. 2.]
 [1. 1. 2.]
 [2. 0. 1.]]
feature_list is [0, 0, 0, 0, 0, 0, 64.37542152586796]
Vestimate is  64.37542152586796
Machine 1's move
[[2. 1. 2.]
 [1. 1. 2.]
 [2. 1. 1.]]
Moves array [4, 0, 8, 6, 3, 2, 1, 5, 7]
Game Over
Machine1 won
Game counter 718
length of f1 5
weights after update 65.97525905152467 7.196282001403875 -50.510991305847085 4.100428399495575 -4.069034974571943 20.382217238945362 0.5
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
feature_list is [0, 0, 4, 0, 0, 0, 82.37697264950697]
Vestimate is  82.37697264950697
Machine 1's move
[[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]
Moves array [4]
Machine 2's move
[[0. 0. 2.]
 [0. 1. 0.]
 [0. 0. 0.]]
feature_list is [

length of f1 4
weights after update 68.76987356013669 10.964252549285664 -50.510991305847085 7.305875248356115 -3.064009145488555 14.863615677259576 0.5
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
feature_list is [0, 0, 4, 0, 0, 0, 97.99337455356115]
Vestimate is  97.99337455356115
Machine 1's move
[[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]
Moves array [4]
Machine 2's move
[[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 2.]]
feature_list is [0, 0, 5, 2, 0, 0, 99.17123151094015]
Vestimate is  99.17123151094015
Machine 1's move
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 2.]]
Moves array [4, 8, 0]
Machine 2's move
[[1. 0. 2.]
 [0. 1. 0.]
 [0. 0. 2.]]
feature_list is [1, 0, 2, 1, 0, 0, 91.28186746064603]
Vestimate is  91.28186746064603
Machine 1's move
[[1. 0. 2.]
 [0. 1. 1.]
 [0. 0. 2.]]
Moves array [4, 8, 0, 2, 5]
Machine 2's move
[[1. 0. 2.]
 [2. 1. 1.]
 [0. 0. 2.]]
feature_list is [1, 0, 0, 0, 0, 0, 79.73412610942235]
Vestimate is  79.73412610942235
Machine 1's move
[[1. 0. 2.]
 [2. 1. 1.]
 [0. 1. 2.]]
Moves array [4, 8, 0, 

Game Over
Machine1 won
Game counter 757
length of f1 5
weights after update 61.516189835313426 9.082887916239114 -50.510991305847085 4.036620785254864 -5.94239787842145 18.19250569033692 0.5
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
feature_list is [0, 0, 4, 0, 0, 0, 77.66267297633289]
Vestimate is  77.66267297633289
Machine 1's move
[[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]
Moves array [4]
Machine 2's move
[[0. 0. 0.]
 [0. 1. 2.]
 [0. 0. 0.]]
feature_list is [1, 0, 3, 0, 0, 0, 82.70894010731713]
Vestimate is  82.70894010731713
Machine 1's move
[[0. 0. 1.]
 [0. 1. 2.]
 [0. 0. 0.]]
Moves array [4, 5, 2]
Machine 2's move
[[0. 2. 1.]
 [0. 1. 2.]
 [0. 0. 0.]]
feature_list is [0, 0, 3, 0, 1, 0, 91.81855788141493]
Vestimate is  91.81855788141493
Machine 1's move
[[0. 2. 1.]
 [0. 1. 2.]
 [1. 0. 0.]]
Moves array [4, 5, 2, 1, 6]
Game Over
Machine1 won
Game counter 758
length of f1 3
weights after update 62.18294603324241 9.337834966620942 -50.510991305847085 6.5415160921402284 -5.94239787842145 18.099688

feature_list is [1, 0, 2, 1, 0, 0, 89.69453947256487]
Vestimate is  89.69453947256487
Machine 1's move
[[2. 0. 0.]
 [1. 1. 0.]
 [2. 0. 1.]]
Moves array [4, 0, 8, 6, 3]
Machine 2's move
[[2. 2. 0.]
 [1. 1. 0.]
 [2. 0. 1.]]
feature_list is [2, 0, 0, 0, 0, 0, 83.13444329901841]
Vestimate is  83.13444329901841
Machine 1's move
[[2. 2. 1.]
 [1. 1. 0.]
 [2. 0. 1.]]
Moves array [4, 0, 8, 6, 3, 1, 2]
Machine 2's move
[[2. 2. 1.]
 [1. 1. 2.]
 [2. 0. 1.]]
feature_list is [0, 0, 0, 0, 0, 0, 69.61632381109261]
Vestimate is  69.61632381109261
Machine 1's move
[[2. 2. 1.]
 [1. 1. 2.]
 [2. 1. 1.]]
Moves array [4, 0, 8, 6, 3, 1, 2, 5, 7]
Game Tie
Game counter 777
length of f1 5
weights after update 61.24354207404751 5.468095852099154 -50.510991305847085 -0.3900780369454555 -2.5918312415588733 16.275984289767806 0.5
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
feature_list is [0, 0, 2, 0, 0, 0, 60.4633860001566]
Vestimate is  60.4633860001566
Machine 1's move
[[0. 1. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Moves array [1

Moves array [4, 8, 2]
Machine 2's move
[[2. 0. 1.]
 [0. 1. 0.]
 [0. 0. 2.]]
feature_list is [0, 0, 2, 0, 1, 0, 94.38075051268252]
Vestimate is  94.38075051268252
Machine 1's move
[[2. 0. 1.]
 [0. 1. 0.]
 [1. 0. 2.]]
Moves array [4, 8, 2, 0, 6]
Game Over
Machine1 won
Game counter 796
length of f1 3
weights after update 70.30577314763394 10.712052354722736 -50.510991305847085 6.2346096510352185 -3.1904510308908245 15.923356709124104 0.5
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
feature_list is [0, 0, 4, 0, 0, 0, 95.24421175177481]
Vestimate is  95.24421175177481
Machine 1's move
[[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]
Moves array [4]
Machine 2's move
[[0. 0. 0.]
 [0. 1. 0.]
 [0. 2. 0.]]
feature_list is [1, 0, 4, 1, 0, 0, 102.76581307560673]
Vestimate is  102.76581307560673
Machine 1's move
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 2. 0.]]
Moves array [4, 7, 0]
Machine 2's move
[[1. 0. 0.]
 [0. 1. 0.]
 [2. 2. 0.]]
feature_list is [0, 0, 3, 0, 1, 0, 104.9329588098637]
Vestimate is  104.9329588098637
Machine 1'

Moves array [4]
Machine 2's move
[[0. 2. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]
feature_list is [1, 0, 3, 0, 0, 0, 76.68662652066892]
Vestimate is  76.68662652066892
Machine 1's move
[[1. 2. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]
Moves array [4, 1, 0]
Machine 2's move
[[1. 2. 2.]
 [0. 1. 0.]
 [0. 0. 0.]]
feature_list is [0, 0, 3, 0, 1, 0, 85.33650724503191]
Vestimate is  85.33650724503191
Machine 1's move
[[1. 2. 2.]
 [0. 1. 0.]
 [0. 0. 1.]]
Moves array [4, 1, 0, 2, 8]
Game Over
Machine1 won
Game counter 816
length of f1 3
weights after update 60.46166738196853 7.6383560699998885 -50.510991305847085 7.8720645279686465 -4.624606137718653 16.523500237186028 0.5
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
feature_list is [0, 0, 4, 0, 0, 0, 91.94992549384312]
Vestimate is  91.94992549384312
Machine 1's move
[[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]
Moves array [4]
Machine 2's move
[[0. 0. 2.]
 [0. 1. 0.]
 [0. 0. 0.]]
feature_list is [0, 0, 5, 2, 0, 0, 90.57277774637446]
Vestimate is  90.57277774637446
Machine 1's move
[[

length of f1 3
weights after update 57.13600031175489 11.116640446350296 -50.510991305847085 6.626872999811081 -4.573351728505482 22.540717815181566 0.5
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
feature_list is [0, 0, 4, 0, 0, 0, 83.64349231099922]
Vestimate is  83.64349231099922
Machine 1's move
[[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]
Moves array [4]
Machine 2's move
[[2. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]
feature_list is [1, 0, 3, 1, 0, 0, 83.55990802903294]
Vestimate is  83.55990802903294
Machine 1's move
[[2. 0. 1.]
 [0. 1. 0.]
 [0. 0. 0.]]
Moves array [4, 0, 2]
Machine 2's move
[[2. 0. 1.]
 [0. 1. 0.]
 [0. 2. 0.]]
feature_list is [0, 0, 2, 0, 1, 0, 92.93046412655862]
Vestimate is  92.93046412655862
Machine 1's move
[[2. 0. 1.]
 [0. 1. 0.]
 [1. 2. 0.]]
Moves array [4, 0, 2, 7, 6]
Game Over
Machine1 won
Game counter 838
length of f1 3
weights after update 58.12649452620182 12.064562012758481 -50.510991305847085 9.539066138719871 -3.6254301620972975 22.591648891416938 0.5
[[0. 0. 0.]
 [0. 0. 0.

length of f1 3
weights after update 68.39180067558127 6.0723555079654075 -50.510991305847085 6.163856617837685 -2.787285291532144 18.747764456270442 0.5
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
feature_list is [0, 0, 4, 0, 0, 0, 93.047227146932]
Vestimate is  93.047227146932
Machine 1's move
[[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]
Moves array [4]
Machine 2's move
[[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 2.]]
feature_list is [0, 0, 5, 2, 0, 0, 93.6365131817054]
Vestimate is  93.6365131817054
Machine 1's move
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 2.]]
Moves array [4, 8, 0]
Machine 2's move
[[1. 0. 0.]
 [0. 1. 2.]
 [0. 0. 2.]]
feature_list is [2, 0, 2, 1, 0, 0, 90.07693963565531]
Vestimate is  90.07693963565531
Machine 1's move
[[1. 0. 1.]
 [0. 1. 2.]
 [0. 0. 2.]]
Moves array [4, 8, 0, 5, 2]
Machine 2's move
[[1. 0. 1.]
 [0. 1. 2.]
 [0. 2. 2.]]
feature_list is [2, 0, 0, 0, 1, 0, 99.28427614778252]
Vestimate is  99.28427614778252
Machine 1's move
[[1. 0. 1.]
 [0. 1. 2.]
 [1. 2. 2.]]
Moves array [4, 8, 0, 5, 2, 

feature_list is [2, 0, 0, 0, 1, 0, 100.41975758648562]
Vestimate is  100.41975758648562
Machine 1's move
[[1. 2. 2.]
 [0. 1. 2.]
 [1. 0. 1.]]
Moves array [4, 1, 6, 2, 0, 5, 8]
Game Over
Machine1 won
Game counter 874
length of f1 4
weights after update 72.66039990871383 7.391664317815011 -50.510991305847085 5.257690227383052 -1.3206621828252614 15.581320071816895 0.5
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
feature_list is [0, 0, 4, 0, 0, 0, 93.69116081824603]
Vestimate is  93.69116081824603
Machine 1's move
[[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]
Moves array [4]
Machine 2's move
[[0. 0. 0.]
 [0. 1. 0.]
 [2. 0. 0.]]
feature_list is [0, 0, 5, 2, 0, 0, 96.30752667997857]
Vestimate is  96.30752667997857
Machine 1's move
[[0. 0. 1.]
 [0. 1. 0.]
 [2. 0. 0.]]
Moves array [4, 6, 2]
Machine 2's move
[[0. 0. 1.]
 [0. 1. 0.]
 [2. 0. 2.]]
feature_list is [1, 0, 2, 1, 0, 0, 89.24678249846968]
Vestimate is  89.24678249846968
Machine 1's move
[[0. 0. 1.]
 [0. 1. 0.]
 [2. 1. 2.]]
Moves array [4, 6, 2, 8, 7]


Machine 2's move
[[0. 2. 0.]
 [0. 1. 0.]
 [1. 0. 2.]]
feature_list is [0, 0, 2, 0, 1, 0, 95.03148281104336]
Vestimate is  95.03148281104336
Machine 1's move
[[0. 2. 1.]
 [0. 1. 0.]
 [1. 0. 2.]]
Moves array [4, 1, 6, 8, 2]
Game Over
Machine1 won
Game counter 897
length of f1 3
weights after update 71.81293624352125 6.308885018596202 -50.510991305847085 5.300601282591569 -3.9601424512649475 13.88790694241252 0.5
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
feature_list is [0, 0, 4, 0, 0, 0, 93.01534137388752]
Vestimate is  93.01534137388752
Machine 1's move
[[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]
Moves array [4]
Machine 2's move
[[0. 0. 2.]
 [0. 1. 0.]
 [0. 0. 0.]]
feature_list is [0, 0, 5, 2, 0, 0, 90.3956577539492]
Vestimate is  90.3956577539492
Machine 1's move
[[0. 0. 2.]
 [0. 1. 0.]
 [1. 0. 0.]]
Moves array [4, 2, 6]
Machine 2's move
[[0. 0. 2.]
 [0. 1. 0.]
 [1. 0. 2.]]
feature_list is [1, 0, 2, 1, 0, 0, 84.76288137603565]
Vestimate is  84.76288137603565
Machine 1's move
[[0. 0. 2.]
 [0. 1. 1.

feature_list is [0, 0, 3, 0, 1, 0, 99.8603825599049]
Vestimate is  99.8603825599049
Machine 1's move
[[1. 0. 2.]
 [0. 1. 2.]
 [0. 0. 1.]]
Moves array [4, 5, 0, 2, 8]
Game Over
Machine1 won
Game counter 915
length of f1 3
weights after update 77.05859111575063 6.659124172901358 -50.510991305847085 3.281079065696047 -2.5623694916168533 12.846755306835629 0.5
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
feature_list is [0, 0, 4, 0, 0, 0, 90.18290737853482]
Vestimate is  90.18290737853482
Machine 1's move
[[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]
Moves array [4]
Machine 2's move
[[0. 0. 0.]
 [0. 1. 0.]
 [0. 2. 0.]]
feature_list is [1, 0, 4, 1, 0, 0, 94.27966205981933]
Vestimate is  94.27966205981933
Machine 1's move
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 2. 0.]]
Moves array [4, 7, 0]
Machine 2's move
[[1. 0. 2.]
 [0. 1. 0.]
 [0. 2. 0.]]
feature_list is [0, 0, 2, 0, 1, 0, 96.46750455397836]
Vestimate is  96.46750455397836
Machine 1's move
[[1. 0. 2.]
 [0. 1. 0.]
 [0. 2. 1.]]
Moves array [4, 7, 0, 2, 8]
Game Over


[[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]
Moves array [4]
Machine 2's move
[[2. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]
feature_list is [0, 0, 5, 2, 0, 0, 95.03147485485198]
Vestimate is  95.03147485485198
Machine 1's move
[[2. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Moves array [4, 0, 8]
Machine 2's move
[[2. 2. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
feature_list is [2, 0, 2, 1, 0, 0, 94.78449293736527]
Vestimate is  94.78449293736527
Machine 1's move
[[2. 2. 1.]
 [0. 1. 0.]
 [0. 0. 1.]]
Moves array [4, 0, 8, 1, 2]
Machine 2's move
[[2. 2. 1.]
 [0. 1. 0.]
 [0. 2. 1.]]
feature_list is [1, 0, 1, 0, 1, 0, 99.38560387024873]
Vestimate is  99.38560387024873
Machine 1's move
[[2. 2. 1.]
 [0. 1. 0.]
 [1. 2. 1.]]
Moves array [4, 0, 8, 1, 2, 7, 6]
Game Over
Machine1 won
Game counter 939
length of f1 4
weights after update 69.49555675539918 8.438796449848164 -50.510991305847085 7.718419079862289 -3.1912428336190777 15.267458381747643 0.5
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
feature_list is [0, 0, 4, 0, 0, 0, 100.369233074848

Game counter 962
length of f1 3
weights after update 72.34167115909848 10.168162950393738 -50.510991305847085 5.513200889615101 -3.067967678820131 10.738979506479199 0.5
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
feature_list is [0, 0, 4, 0, 0, 0, 94.3944747175589]
Vestimate is  94.3944747175589
Machine 1's move
[[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]
Moves array [4]
Machine 2's move
[[0. 0. 0.]
 [0. 1. 2.]
 [0. 0. 0.]]
feature_list is [1, 0, 4, 1, 0, 0, 101.4946699891325]
Vestimate is  101.4946699891325
Machine 1's move
[[1. 0. 0.]
 [0. 1. 2.]
 [0. 0. 0.]]
Moves array [4, 5, 0]
Machine 2's move
[[1. 0. 0.]
 [0. 1. 2.]
 [2. 0. 0.]]
feature_list is [3, 0, 0, 2, 0, 0, 96.71022465263944]
Vestimate is  96.71022465263944
Machine 1's move
[[1. 1. 0.]
 [0. 1. 2.]
 [2. 0. 0.]]
Moves array [4, 5, 0, 6, 1]
Machine 2's move
[[1. 1. 0.]
 [0. 1. 2.]
 [2. 0. 2.]]
feature_list is [1, 1, 0, 0, 1, 0, 42.73782231012433]
Vestimate is  42.73782231012433
Machine 1's move
[[1. 1. 1.]
 [0. 1. 2.]
 [2. 0. 2.]]
Moves a

Machine1 won
Game counter 983
length of f1 3
weights after update 71.02028082400545 7.613300551915515 -42.735897723981026 5.397526124906955 -3.929903309600118 12.839531328399282 0.5
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
feature_list is [0, 0, 4, 0, 0, 0, 92.61038532363327]
Vestimate is  92.61038532363327
Machine 1's move
[[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]
Moves array [4]
Machine 2's move
[[0. 0. 0.]
 [0. 1. 0.]
 [0. 2. 0.]]
feature_list is [1, 0, 4, 1, 0, 0, 96.29378256594867]
Vestimate is  96.29378256594867
Machine 1's move
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 2. 0.]]
Moves array [4, 7, 0]
Machine 2's move
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 2. 2.]]
feature_list is [2, 0, 2, 1, 0, 0, 93.11203086805027]
Vestimate is  93.11203086805027
Machine 1's move
[[1. 0. 0.]
 [0. 1. 0.]
 [1. 2. 2.]]
Moves array [4, 7, 0, 8, 6]
Machine 2's move
[[1. 0. 0.]
 [0. 1. 2.]
 [1. 2. 2.]]
feature_list is [2, 0, 0, 0, 1, 0, 99.08641325623577]
Vestimate is  99.08641325623577
Machine 1's move
[[1. 0. 1.]
 [0. 1. 2.]
 [1. 2

## Execute below two blocks for playing / testing with human player

##### This is for making the moves of the human player

In [58]:
def human_move(moves_entered):
    move_entered = 0
    while (move_entered == 0):
        human_position = int(input("enter your move 1 - 9 ")) - 1
        if human_position > 8 or human_position < 0:
            print("Enter your move between 1 - 9")
        elif human_position not in moves_entered:
            #game_board[position // 3, position % 3] = 1
            move_entered = 2
            #clear_output()
            #print(game_board)
        else:
            print("Enter into a blank cell")
    return(human_position)

#### Pitting the human with the smart agent

In [73]:

#positions = []
winning_moves = [[0,1,2],[0,3,6],[0,4,8],[1,4,7],[2,5,8],[2,4,6],[3,4,5],[6,7,8]]
#start_index = 0


real_game_moves = []
machine_moves = []
human_moves = []
real_game_board = np.zeros([3,3])
#print(real_game_board)
print_game_board(real_game_board)


for i in range(0,9):
    GO = 0
    
    gb_copy = np.copy(real_game_board)
    
    machine_position, vestimate, feature_list = machine1_move(real_game_board, w0, w1, w2, w3, w4, w5, w6)
       
    #machine_position = machine_move(gb_copy.ravel())
    #print(machine_position)
    real_game_board[machine_position // 3, machine_position % 3] = 1
    clear_output()
    #print(real_game_board)
    print_game_board(real_game_board)
    real_game_moves.append(machine_position)
    machine_moves.append(machine_position)
    
    if len(machine_moves) > 2:
        for j in range(len(winning_moves)):
            
            machine_counter = [a for a in machine_moves if a in winning_moves[j]]
            if len(machine_counter)==3:
                print("Game Over")
                print("Machine won")
                GO = 1
                break
    
    if GO == 1:
        break
            
    elif len(machine_moves)+len(human_moves) == 9:
        print("Game Tie")
        break
      
    
    human_game_position = human_move(real_game_moves)
    real_game_board[human_game_position // 3, human_game_position % 3] = 2
    clear_output()
    #print(real_game_board)
    print_game_board(real_game_board)
    real_game_moves.append(human_game_position)
    human_moves.append(human_game_position)
    
    if len(human_moves) > 2:
        for h in range(len(winning_moves)):
            #machine_counter = 0
            human_counter = [b for b in human_moves if b in winning_moves[h]]
            if len(human_counter)==3:
                print("Game Over")
                print("Human won")
                GO = 1
                break
    
    if GO == 1:
        break   
    
    

     |     |     
  X  |  O  |  O  
_____|_____|_____
     |     |     
  O  |  X  |  X  
_____|_____|_____
     |     |     
  X  |  X  |  O  
     |     |     
Game Tie
