In [1]:
import numpy as np
import pandas as pd
import os
from random import randint
from IPython.display import display, clear_output


# moves = []
# machine1_moves = []
# machine2_moves = []
# game_board = np.zeros([3,3])
# print(game_board)
# winning_moves = [[0,1,2],[0,3,6],[0,4,8],[1,4,7],[2,5,8],[2,4,6],[3,4,5],[6,7,8]]


'''
def human_move():
    move_entered = 0
    while (move_entered == 0):
        position = int(input("enter your move 1 - 9 ")) - 1
        if position > 8 or position < 0:
            print("Enter your move between 1 - 9")
        elif position not in moves:
            game_board[position // 3, position % 3] = 1
            move_entered = 1
            #clear_output()
            print(game_board)
        else:
            print("Enter into a blank cell")
    return(position)
'''

  


'\ndef human_move():\n    move_entered = 0\n    while (move_entered == 0):\n        position = int(input("enter your move 1 - 9 ")) - 1\n        if position > 8 or position < 0:\n            print("Enter your move between 1 - 9")\n        elif position not in moves:\n            game_board[position // 3, position % 3] = 1\n            move_entered = 1\n            #clear_output()\n            print(game_board)\n        else:\n            print("Enter into a blank cell")\n    return(position)\n'

In [2]:
def machine1_move():
    while(True):
        machine1_position = randint(0,8)
        if machine1_position not in moves:
            #game_board[machine1_position // 3, machine1_position % 3] = 1
            moves.append(machine1_position)
            
            #clear_output()
            print("Machine 1's move")
            break
    return(machine1_position)



In [3]:

def machine2_move():
    while(True):
        machine2_position = randint(0,8)
        if machine2_position not in moves:
            #game_board[machine2_position // 3, machine2_position % 3] = 2
            moves.append(machine2_position)
            
            #clear_output()
            print("Machine 2's move")
            break
    return(machine2_position)



In [20]:

positions = []
winning_moves = [[0,1,2],[0,3,6],[0,4,8],[1,4,7],[2,5,8],[2,4,6],[3,4,5],[6,7,8]]
start_index = 0

for m in range(0,200):
    #np.zeros([3,3])
    
    
    moves = []
    machine1_moves = []
    machine2_moves = []
    game_board = np.zeros([3,3])
    print(game_board)
    
    for i in range(0,9):
        GO = 0
        machine1_position = machine1_move()
        game_board[machine1_position // 3, machine1_position % 3] = 1
        print(game_board)
        mc1 = np.copy(game_board)
        positions.append(mc1.ravel().tolist())
        moves.append(machine1_position)
        machine1_moves.append(machine1_position)
        machine1_counter = 0
        
        ## If more than one moves are made, then keep checking in the winning moves list
        
        if len(machine1_moves) > 2:
            for j in range(len(winning_moves)):
                #human_counter = 0
                machine1_counter = [a for a in machine1_moves if a in winning_moves[j]]
                if len(machine1_counter)==3:
                    print("Game Over")
                    print("Machine1 won")
                    GO = 1
                    break

        if GO == 1:
            for p in range(start_index,len(positions)):
                positions[p].extend([1])
            #print(positions)
            start_index = len(positions)
            break
        elif len(machine1_moves)+len(machine2_moves) ==9:
            print("Game Tie")
            for p in range(start_index,len(positions)):
         
                positions[p].extend([0])
            #print(positions)
            start_index = len(positions)
            
            break

        machine2_position = machine2_move()
        
        game_board[machine2_position // 3, machine2_position % 3] = 2
        print(game_board)
        mc2 = np.copy(game_board)
        positions.append(mc2.ravel().tolist())
        moves.append(machine2_position)
        machine2_moves.append(machine2_position)
        machine2_counter = 0
        if len(machine2_moves) > 2:
            for h in range(len(winning_moves)):
                #machine_counter = 0
                machine2_counter = [b for b in machine2_moves if b in winning_moves[h]]
                if len(machine2_counter)==3:
                    print("Game Over")
                    print("Machine2 won")
                    GO = 1
                    break

        if GO == 1:
            for p in range(start_index,len(positions)):
             
                positions[p].extend([2])
            #print(positions)
            start_index = len(positions)
            break   

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Machine 1's move
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 1.]]
Machine 2's move
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 2. 1.]]
Machine 1's move
[[0. 1. 0.]
 [0. 0. 0.]
 [0. 2. 1.]]
Machine 2's move
[[0. 1. 0.]
 [0. 0. 2.]
 [0. 2. 1.]]
Machine 1's move
[[1. 1. 0.]
 [0. 0. 2.]
 [0. 2. 1.]]
Machine 2's move
[[1. 1. 0.]
 [0. 0. 2.]
 [2. 2. 1.]]
Machine 1's move
[[1. 1. 0.]
 [1. 0. 2.]
 [2. 2. 1.]]
Machine 2's move
[[1. 1. 2.]
 [1. 0. 2.]
 [2. 2. 1.]]
Machine 1's move
[[1. 1. 2.]
 [1. 1. 2.]
 [2. 2. 1.]]
Game Over
Machine1 won
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Machine 1's move
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 1.]]
Machine 2's move
[[0. 0. 0.]
 [0. 0. 2.]
 [0. 0. 1.]]
Machine 1's move
[[0. 0. 0.]
 [1. 0. 2.]
 [0. 0. 1.]]
Machine 2's move
[[2. 0. 0.]
 [1. 0. 2.]
 [0. 0. 1.]]
Machine 1's move
[[2. 0. 0.]
 [1. 0. 2.]
 [1. 0. 1.]]
Machine 2's move
[[2. 0. 0.]
 [1. 0. 2.]
 [1. 2. 1.]]
Machine 1's move
[[2. 0. 1.]
 [1. 0. 2.]
 [1. 2. 1.]]
Machine 2's move
[[2. 0. 1.]
 [1. 2. 2.

Game Tie
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Machine 1's move
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]
Machine 2's move
[[0. 0. 0.]
 [2. 0. 1.]
 [0. 0. 0.]]
Machine 1's move
[[0. 0. 0.]
 [2. 1. 1.]
 [0. 0. 0.]]
Machine 2's move
[[0. 2. 0.]
 [2. 1. 1.]
 [0. 0. 0.]]
Machine 1's move
[[0. 2. 0.]
 [2. 1. 1.]
 [1. 0. 0.]]
Machine 2's move
[[0. 2. 0.]
 [2. 1. 1.]
 [1. 0. 2.]]
Machine 1's move
[[0. 2. 1.]
 [2. 1. 1.]
 [1. 0. 2.]]
Game Over
Machine1 won
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Machine 1's move
[[1. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Machine 2's move
[[1. 0. 0.]
 [0. 2. 0.]
 [0. 0. 0.]]
Machine 1's move
[[1. 0. 0.]
 [0. 2. 0.]
 [0. 0. 1.]]
Machine 2's move
[[1. 0. 0.]
 [0. 2. 0.]
 [0. 2. 1.]]
Machine 1's move
[[1. 0. 0.]
 [1. 2. 0.]
 [0. 2. 1.]]
Machine 2's move
[[1. 0. 2.]
 [1. 2. 0.]
 [0. 2. 1.]]
Machine 1's move
[[1. 0. 2.]
 [1. 2. 0.]
 [1. 2. 1.]]
Game Over
Machine1 won
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Machine 1's move
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]
Machine 2's move
[[0. 0.

 [0. 0. 0.]]
Machine 1's move
[[0. 0. 0.]
 [1. 0. 0.]
 [0. 0. 0.]]
Machine 2's move
[[0. 2. 0.]
 [1. 0. 0.]
 [0. 0. 0.]]
Machine 1's move
[[0. 2. 1.]
 [1. 0. 0.]
 [0. 0. 0.]]
Machine 2's move
[[0. 2. 1.]
 [1. 0. 2.]
 [0. 0. 0.]]
Machine 1's move
[[0. 2. 1.]
 [1. 0. 2.]
 [0. 1. 0.]]
Machine 2's move
[[0. 2. 1.]
 [1. 2. 2.]
 [0. 1. 0.]]
Machine 1's move
[[0. 2. 1.]
 [1. 2. 2.]
 [0. 1. 1.]]
Machine 2's move
[[2. 2. 1.]
 [1. 2. 2.]
 [0. 1. 1.]]
Machine 1's move
[[2. 2. 1.]
 [1. 2. 2.]
 [1. 1. 1.]]
Game Over
Machine1 won
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Machine 1's move
[[0. 0. 0.]
 [0. 0. 0.]
 [1. 0. 0.]]
Machine 2's move
[[0. 0. 0.]
 [0. 0. 0.]
 [1. 0. 2.]]
Machine 1's move
[[0. 0. 0.]
 [0. 1. 0.]
 [1. 0. 2.]]
Machine 2's move
[[2. 0. 0.]
 [0. 1. 0.]
 [1. 0. 2.]]
Machine 1's move
[[2. 0. 0.]
 [1. 1. 0.]
 [1. 0. 2.]]
Machine 2's move
[[2. 0. 2.]
 [1. 1. 0.]
 [1. 0. 2.]]
Machine 1's move
[[2. 0. 2.]
 [1. 1. 0.]
 [1. 1. 2.]]
Machine 2's move
[[2. 0. 2.]
 [1. 1. 2.]
 [1. 1. 2.]]
Game Over

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Machine 1's move
[[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]
Machine 2's move
[[0. 0. 0.]
 [0. 1. 2.]
 [0. 0. 0.]]
Machine 1's move
[[0. 0. 0.]
 [1. 1. 2.]
 [0. 0. 0.]]
Machine 2's move
[[0. 2. 0.]
 [1. 1. 2.]
 [0. 0. 0.]]
Machine 1's move
[[0. 2. 1.]
 [1. 1. 2.]
 [0. 0. 0.]]
Machine 2's move
[[0. 2. 1.]
 [1. 1. 2.]
 [0. 2. 0.]]
Machine 1's move
[[0. 2. 1.]
 [1. 1. 2.]
 [0. 2. 1.]]
Machine 2's move
[[0. 2. 1.]
 [1. 1. 2.]
 [2. 2. 1.]]
Machine 1's move
[[1. 2. 1.]
 [1. 1. 2.]
 [2. 2. 1.]]
Game Over
Machine1 won
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Machine 1's move
[[0. 0. 1.]
 [0. 0. 0.]
 [0. 0. 0.]]
Machine 2's move
[[0. 0. 1.]
 [0. 2. 0.]
 [0. 0. 0.]]
Machine 1's move
[[0. 0. 1.]
 [0. 2. 0.]
 [0. 0. 1.]]
Machine 2's move
[[0. 0. 1.]
 [0. 2. 2.]
 [0. 0. 1.]]
Machine 1's move
[[0. 0. 1.]
 [0. 2. 2.]
 [1. 0. 1.]]
Machine 2's move
[[0. 0. 1.]
 [0. 2. 2.]
 [1. 2. 1.]]
Machine 1's move
[[0. 1. 1.]
 [0. 2. 2.]
 [1. 2. 1.]]
Machine 2's move
[[0. 1. 1.]
 [2. 2. 2.

In [ ]:
moves

In [17]:
target = [item[9] for item in positions]

In [19]:
target.count(1)

93

In [21]:
game_data = pd.DataFrame(positions)

In [22]:
cols = ('pos1','pos2','pos3','pos4','pos5','pos6','pos7','pos8','pos9','Outcome')
game_data.columns=cols

In [23]:
#game_data

In [24]:
from sklearn import datasets
from sklearn import metrics
from sklearn.naive_bayes import GaussianNB

In [25]:
game_data[game_data.columns.difference(["Outcome"])]

pos1  pos2  pos3  pos4  pos5  pos6  pos7  pos8  pos9
0      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   1.0
1      0.0   0.0   0.0   0.0   0.0   0.0   0.0   2.0   1.0
2      0.0   1.0   0.0   0.0   0.0   0.0   0.0   2.0   1.0
3      0.0   1.0   0.0   0.0   0.0   2.0   0.0   2.0   1.0
4      1.0   1.0   0.0   0.0   0.0   2.0   0.0   2.0   1.0
5      1.0   1.0   0.0   0.0   0.0   2.0   2.0   2.0   1.0
6      1.0   1.0   0.0   1.0   0.0   2.0   2.0   2.0   1.0
7      1.0   1.0   2.0   1.0   0.0   2.0   2.0   2.0   1.0
8      1.0   1.0   2.0   1.0   1.0   2.0   2.0   2.0   1.0
9      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   1.0
10     0.0   0.0   0.0   0.0   0.0   2.0   0.0   0.0   1.0
11     0.0   0.0   0.0   1.0   0.0   2.0   0.0   0.0   1.0
12     2.0   0.0   0.0   1.0   0.0   2.0   0.0   0.0   1.0
13     2.0   0.0   0.0   1.0   0.0   2.0   1.0   0.0   1.0
14     2.0   0.0   0.0   1.0   0.0   2.0   1.0   2.0   1.0
15     2.0   0.0   1.0   1.0   0.0   2.0   1.0   2.0   1.0
16     2.0   0.0   1.0   1.0   2.0   2.0   1.0   2.0   1.0
17     2.0   1.0   1.0   1.0   2.0   2.0   1.0   2.0   1.0
18     0.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
19     0.0   1.0   0.0   2.0   0.0   0.0   0.0   0.0   0.0
20     0.0   1.0   0.0   2.0   0.0   0.0   0.0   1.0   0.0
21     0.0   1.0   0.0   2.0   2.0   0.0   0.0   1.0   0.0
22     0.0   1.0   0.0   2.0   2.0   0.0   1.0   1.0   0.0
23     0.0   1.0   2.0   2.0   2.0   0.0   1.0   1.0   0.0
24     0.0   1.0   2.0   2.0   2.0   0.0   1.0   1.0   1.0
25     0.0   0.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0
26     0.0   0.0   1.0   0.0   0.0   0.0   0.0   0.0   2.0
27     0.0   0.0   1.0   0.0   0.0   0.0   1.0   0.0   2.0
28     0.0   0.0   1.0   0.0   0.0   0.0   1.0   2.0   2.0
29     0.0   0.0   1.0   0.0   1.0   0.0   1.0   2.0   2.0
...    ...   ...   ...   ...   ...   ...   ...   ...   ...
1500   0.0   2.0   1.0   0.0   1.0   0.0   0.0   0.0   0.0
1501   0.0   2.0   1.0   0.0   1.0   0.0   0.0   0.0   2.0
1502   0.0   2.0   1.0   0.0   1.0   1.0   0.0   0.0   2.0
1503   0.0   2.0   1.0   0.0   1.0   1.0   2.0   0.0   2.0
1504   0.0   2.0   1.0   1.0   1.0   1.0   2.0   0.0   2.0
1505   0.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
1506   0.0   1.0   2.0   0.0   0.0   0.0   0.0   0.0   0.0
1507   0.0   1.0   2.0   0.0   0.0   0.0   0.0   1.0   0.0
1508   2.0   1.0   2.0   0.0   0.0   0.0   0.0   1.0   0.0
1509   2.0   1.0   2.0   0.0   0.0   1.0   0.0   1.0   0.0
1510   2.0   1.0   2.0   2.0   0.0   1.0   0.0   1.0   0.0
1511   2.0   1.0   2.0   2.0   0.0   1.0   0.0   1.0   1.0
1512   2.0   1.0   2.0   2.0   2.0   1.0   0.0   1.0   1.0
1513   2.0   1.0   2.0   2.0   2.0   1.0   1.0   1.0   1.0
1514   0.0   0.0   0.0   0.0   0.0   0.0   1.0   0.0   0.0
1515   0.0   0.0   0.0   0.0   0.0   2.0   1.0   0.0   0.0
1516   0.0   0.0   0.0   0.0   0.0   2.0   1.0   0.0   1.0
1517   0.0   0.0   0.0   0.0   2.0   2.0   1.0   0.0   1.0
1518   0.0   1.0   0.0   0.0   2.0   2.0   1.0   0.0   1.0
1519   0.0   1.0   2.0   0.0   2.0   2.0   1.0   0.0   1.0
1520   0.0   1.0   2.0   1.0   2.0   2.0   1.0   0.0   1.0
1521   2.0   1.0   2.0   1.0   2.0   2.0   1.0   0.0   1.0
1522   2.0   1.0   2.0   1.0   2.0   2.0   1.0   1.0   1.0
1523   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   1.0
1524   0.0   2.0   0.0   0.0   0.0   0.0   0.0   0.0   1.0
1525   0.0   2.0   0.0   0.0   0.0   0.0   0.0   1.0   1.0
1526   0.0   2.0   0.0   0.0   0.0   2.0   0.0   1.0   1.0
1527   0.0   2.0   0.0   1.0   0.0   2.0   0.0   1.0   1.0
1528   2.0   2.0   0.0   1.0   0.0   2.0   0.0   1.0   1.0
1529   2.0   2.0   0.0   1.0   0.0   2.0   1.0   1.0   1.0

[1530 rows x 9 columns]

In [26]:
model = GaussianNB()
model.fit(game_data[game_data.columns.difference(["Outcome"])], game_data['Outcome'])

GaussianNB(priors=None)

In [27]:
expected = game_data["Outcome"]
predicted = model.predict(test_set)

In [28]:
predicted

array([1, 1, 1, 1, 1, 1, 1])

In [10]:
test_list = [[0,1,2,0,0,0,0,0,0],[0,1,0,2,0,0,0,0,0],[0,1,0,0,2,0,0,0,0],[0,1,0,0,0,2,0,0,0],[0,1,0,0,0,0,2,0,0],[0,1,0,0,0,0,0,2,0],[0,1,1,0,0,0,0,0,2]]

In [47]:
test_list1 = [[2,1,0,2,1,2,0,0,0]]

In [11]:
test_set = pd.DataFrame(test_list)
cols = ('pos1','pos2','pos3','pos4','pos5','pos6','pos7','pos8','pos9')
test_set.columns=cols

In [91]:
test_set

pos1  pos2  pos3  pos4  pos5  pos6  pos7  pos8  pos9
0     0     1     2     0     0     0     0     0     0
1     0     1     0     2     0     0     0     0     0
2     0     1     0     0     2     0     0     0     0
3     0     1     0     0     0     2     0     0     0
4     0     1     0     0     0     0     2     0     0
5     0     1     0     0     0     0     0     2     0
6     0     1     1     0     0     0     0     0     2

In [29]:

#positions = []
winning_moves = [[0,1,2],[0,3,6],[0,4,8],[1,4,7],[2,5,8],[2,4,6],[3,4,5],[6,7,8]]
#start_index = 0


game_moves = []
machine_moves = []
human_moves = []
game_board = np.zeros([3,3])
print(game_board)


for i in range(0,9):
    GO = 0
    
    human_game_position = human_move()
    game_board[human_game_position // 3, human_game_position % 3] = 1
    print(game_board)
    game_moves.append(human_game_position)
    human_moves.append(human_game_position)
    
    if len(human_moves) > 2:
        for h in range(len(winning_moves)):
            #machine_counter = 0
            human_counter = [b for b in human_moves if b in winning_moves[h]]
            if len(human_counter)==3:
                print("Game Over")
                print("Human won")
                GO = 1
                break
    
    if GO == 1:
        break   
    
    gb_copy = np.copy(game_board)
    
    machine_position = machine_move(gb_copy.ravel())
    #print(machine_position)
    game_board[machine_position // 3, machine_position % 3] = 2
    print(game_board)
    game_moves.append(machine_position)
    machine_moves.append(machine_position)
    
    if len(machine_moves) > 2:
        for j in range(len(winning_moves)):
            
            machine_counter = [a for a in machine_moves if a in winning_moves[j]]
            if len(machine_counter)==3:
                print("Game Over")
                print("Machine won")
                GO = 1
                break
    
    if GO == 1:
        break

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
enter your move 1 - 9 1
[[1. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[array([1]), array([1]), array([1]), array([1]), array([1]), array([1]), array([1]), array([1])]
Machine's move
[[2. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
enter your move 1 - 9 2
[[2. 1. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[array([1]), array([1]), array([1]), array([1]), array([1]), array([1]), array([1])]
Machine's move
[[2. 1. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
enter your move 1 - 9 3
[[2. 1. 1.]
 [0. 0. 0.]
 [0. 0. 0.]]
Game Over
Human won


In [14]:
def human_move():
    move_entered = 0
    while (move_entered == 0):
        human_position = int(input("enter your move 1 - 9 ")) - 1
        if human_position > 8 or human_position < 0:
            print("Enter your move between 1 - 9")
        elif human_position not in game_moves:
            #game_board[position // 3, position % 3] = 1
            move_entered = 2
            #clear_output()
            #print(game_board)
        else:
            print("Enter into a blank cell")
    return(human_position)

In [15]:
def machine_move(board_state):
    model_output = []
    #while(True):
        #machine1_position = randint(0,8)
    choices = np.where(board_state==0)[0]

    for x in np.nditer(choices):
        board_state_copy = np.copy(board_state)
        board_state_copy[x]=2
        test_set = pd.DataFrame(board_state_copy)
        test_set = test_set.transpose()
        #print(test_set)
        cols = ('pos1','pos2','pos3','pos4','pos5','pos6','pos7','pos8','pos9')
        test_set.columns=cols
        #print(test_set)
        #print(board_state_copy)
        #print(model.predict(test_set))
        model_output.append(model.predict(test_set))
    
    print(model_output)

    machine_position = np.argmax(model_output)
    #moves.append(machine_position)
    print("Machine's move")
    return(machine_position)
            
#         if machine1_position not in moves:
            
#             #game_board[machine1_position // 3, machine1_position % 3] = 1
#             moves.append(machine1_position)
            
#             #clear_output()
#             print("Machine 1's move")
            #break
    




In [ ]:
b = np.array([1,23,0,9,2,5,0,10,1,2,0])

In [ ]:
choice = np.where(b==0)[0]

In [1]:
np.argmax(model_output)

NameError: name 'np' is not defined

In [ ]:
[b[i]=2 for i in choice]

In [ ]:
model_output = []
for x in np.nditer(choice):
    a = np.copy(b)
    a[x]=2
    model_output.append(model.predict(a))
    print(a)

In [ ]:
a.argmax()

In [ ]:
moves