Allow the two machines to play for n times. One agent has weights and features and calculates the value and makes the move while the other agent makes random moves. create a dataframe with the moves made and the evaluation score. Once the playing is complete, the actual Vtrain values are populated in the dataframe. If it is the last move (game over move), the Vtrain gets 100,0,-100 (w,d,l). Otherwise, the Vtrain value is the evaluation score (estimate) of the subsequent board state. For instance, the Vtrain value of the last but one board state will be the Vestimate of the last move.

In [1]:
import numpy as np
import pandas as pd
import os
import random
from random import randint
from IPython.display import display, clear_output
import ipywidgets as widgets

In [2]:
from ipywidgets import interact, interactive, fixed, interact_manual

## The below code is for feature extraction

In [3]:
def evalboard(test_board):
    #print("Test board inside evalboard", test_board)
    ## two squares in a row (can be row, column or diagonal) are filled with 1 and the other square is empty
    f1 = []
    
    if((np.count_nonzero(test_board[0,:])==2) & (np.sum(test_board[0,:])==2)):
        f1.append(1)
    if((np.count_nonzero(test_board[1,:])==2) & (np.sum(test_board[1,:])==2)):
        f1.append(1)
    if((np.count_nonzero(test_board[2,:])==2) & (np.sum(test_board[2,:])==2)):
        f1.append(1)
    if((np.count_nonzero(test_board[:,0])==2) & (np.sum(test_board[:,0])==2)):
        f1.append(1)
    if((np.count_nonzero(test_board[:,1])==2) & (np.sum(test_board[:,1])==2)):
        f1.append(1)
    if((np.count_nonzero(test_board[:,2])==2) & (np.sum(test_board[:,2])==2)):
        f1.append(1)
    if((np.count_nonzero(test_board.diagonal())==2) & (np.trace(test_board)==2)):
        f1.append(1)
    if((np.count_nonzero(np.fliplr(test_board).diagonal())==2) & (np.trace(np.fliplr(test_board))==2)):
        f1.append(1)

    
    
    ## two squares in a row (can be row, column or diagonal) are filled with 2 and the other square is empty
    f2 = []

    if((np.count_nonzero(test_board[0,:])==2) & (np.sum(test_board[0,:])==4)):
        f2.append(2)
    if((np.count_nonzero(test_board[1,:])==2) & (np.sum(test_board[1,:])==4)):
        f2.append(2)
    if((np.count_nonzero(test_board[2,:])==2) & (np.sum(test_board[2,:])==4)):
        f2.append(2)
    if((np.count_nonzero(test_board[:,0])==2) & (np.sum(test_board[:,0])==4)):
        f2.append(2)
    if((np.count_nonzero(test_board[:,1])==2) & (np.sum(test_board[:,1])==4)):
        f2.append(2)
    if((np.count_nonzero(test_board[:,2])==2) & (np.sum(test_board[:,2])==4)):
        f2.append(2)
    if((np.count_nonzero(test_board.diagonal())==2) & (np.trace(test_board)==4)):
        f2.append(2)
    if((np.count_nonzero(np.fliplr(test_board).diagonal())==2) & (np.trace(np.fliplr(test_board))==4)):
        f2.append(2)
    
    ## One 2 in an otherwise empty row (column, row or diagonal)
    f4 = []
    
    if((np.count_nonzero(test_board[0,:])==1) & (np.sum(test_board[0,:])==2)):
        f4.append(2)
    if((np.count_nonzero(test_board[1,:])==1) & (np.sum(test_board[1,:])==2)):
        f4.append(2)
    if((np.count_nonzero(test_board[2,:])==1) & (np.sum(test_board[2,:])==2)):
        f4.append(2)
    if((np.count_nonzero(test_board[:,0])==1) & (np.sum(test_board[:,0])==2)):
        f4.append(2)
    if((np.count_nonzero(test_board[:,1])==1) & (np.sum(test_board[:,1])==2)):
        f4.append(2)
    if((np.count_nonzero(test_board[:,2])==1) & (np.sum(test_board[:,2])==2)):
        f4.append(2)
    if((np.count_nonzero(test_board.diagonal())==1) & (np.trace(test_board)==2)):
        f4.append(2)
    if((np.count_nonzero(np.fliplr(test_board).diagonal())==1) & (np.trace(np.fliplr(test_board))==2)):
        f4.append(2)
        
    ## One 1 in an otherwise empty row (column, row or diagonal)
    f3 = []
    
    if(np.sum(test_board[0,:])==1):
        f3.append(1)
        
    if(np.sum(test_board[1,:])==1):
        f3.append(1)
        
    if(np.sum(test_board[2,:])==1):
        f3.append(1)
        
    if(np.sum(test_board[:,0])==1):
        f3.append(1)
        
    if(np.sum(test_board[:,1])==1):
        f3.append(1)
        
    if(np.sum(test_board[:,2])==1):
        f3.append(1)
        
    if(np.trace(test_board)==1):
        f3.append(1)
       
    if(np.trace(np.fliplr(test_board))==1):
        f3.append(1)
       

    

    ## Three cells in a row is filled with 1
    f5 = []
    
    if(test_board[0,:]==1).all():
        f5.append(1)
    if(test_board[1,:]==1).all():
        f5.append(1)
    if(test_board[2,:]==1).all():
        f5.append(1)
    if(test_board.diagonal()==1).all():
        f5.append(1)
    if(np.fliplr(test_board).diagonal()==1).all():
        f5.append(1)

    
    ## Three cells in a row is filled with 2
    f6 = []

    
    if(test_board[0,:]==2).all():
        f6.append(2)
    if(test_board[1,:]==2).all():
        f6.append(2)
    if(test_board[2,:]==2).all():
        f6.append(2)
    if(test_board.diagonal()==2).all():
        f6.append(2)
    if(np.fliplr(test_board).diagonal()==2).all():
        f6.append(2)
    
    return(len(f1),len(f2),len(f3),len(f4),len(f5),len(f6))

### The below function is for making the moves of the machine which is trained to become smart

In [4]:
def machine1_move(old_board_state,w0,w1,w2,w3,w4,w5,w6):
    feature_list = []
    board_state = np.copy(old_board_state)
    x, y = np.where(board_state==0)
    #print("weights are ",w0,w1,w2,w3,w4,w5,w6)
    evalscore = []
    for i in range(len(x)):
        board_state[x[i],y[i]]=1

        ft1, ft2, ft3, ft4, ft5, ft6 = evalboard(board_state)
        feature_list.append([ft1,ft2,ft3,ft4,ft5,ft6])
        
        evalscore.append(w0 + w1*ft1 + w2*ft2 + w3*ft3 + w4*ft4 + w5*ft5 + w6*ft6)
        feature_list[i].extend([w0 + w1*ft1 + w2*ft2 + w3*ft3 + w4*ft4 + w5*ft5 + w6*ft6])
        #print("features",feature_list)
        #print("evalscore",evalscore)
        board_state = np.copy(old_board_state)
        

    position_index = np.argmax(np.asarray(evalscore))
    optimal_feature = feature_list[position_index]
    #print("Optimal feature is ", optimal_feature)
    #print("position_index is ",position_index)

    machine1_position = x[position_index]*3 + y[position_index]
    #moves.append(machine1_position)
    
    return(machine1_position, max(evalscore), optimal_feature)




### the below code is for the machine which doesnt learn - makes random moves 

In [5]:

def machine2_move(game_moves):
    while(True):
        machine2_position = randint(0,8)
        if machine2_position not in game_moves:
            #game_board[machine2_position // 3, machine2_position % 3] = 2
            #moves.append(machine2_position)
            
            #clear_output()
            print("Machine 2's move")
            break
    return(machine2_position)



### Below code is for updating weights after each training game is played

In [6]:
def weight_update(X, y, game_counter,w0,w1,w2,w3,w4,w5,w6):
    print("Game counter", game_counter)
    f1 = [sublist[0] for sublist in X]
    f2 = [sublist[1] for sublist in X]
    f3 = [sublist[2] for sublist in X]
    f4 = [sublist[3] for sublist in X]
    f5 = [sublist[4] for sublist in X]
    f6 = [sublist[5] for sublist in X]
    Vestimate = [sublist[6] for sublist in X]
    Vtrain_flattened = [item for sublist in y for item in sublist]
    #print("Vtrain_flattened is",Vtrain_flattened)
    
    lr = 0.1
    print("length of f1",len(f1))
    w0_old = w0
    w1_old = w1
    w2_old = w2
    w3_old = w3
    w4_old = w4
    w5_old = w5
    w6_old = w6
    
    for i in range(0, len(f1)):
        w0_new = w0_old + lr*(Vtrain_flattened[i] - Vestimate[i])
        w1_new = w1_old + lr*(Vtrain_flattened[i] - Vestimate[i])*f1[i]
        w2_new = w2_old + lr*(Vtrain_flattened[i] - Vestimate[i])*f2[i]
        w3_new = w3_old + lr*(Vtrain_flattened[i] - Vestimate[i])*f3[i]
        w4_new = w4_old + lr*(Vtrain_flattened[i] - Vestimate[i])*f4[i]
        w5_new = w5_old + lr*(Vtrain_flattened[i] - Vestimate[i])*f5[i]
        w6_new = w6_old + lr*(Vtrain_flattened[i] - Vestimate[i])*f6[i]
        #print("Vtrain_flattened",Vtrain_flattened[i])
        w0_old = w0_new
        w1_old = w1_new
        w2_old = w2_new
        w3_old = w3_new
        w4_old = w4_new
        w5_old = w5_new
        w6_old = w6_new
       
        
        if i==(len(f1)-1):
            break

        Vestimate[i+1] = w0_new + w1_new*f1[i+1] + w2_new*f2[i+1] + w3_new*f3[i+1] + w4_new*f4[i+1] + w5_new*f5[i+1] + w6_new*f6[i+1]
    #print(w0_new,w1_new,w2_new,w3_new,w4_new,w5_new,w6_new)
    return(w0_new,w1_new,w2_new,w3_new,w4_new,w5_new,w6_new)




#### For printing the game board

In [7]:
def print_game_board(game_board):
    print_board = np.copy(game_board)
    print_board_list = print_board.ravel().tolist()
    replace_dict = {1:'X',2:'O',0:" "}
    print_board_XO = [replace_dict.get(n) for n in print_board_list]
    
    print("     |     |     ")
    print("  "+print_board_XO[0]+"  |  "+print_board_XO[1]+"  |  "+print_board_XO[2]+"  ")
    print("_____|_____|_____")
    print("     |     |     ")
    print("  "+print_board_XO[3]+"  |  "+print_board_XO[4]+"  |  "+print_board_XO[5]+"  ")
    print("_____|_____|_____")
    print("     |     |     ")
    print("  "+print_board_XO[6]+"  |  "+print_board_XO[7]+"  |  "+print_board_XO[8]+"  ")
    print("     |     |     ")

### Below code is for the whole training process

In [8]:
##List of winning moves - whenever any combination in this achieved it is game over
winning_moves = [[0,1,2],[0,3,6],[0,4,8],[1,4,7],[2,5,8],[2,4,6],[3,4,5],[6,7,8]]
positions = []
start_index = 0
game_feature = []

Vtrain = []

## Initializing weights for the learning. This can be made random also instead of a fixed 0.5
w0 = w1 = w2 = w3 = w4 = w5 = w6 = 0.5
print("intial wights",w0,w1,w2,w3,w4,w5,w6)


for m in range(0,1000):
    
    ##Initializing different lists - moves contain overall moves made by both the agents
    ## This is to prevent repetition of moves
    ## The individual agent moves are to compare with the winning moves list
    ## The board is initialized with zeros
    
    moves = []
    machine1_moves = []
    machine2_moves = []
    Vest = []
    feature_list = []
    game_feature = []
    Vtrain=[]
    game_board = np.zeros([3,3])
    print(game_board)
    
    ## This loop is for the game play - a maximum of 9 moves can be made in a game
    for i in range(0,9):
        #game_feature = []
        ## Initializing a game over flag to 0
        GO = 0
        
        ## Calling the function machine1_move for making the moves of the agent 1
        ## and receiving the move position in machine1_position variable
        ## Passing the weights as function arguments 
        machine1_position, vestimate, feature_list = machine1_move(game_board, w0, w1, w2, w3, w4, w5, w6)
        print("feature_list is", feature_list)
        print("Vestimate is ", vestimate)
        Vest.append(vestimate)
        
        ##Updating the game board with the machine1 move position
        game_board[machine1_position // 3, machine1_position % 3] = 1
        print("Machine 1's move")
        print(game_board)
        
        ## Creating a copy of game board into mc1
        ## Pushing the game board status into the positions list
        ## this will useful later when creating the dataframe of game board positions
        
        #mc1 = np.copy(game_board)
        #positions.append(mc1.ravel().tolist())
        game_feature.append(feature_list)
 
        
        ## Pushing the moves machine 1 into the moves list and the machine1_moves list
        moves.append(machine1_position)
        print("Moves array",moves)
        machine1_moves.append(machine1_position)
        machine1_counter = 0
        
        ## If more than two moves are made, then keep checking in the winning moves list
        if len(machine1_moves) > 2:
            for j in range(len(winning_moves)):
                #human_counter = 0
                ## For each set (3 positions) of winning moves, the values in the machine1_moves
                ## are checked with the winning moves set - and if there is a match of 3, the game is 
                ## declared won by machine 1
                machine1_counter = [a for a in machine1_moves if a in winning_moves[j]]
                if len(machine1_counter)==3:
                    print("Game Over")
                    print("Machine1 won")
                    GO = 1
                    break
        
        ## If game over, the GO flag will be set to 1 in the previous code block and the previous loop is exited.
        ## Now, for all the gameboard arrays in the position list (which includes moves by machine 2 as well)
        ## a 1 is added - to indicate that the game was won by agent 1.
        ## Else if the number of moves is 9 without the GO flag set to 1, then it is a tie game and hence '0' is 
        ## added to the position arrays
        if GO == 1:
            Vest.append(100)
            Vest.pop(0)
            Vtrain.append(Vest)

            break
            
        elif len(machine1_moves)+len(machine2_moves) == 9:
            print("Game Tie")
            Vest.append(0)
            Vest.pop(0)
            Vtrain.append(Vest)
            break
            
            
        ## Calling the function machine2_move for making the moves of the agent 2
        ## and receiving the move position in machine2_position variable
        
        
        machine2_position = machine2_move(moves)
        
        game_board[machine2_position // 3, machine2_position % 3] = 2
        print(game_board)
        
        mc2 = np.copy(game_board)
        #positions.append(mc2.ravel().tolist())
        
        moves.append(machine2_position)
        machine2_moves.append(machine2_position)
        machine2_counter = 0
        
        if len(machine2_moves) > 2:
            for h in range(len(winning_moves)):
                #machine_counter = 0
                machine2_counter = [b for b in machine2_moves if b in winning_moves[h]]
                if len(machine2_counter)==3:
                    print("Game Over")
                    print("Machine2 won")
                    GO = 2
                    break

        if GO == 2:
            Vest.append(-100)
            Vest.pop(0)
            Vtrain.append(Vest)
            break
    #print("GAME FEATURE",game_feature)
    w0,w1,w2,w3,w4,w5,w6 = weight_update(game_feature, Vtrain,m,w0,w1,w2,w3,w4,w5,w6)
    print("weights after update",w0,w1,w2,w3,w4,w5,w6)

intial wights 0.5 0.5 0.5 0.5 0.5 0.5 0.5
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
feature_list is [0, 0, 4, 0, 0, 0, 2.5]
Vestimate is  2.5
Machine 1's move
[[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]
Moves array [4]
Machine 2's move
[[0. 0. 0.]
 [2. 1. 0.]
 [0. 0. 0.]]
feature_list is [1, 0, 4, 1, 0, 0, 3.5]
Vestimate is  3.5
Machine 1's move
[[0. 0. 1.]
 [2. 1. 0.]
 [0. 0. 0.]]
Moves array [4, 3, 2]
Machine 2's move
[[0. 0. 1.]
 [2. 1. 0.]
 [0. 2. 0.]]
feature_list is [2, 0, 2, 2, 0, 0, 3.5]
Vestimate is  3.5
Machine 1's move
[[0. 1. 1.]
 [2. 1. 0.]
 [0. 2. 0.]]
Moves array [4, 3, 2, 7, 1]
Machine 2's move
[[0. 1. 1.]
 [2. 1. 0.]
 [0. 2. 2.]]
feature_list is [2, 1, 0, 1, 0, 0, 2.5]
Vestimate is  2.5
Machine 1's move
[[0. 1. 1.]
 [2. 1. 1.]
 [0. 2. 2.]]
Moves array [4, 3, 2, 7, 1, 8, 5]
Machine 2's move
[[0. 1. 1.]
 [2. 1. 1.]
 [2. 2. 2.]]
Game Over
Machine2 won
Game counter 0
length of f1 4
weights after update -9.7527 -20.035400000000003 -9.713700000000001 0.282 -9.821700000000002 0.5 0.5
[[0

Moves array [4]
Machine 2's move
[[0. 2. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]
feature_list is [0, 0, 4, 1, 0, 0, 23.447896945459938]
Vestimate is  23.447896945459938
Machine 1's move
[[0. 2. 0.]
 [0. 1. 0.]
 [0. 1. 0.]]
Moves array [4, 1, 7]
Machine 2's move
[[0. 2. 0.]
 [0. 1. 0.]
 [0. 1. 2.]]
feature_list is [0, 0, 3, 1, 0, 0, 20.332074425001643]
Vestimate is  20.332074425001643
Machine 1's move
[[1. 2. 0.]
 [0. 1. 0.]
 [0. 1. 2.]]
Moves array [4, 1, 7, 8, 0]
Machine 2's move
[[1. 2. 0.]
 [2. 1. 0.]
 [0. 1. 2.]]
feature_list is [0, 0, 1, 0, 0, 0, 20.263825731689522]
Vestimate is  20.263825731689522
Machine 1's move
[[1. 2. 0.]
 [2. 1. 1.]
 [0. 1. 2.]]
Moves array [4, 1, 7, 8, 0, 3, 5]
Machine 2's move
[[1. 2. 0.]
 [2. 1. 1.]
 [2. 1. 2.]]
feature_list is [0, 0, 0, 0, 0, 0, 17.148003211231227]
Vestimate is  17.148003211231227
Machine 1's move
[[1. 2. 1.]
 [2. 1. 1.]
 [2. 1. 2.]]
Moves array [4, 1, 7, 8, 0, 3, 5, 6, 2]
Game Tie
Game counter 17
length of f1 5
weights after update 15.079135312911

Machine1 won
Game counter 38
length of f1 3
weights after update 36.02007128108454 19.81221286999581 -14.470569799529972 9.80877852875625 -4.156909251340194 32.33684016282785 0.5
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
feature_list is [0, 0, 4, 0, 0, 0, 75.25518539610954]
Vestimate is  75.25518539610954
Machine 1's move
[[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]
Moves array [4]
Machine 2's move
[[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 2.]]
feature_list is [1, 0, 3, 1, 0, 0, 81.10171048600891]
Vestimate is  81.10171048600891
Machine 1's move
[[0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 2.]]
Moves array [4, 8, 2]
Machine 2's move
[[0. 2. 1.]
 [0. 1. 0.]
 [0. 0. 2.]]
feature_list is [0, 0, 2, 0, 1, 0, 87.9744685014249]
Vestimate is  87.9744685014249
Machine 1's move
[[0. 2. 1.]
 [0. 1. 0.]
 [1. 0. 2.]]
Moves array [4, 8, 2, 1, 6]
Game Over
Machine1 won
Game counter 39
length of f1 3
weights after update 37.25925794379745 19.73944040985049 -14.470569799529972 13.38368441201662 -4.229681711485514 33.06414677669614 0.5
[[

weights after update 47.415862051631365 3.3884058808483726 -33.75911623111807 -6.796868984487789 0.34544210568947875 35.38749626853316 0.5
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
feature_list is [0, 0, 2, 0, 0, 0, 33.82212408265579]
Vestimate is  33.82212408265579
Machine 1's move
[[0. 1. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Moves array [1]
Machine 2's move
[[0. 1. 0.]
 [0. 0. 0.]
 [0. 0. 2.]]
feature_list is [1, 0, 1, 2, 0, 0, 44.69828315937091]
Vestimate is  44.69828315937091
Machine 1's move
[[0. 1. 0.]
 [0. 0. 0.]
 [0. 1. 2.]]
Moves array [1, 8, 7]
Machine 2's move
[[0. 1. 0.]
 [0. 0. 0.]
 [2. 1. 2.]]
feature_list is [2, 0, 0, 2, 0, 0, 54.88355802470707]
Vestimate is  54.88355802470707
Machine 1's move
[[1. 1. 0.]
 [0. 0. 0.]
 [2. 1. 2.]]
Moves array [1, 8, 7, 6, 0]
Machine 2's move
[[1. 1. 0.]
 [2. 0. 0.]
 [2. 1. 2.]]
feature_list is [1, 0, 0, 1, 1, 0, 86.53720630670239]
Vestimate is  86.53720630670239
Machine 1's move
[[1. 1. 1.]
 [2. 0. 0.]
 [2. 1. 2.]]
Moves array [1, 8, 7, 6, 0, 3, 2]
Ga

Moves array [4, 3, 2, 7, 6]
Game Over
Machine1 won
Game counter 76
length of f1 3
weights after update 64.13497067473958 11.169236717517801 -29.49976362153226 4.594583054106057 -3.7460038781459115 21.377969432942518 0.5
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
feature_list is [0, 0, 4, 0, 0, 0, 82.5133028911638]
Vestimate is  82.5133028911638
Machine 1's move
[[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]
Moves array [4]
Machine 2's move
[[0. 0. 0.]
 [2. 1. 0.]
 [0. 0. 0.]]
feature_list is [1, 0, 4, 1, 0, 0, 89.9365357305357]
Vestimate is  89.9365357305357
Machine 1's move
[[0. 0. 1.]
 [2. 1. 0.]
 [0. 0. 0.]]
Moves array [4, 3, 2]
Machine 2's move
[[0. 0. 1.]
 [2. 1. 0.]
 [0. 0. 2.]]
feature_list is [0, 0, 2, 0, 1, 0, 94.7021062158942]
Vestimate is  94.7021062158942
Machine 1's move
[[0. 0. 1.]
 [2. 1. 0.]
 [1. 0. 2.]]
Moves array [4, 3, 2, 8, 6]
Game Over
Machine1 won
Game counter 77
length of f1 3
weights after update 64.66045312812815 10.38384418336043 -29.49976362153226 5.559409460442811 -4.5313

[[1. 1. 1.]
 [2. 1. 2.]
 [2. 1. 2.]]
Moves array [4, 6, 0, 8, 7, 3, 2, 5, 1]
Game Over
Machine1 won
Game counter 99
length of f1 5
weights after update 64.18173557684496 11.225290915283166 -24.898372351854583 6.794946699595314 -4.6743080109183435 18.84831964998962 0.5
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
feature_list is [0, 0, 4, 0, 0, 0, 91.36152237522622]
Vestimate is  91.36152237522622
Machine 1's move
[[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]
Moves array [4]
Machine 2's move
[[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 2.]]
feature_list is [1, 0, 3, 1, 0, 0, 91.11755857999573]
Vestimate is  91.11755857999573
Machine 1's move
[[0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 2.]]
Moves array [4, 8, 2]
Machine 2's move
[[0. 2. 1.]
 [0. 1. 0.]
 [0. 0. 2.]]
feature_list is [0, 0, 2, 0, 1, 0, 96.6199486260252]
Vestimate is  96.6199486260252
Machine 1's move
[[0. 2. 1.]
 [0. 1. 0.]
 [1. 0. 2.]]
Moves array [4, 8, 2, 1, 6]
Game Over
Machine1 won
Game counter 100
length of f1 3
weights after update 64.691887365685 11.8072452

Vestimate is  89.3428735876046
Machine 1's move
[[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]
Moves array [4]
Machine 2's move
[[0. 0. 0.]
 [0. 1. 0.]
 [0. 2. 0.]]
feature_list is [1, 0, 4, 1, 0, 0, 96.60913325602483]
Vestimate is  96.60913325602483
Machine 1's move
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 2. 0.]]
Moves array [4, 7, 0]
Machine 2's move
[[1. 0. 0.]
 [0. 1. 2.]
 [0. 2. 0.]]
feature_list is [0, 0, 3, 0, 1, 0, 101.28721914088996]
Vestimate is  101.28721914088996
Machine 1's move
[[1. 0. 0.]
 [0. 1. 2.]
 [0. 2. 1.]]
Moves array [4, 7, 0, 5, 8]
Game Over
Machine1 won
Game counter 122
length of f1 3
weights after update 64.99708550733308 10.157186183465392 -24.898372351854583 5.66708005957107 -4.42583762533502 17.926030864658482 0.5
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
feature_list is [0, 0, 4, 0, 0, 0, 87.66540574561736]
Vestimate is  87.66540574561736
Machine 1's move
[[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]
Moves array [4]
Machine 2's move
[[0. 2. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]
feature_list is [1, 0

feature_list is [1, 0, 0, 0, 1, 0, 95.566482716549]
Vestimate is  95.566482716549
Machine 1's move
[[1. 2. 2.]
 [0. 1. 1.]
 [2. 0. 1.]]
Moves array [4, 6, 0, 1, 5, 2, 8]
Game Over
Machine1 won
Game counter 143
length of f1 4
weights after update 69.79324130801729 12.39549993911565 -24.898372351854583 4.820658097610231 -2.0163992231247523 14.487332072887483 0.5
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
feature_list is [0, 0, 4, 0, 0, 0, 89.07587369845821]
Vestimate is  89.07587369845821
Machine 1's move
[[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]
Moves array [4]
Machine 2's move
[[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 2.]]
feature_list is [1, 0, 3, 1, 0, 0, 94.63431631683888]
Vestimate is  94.63431631683888
Machine 1's move
[[0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 2.]]
Moves array [4, 8, 2]
Machine 2's move
[[0. 2. 1.]
 [0. 1. 0.]
 [0. 0. 2.]]
feature_list is [2, 0, 1, 1, 0, 0, 97.38850006073407]
Vestimate is  97.38850006073407
Machine 1's move
[[0. 2. 1.]
 [1. 1. 0.]
 [0. 0. 2.]]
Moves array [4, 8, 2, 1, 3]
Machin

Machine 1's move
[[2. 0. 1.]
 [0. 1. 2.]
 [1. 0. 0.]]
Moves array [4, 5, 2, 0, 6]
Game Over
Machine1 won
Game counter 165
length of f1 3
weights after update 76.79043163469638 7.046385556076466 -24.898372351854583 4.535840200205592 -3.5870204717330303 14.390992541912698 0.5
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
feature_list is [0, 0, 4, 0, 0, 0, 94.93379243551874]
Vestimate is  94.93379243551874
Machine 1's move
[[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]
Moves array [4]
Machine 2's move
[[0. 2. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]
feature_list is [1, 0, 4, 1, 0, 0, 98.39315751986219]
Vestimate is  98.39315751986219
Machine 1's move
[[0. 2. 0.]
 [0. 1. 0.]
 [1. 0. 0.]]
Moves array [4, 1, 6]
Machine 2's move
[[0. 2. 0.]
 [2. 1. 0.]
 [1. 0. 0.]]
feature_list is [0, 0, 3, 0, 1, 0, 104.78894477722585]
Vestimate is  104.78894477722585
Machine 1's move
[[0. 2. 1.]
 [2. 1. 0.]
 [1. 0. 0.]]
Moves array [4, 1, 6, 3, 2]
Game Over
Machine1 won
Game counter 166
length of f1 3
weights after update 76.1923102060241

weights after update 80.86118713373568 7.441653889444376 -24.898372351854583 4.316489216658243 -2.7989482005469113 11.14340988748294 0.5
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
feature_list is [0, 0, 4, 0, 0, 0, 98.12714400036866]
Vestimate is  98.12714400036866
Machine 1's move
[[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]
Moves array [4]
Machine 2's move
[[0. 0. 0.]
 [0. 1. 2.]
 [0. 0. 0.]]
feature_list is [1, 0, 4, 1, 0, 0, 102.76984968926612]
Vestimate is  102.76984968926612
Machine 1's move
[[1. 0. 0.]
 [0. 1. 2.]
 [0. 0. 0.]]
Moves array [4, 5, 0]
Machine 2's move
[[1. 0. 0.]
 [0. 1. 2.]
 [0. 0. 2.]]
feature_list is [2, 0, 2, 1, 0, 0, 101.578525145394]
Vestimate is  101.578525145394
Machine 1's move
[[1. 0. 1.]
 [0. 1. 2.]
 [0. 0. 2.]]
Moves array [4, 5, 0, 8, 2]
Machine 2's move
[[1. 2. 1.]
 [0. 1. 2.]
 [0. 0. 2.]]
feature_list is [1, 0, 0, 0, 1, 0, 99.44625091066301]
Vestimate is  99.44625091066301
Machine 1's move
[[1. 2. 1.]
 [0. 1. 2.]
 [1. 0. 2.]]
Moves array [4, 5, 0, 8, 2, 1, 6]
Game

Moves array [1, 3, 0]
Machine 2's move
[[1. 1. 0.]
 [2. 0. 0.]
 [0. 2. 0.]]
feature_list is [2, 0, 1, 1, 0, 0, 90.64793492892312]
Vestimate is  90.64793492892312
Machine 1's move
[[1. 1. 0.]
 [2. 1. 0.]
 [0. 2. 0.]]
Moves array [1, 3, 0, 7, 4]
Machine 2's move
[[1. 1. 0.]
 [2. 1. 0.]
 [0. 2. 2.]]
feature_list is [2, 0, 0, 1, 0, 0, 92.64882059659004]
Vestimate is  92.64882059659004
Machine 1's move
[[1. 1. 0.]
 [2. 1. 0.]
 [1. 2. 2.]]
Moves array [1, 3, 0, 7, 4, 8, 6]
Machine 2's move
[[1. 1. 2.]
 [2. 1. 0.]
 [1. 2. 2.]]
feature_list is [0, 0, 0, 0, 0, 0, 84.43668638929303]
Vestimate is  84.43668638929303
Machine 1's move
[[1. 1. 2.]
 [2. 1. 1.]
 [1. 2. 2.]]
Moves array [1, 3, 0, 7, 4, 8, 6, 2, 5]
Game Tie
Game counter 204
length of f1 5
weights after update 75.73022747265898 3.0403502778870664 -17.864376239270722 -0.5068411201962968 -2.0504503196735486 7.760141438359187 0.5
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
feature_list is [0, 0, 2, 0, 0, 0, 74.71654523226638]
Vestimate is  74.71654

Moves array [4]
Machine 2's move
[[2. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]
feature_list is [1, 0, 3, 1, 0, 0, 95.36159795113784]
Vestimate is  95.36159795113784
Machine 1's move
[[2. 0. 1.]
 [0. 1. 0.]
 [0. 0. 0.]]
Moves array [4, 0, 2]
Machine 2's move
[[2. 0. 1.]
 [0. 1. 0.]
 [0. 0. 2.]]
feature_list is [0, 0, 2, 0, 1, 0, 98.14675052388289]
Vestimate is  98.14675052388289
Machine 1's move
[[2. 0. 1.]
 [0. 1. 0.]
 [1. 0. 2.]]
Moves array [4, 0, 2, 8, 6]
Game Over
Machine1 won
Game counter 226
length of f1 3
weights after update 85.1828126335872 5.727090029774488 -17.864376239270722 3.129234657445386 -1.9696787117069816 8.592385044889205 0.5
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
feature_list is [0, 0, 4, 0, 0, 0, 97.69975126336875]
Vestimate is  97.69975126336875
Machine 1's move
[[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]
Moves array [4]
Machine 2's move
[[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 2.]]
feature_list is [1, 0, 3, 1, 0, 0, 98.32792792399087]
Vestimate is  98.32792792399087
Machine 1's move
[[0. 

Machine 2's move
[[2. 0. 1.]
 [0. 1. 0.]
 [0. 0. 2.]]
feature_list is [0, 0, 2, 0, 1, 0, 97.18689826319834]
Vestimate is  97.18689826319834
Machine 1's move
[[2. 0. 1.]
 [0. 1. 0.]
 [1. 0. 2.]]
Moves array [4, 0, 2, 8, 6]
Game Over
Machine1 won
Game counter 248
length of f1 3
weights after update 86.64800882546774 4.290004515040397 -17.864376239270722 3.0099709146059417 -1.1593841351683218 6.314769792741373 0.5
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
feature_list is [0, 0, 4, 0, 0, 0, 98.6878924838915]
Vestimate is  98.6878924838915
Machine 1's move
[[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]
Moves array [4]
Machine 2's move
[[0. 0. 0.]
 [0. 1. 2.]
 [0. 0. 0.]]
feature_list is [1, 0, 4, 1, 0, 0, 101.81851286376357]
Vestimate is  101.81851286376357
Machine 1's move
[[1. 0. 0.]
 [0. 1. 2.]
 [0. 0. 0.]]
Moves array [4, 5, 0]
Machine 2's move
[[1. 0. 0.]
 [0. 1. 2.]
 [0. 0. 2.]]
feature_list is [2, 0, 2, 1, 0, 0, 100.0885755495921]
Vestimate is  100.0885755495921
Machine 1's move
[[1. 0. 1.]
 [0. 1.

Machine 2's move
[[1. 0. 0.]
 [2. 1. 0.]
 [2. 0. 0.]]
feature_list is [0, 0, 3, 0, 1, 0, 101.61153314216158]
Vestimate is  101.61153314216158
Machine 1's move
[[1. 0. 0.]
 [2. 1. 0.]
 [2. 0. 1.]]
Moves array [4, 6, 0, 3, 8]
Game Over
Machine1 won
Game counter 268
length of f1 3
weights after update 89.75081265621324 4.078179854953806 -17.864376239270722 1.5664296522302577 -1.0226225082480414 5.09562564731406 0.5
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
feature_list is [0, 0, 4, 0, 0, 0, 96.01653126513428]
Vestimate is  96.01653126513428
Machine 1's move
[[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]
Moves array [4]
Machine 2's move
[[0. 0. 0.]
 [0. 1. 2.]
 [0. 0. 0.]]
feature_list is [1, 0, 4, 1, 0, 0, 99.07208861184003]
Vestimate is  99.07208861184003
Machine 1's move
[[1. 0. 0.]
 [0. 1. 2.]
 [0. 0. 0.]]
Moves array [4, 5, 0]
Machine 2's move
[[1. 0. 0.]
 [0. 1. 2.]
 [0. 0. 2.]]
feature_list is [2, 0, 2, 1, 0, 0, 100.01740916233331]
Vestimate is  100.01740916233331
Machine 1's move
[[1. 0. 1.]
 [0.

feature_list is [2, 0, 0, 0, 0, 0, 96.5334862276558]
Vestimate is  96.5334862276558
Machine 1's move
[[1. 0. 1.]
 [0. 1. 2.]
 [2. 1. 2.]]
Moves array [4, 8, 0, 5, 2, 6, 7]
Machine 2's move
[[1. 0. 1.]
 [2. 1. 2.]
 [2. 1. 2.]]
feature_list is [0, 0, 0, 0, 1, 0, 96.35465939161712]
Vestimate is  96.35465939161712
Machine 1's move
[[1. 1. 1.]
 [2. 1. 2.]
 [2. 1. 2.]]
Moves array [4, 8, 0, 5, 2, 6, 7, 3, 1]
Game Over
Machine1 won
Game counter 287
length of f1 5
weights after update 92.34987385710798 2.0742140443870443 -17.864376239270722 0.5244480276580622 -0.40367491255295823 4.635408481874406 0.5
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
feature_list is [0, 0, 4, 0, 0, 0, 94.44766596774024]
Vestimate is  94.44766596774024
Machine 1's move
[[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]
Moves array [4]
Machine 2's move
[[0. 0. 0.]
 [0. 1. 0.]
 [0. 2. 0.]]
feature_list is [1, 0, 4, 1, 0, 0, 96.11820509957433]
Vestimate is  96.11820509957433
Machine 1's move
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 2. 0.]]
Moves array 

Vestimate is  74.58788931744382
Machine 1's move
[[0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 2.]]
Moves array [4, 8, 2]
Machine 2's move
[[0. 0. 1.]
 [2. 1. 0.]
 [0. 0. 2.]]
feature_list is [3, 0, 0, 2, 0, 0, 81.96429344717437]
Vestimate is  81.96429344717437
Machine 1's move
[[0. 1. 1.]
 [2. 1. 0.]
 [0. 0. 2.]]
Moves array [4, 8, 2, 3, 1]
Machine 2's move
[[2. 1. 1.]
 [2. 1. 0.]
 [0. 0. 2.]]
feature_list is [1, 0, 0, 0, 1, 0, 86.12827074204793]
Vestimate is  86.12827074204793
Machine 1's move
[[2. 1. 1.]
 [2. 1. 0.]
 [1. 0. 2.]]
Moves array [4, 8, 2, 3, 1, 0, 6]
Game Over
Machine1 won
Game counter 306
length of f1 4
weights after update 72.3178855360887 6.846679724844835 -17.864376239270722 2.5244925766960664 -0.5535565488066805 12.335398923189093 0.5
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
feature_list is [0, 0, 4, 0, 0, 0, 82.41585584287296]
Vestimate is  82.41585584287296
Machine 1's move
[[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]
Moves array [4]
Machine 2's move
[[0. 0. 0.]
 [0. 1. 2.]
 [0. 0. 0.]]
fe

feature_list is [0, 0, 4, 0, 0, 0, 91.42467736810346]
Vestimate is  91.42467736810346
Machine 1's move
[[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]
Moves array [4]
Machine 2's move
[[2. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]
feature_list is [1, 0, 3, 1, 0, 0, 91.04459188678375]
Vestimate is  91.04459188678375
Machine 1's move
[[2. 0. 1.]
 [0. 1. 0.]
 [0. 0. 0.]]
Moves array [4, 0, 2]
Machine 2's move
[[2. 0. 1.]
 [0. 1. 0.]
 [0. 2. 0.]]
feature_list is [0, 0, 2, 0, 1, 0, 96.15940327429156]
Vestimate is  96.15940327429156
Machine 1's move
[[2. 0. 1.]
 [0. 1. 0.]
 [1. 2. 0.]]
Moves array [4, 0, 2, 7, 6]
Game Over
Machine1 won
Game counter 327
length of f1 3
weights after update 79.25458976368895 6.072722205239209 -17.864376239270722 4.761581665759317 -2.151369659522016 11.119675744936515 0.5
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
feature_list is [0, 0, 4, 0, 0, 0, 98.30091642672622]
Vestimate is  98.30091642672622
Machine 1's move
[[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]
Moves array [4]
Machine 2's move
[[0.

Machine 2's move
[[1. 2. 0.]
 [0. 1. 0.]
 [0. 2. 0.]]
feature_list is [0, 0, 4, 0, 1, 0, 108.70193894843138]
Vestimate is  108.70193894843138
Machine 1's move
[[1. 2. 0.]
 [0. 1. 0.]
 [0. 2. 1.]]
Moves array [4, 7, 0, 1, 8]
Game Over
Machine1 won
Game counter 347
length of f1 3
weights after update 75.03957827634441 6.524771407139664 -17.864376239270722 0.7612070281731844 -2.1529091032524397 9.919323260280777 0.5
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
feature_list is [0, 0, 4, 0, 0, 0, 78.08440638903716]
Vestimate is  78.08440638903716
Machine 1's move
[[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]
Moves array [4]
Machine 2's move
[[0. 0. 0.]
 [0. 1. 0.]
 [2. 0. 0.]]
feature_list is [1, 0, 3, 1, 0, 0, 81.6950616647512]
Vestimate is  81.6950616647512
Machine 1's move
[[1. 0. 0.]
 [0. 1. 0.]
 [2. 0. 0.]]
Moves array [4, 6, 0]
Machine 2's move
[[1. 0. 2.]
 [0. 1. 0.]
 [2. 0. 0.]]
feature_list is [2, 0, 1, 1, 0, 0, 86.69741901554448]
Vestimate is  86.69741901554448
Machine 1's move
[[1. 0. 2.]
 [0. 1.

Machine 1's move
[[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]
Moves array [4]
Machine 2's move
[[0. 0. 0.]
 [0. 1. 2.]
 [0. 0. 0.]]
feature_list is [1, 0, 4, 1, 0, 0, 97.36302013617943]
Vestimate is  97.36302013617943
Machine 1's move
[[1. 0. 0.]
 [0. 1. 2.]
 [0. 0. 0.]]
Moves array [4, 5, 0]
Machine 2's move
[[1. 0. 0.]
 [2. 1. 2.]
 [0. 0. 0.]]
feature_list is [0, 0, 4, 0, 1, 0, 103.71341309121473]
Vestimate is  103.71341309121473
Machine 1's move
[[1. 0. 0.]
 [2. 1. 2.]
 [0. 0. 1.]]
Moves array [4, 5, 0, 3, 8]
Game Over
Machine1 won
Game counter 370
length of f1 3
weights after update 79.63607800950354 6.529853425237665 -15.18495182386259 0.813183866981591 -2.8709827411346716 8.9495732559432 0.5
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
feature_list is [0, 0, 4, 0, 0, 0, 82.88881347742989]
Vestimate is  82.88881347742989
Machine 1's move
[[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]
Moves array [4]
Machine 2's move
[[0. 0. 0.]
 [0. 1. 0.]
 [0. 2. 0.]]
feature_list is [1, 0, 3, 0, 0, 0, 88.60548303568596]


weights after update 84.12735928727582 5.979195775793596 -15.18495182386259 3.8395064569896826 -2.035109667037961 9.295524004419029 0.5
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
feature_list is [0, 0, 4, 0, 0, 0, 99.48538511523455]
Vestimate is  99.48538511523455
Machine 1's move
[[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]
Moves array [4]
Machine 2's move
[[2. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]
feature_list is [1, 0, 3, 1, 0, 0, 99.58996476700051]
Vestimate is  99.58996476700051
Machine 1's move
[[2. 0. 1.]
 [0. 1. 0.]
 [0. 0. 0.]]
Moves array [4, 0, 2]
Machine 2's move
[[2. 0. 1.]
 [0. 1. 0.]
 [0. 0. 2.]]
feature_list is [0, 0, 2, 0, 1, 0, 101.10189620567422]
Vestimate is  101.10189620567422
Machine 1's move
[[2. 0. 1.]
 [0. 1. 0.]
 [1. 0. 2.]]
Moves array [4, 0, 2, 8, 6]
Game Over
Machine1 won
Game counter 391
length of f1 3
weights after update 84.05949479996741 6.116793564931392 -15.18495182386259 3.86229120186382 -1.8975118779001654 9.079603762796213 0.5
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
feat

[[2. 0. 1.]
 [2. 1. 0.]
 [0. 0. 0.]]
feature_list is [0, 0, 3, 0, 1, 0, 100.90512527511615]
Vestimate is  100.90512527511615
Machine 1's move
[[2. 0. 1.]
 [2. 1. 0.]
 [1. 0. 0.]]
Moves array [4, 0, 2, 3, 6]
Game Over
Machine1 won
Game counter 411
length of f1 3
weights after update 86.08897355150216 4.843137436672738 -15.18495182386259 2.262648652461142 -1.1532051682022162 6.617961904612821 0.5
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
feature_list is [0, 0, 4, 0, 0, 0, 95.13956816134673]
Vestimate is  95.13956816134673
Machine 1's move
[[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]
Moves array [4]
Machine 2's move
[[0. 0. 2.]
 [0. 1. 0.]
 [0. 0. 0.]]
feature_list is [1, 0, 3, 1, 0, 0, 96.5668517773561]
Vestimate is  96.5668517773561
Machine 1's move
[[1. 0. 2.]
 [0. 1. 0.]
 [0. 0. 0.]]
Moves array [4, 2, 0]
Machine 2's move
[[1. 0. 2.]
 [2. 1. 0.]
 [0. 0. 0.]]
feature_list is [0, 0, 2, 0, 1, 0, 97.23223276103728]
Vestimate is  97.23223276103728
Machine 1's move
[[1. 0. 2.]
 [2. 1. 0.]
 [0. 0. 1.]]
M

Machine 1's move
[[0. 2. 0.]
 [0. 1. 0.]
 [1. 0. 0.]]
Moves array [4, 1, 6]
Machine 2's move
[[0. 2. 2.]
 [0. 1. 0.]
 [1. 0. 0.]]
feature_list is [2, 0, 2, 1, 0, 0, 100.82465519826117]
Vestimate is  100.82465519826117
Machine 1's move
[[1. 2. 2.]
 [0. 1. 0.]
 [1. 0. 0.]]
Moves array [4, 1, 6, 2, 0]
Machine 2's move
[[1. 2. 2.]
 [0. 1. 0.]
 [1. 0. 2.]]
feature_list is [2, 0, 0, 0, 0, 0, 95.33276410699983]
Vestimate is  95.33276410699983
Machine 1's move
[[1. 2. 2.]
 [0. 1. 1.]
 [1. 0. 2.]]
Moves array [4, 1, 6, 2, 0, 8, 5]
Machine 2's move
[[1. 2. 2.]
 [2. 1. 1.]
 [1. 0. 2.]]
feature_list is [0, 0, 0, 0, 0, 0, 82.33756861666652]
Vestimate is  82.33756861666652
Machine 1's move
[[1. 2. 2.]
 [2. 1. 1.]
 [1. 1. 2.]]
Moves array [4, 1, 6, 2, 0, 8, 5, 3, 7]
Game Tie
Game counter 432
length of f1 5
weights after update 72.79552707972006 3.539491818256394 -15.18495182386259 2.2084456484857995 -2.672363801264298 9.14792036934472 0.5
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
feature_list is [0, 0, 4,

weights after update 70.25997129675011 8.190756203135638 -15.18495182386259 2.4116707880866612 -1.1473546973744961 17.446332872982623 0.5
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
feature_list is [0, 0, 4, 0, 0, 0, 79.90665444909675]
Vestimate is  79.90665444909675
Machine 1's move
[[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]
Moves array [4]
Machine 2's move
[[0. 2. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]
feature_list is [1, 0, 4, 1, 0, 0, 86.95005595485789]
Vestimate is  86.95005595485789
Machine 1's move
[[0. 2. 0.]
 [0. 1. 0.]
 [1. 0. 0.]]
Moves array [4, 1, 6]
Machine 2's move
[[0. 2. 0.]
 [2. 1. 0.]
 [1. 0. 0.]]
feature_list is [3, 0, 1, 1, 0, 0, 96.0965559968692]
Vestimate is  96.0965559968692
Machine 1's move
[[0. 2. 0.]
 [2. 1. 0.]
 [1. 0. 1.]]
Moves array [4, 1, 6, 3, 8]
Machine 2's move
[[0. 2. 0.]
 [2. 1. 0.]
 [1. 2. 1.]]
feature_list is [2, 0, 0, 0, 1, 0, 104.087816576004]
Vestimate is  104.087816576004
Machine 1's move
[[0. 2. 1.]
 [2. 1. 0.]
 [1. 2. 1.]]
Moves array [4, 1, 6, 3, 8, 7, 2]
Game Ov

feature_list is [2, 0, 2, 1, 0, 0, 84.53636738258356]
Vestimate is  84.53636738258356
Machine 1's move
[[0. 0. 1.]
 [0. 1. 0.]
 [2. 2. 1.]]
Moves array [4, 6, 2, 7, 8]
Machine 2's move
[[0. 0. 1.]
 [2. 1. 0.]
 [2. 2. 1.]]
feature_list is [2, 0, 0, 0, 1, 0, 91.54097814268012]
Vestimate is  91.54097814268012
Machine 1's move
[[1. 0. 1.]
 [2. 1. 0.]
 [2. 2. 1.]]
Moves array [4, 6, 2, 7, 8, 3, 0]
Game Over
Machine1 won
Game counter 472
length of f1 4
weights after update 61.635807403275734 9.401652156886195 -15.18495182386259 8.892915825243605 -3.9612017430278468 17.382677497489983 0.5
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
feature_list is [0, 0, 4, 0, 0, 0, 97.20747070425016]
Vestimate is  97.20747070425016
Machine 1's move
[[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]
Moves array [4]
Machine 2's move
[[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 2.]]
feature_list is [0, 0, 5, 2, 0, 0, 98.17798304343806]
Vestimate is  98.17798304343806
Machine 1's move
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 2.]]
Moves array [4, 8, 0]
Ma

Vestimate is  74.40329613496168
Machine 1's move
[[1. 0. 0.]
 [0. 1. 2.]
 [0. 0. 0.]]
Moves array [4, 5, 0]
Machine 2's move
[[1. 0. 0.]
 [0. 1. 2.]
 [0. 2. 0.]]
feature_list is [0, 0, 3, 0, 1, 0, 82.32212306989139]
Vestimate is  82.32212306989139
Machine 1's move
[[1. 0. 0.]
 [0. 1. 2.]
 [0. 2. 1.]]
Moves array [4, 5, 0, 7, 8]
Game Over
Machine1 won
Game counter 492
length of f1 3
weights after update 52.61163293589493 8.699441878029841 -15.18495182386259 10.21858079657721 -4.508598961526577 17.830425555519312 0.5
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
feature_list is [0, 0, 4, 0, 0, 0, 93.48595612220377]
Vestimate is  93.48595612220377
Machine 1's move
[[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]
Moves array [4]
Machine 2's move
[[0. 0. 0.]
 [0. 1. 0.]
 [2. 0. 0.]]
feature_list is [0, 0, 5, 2, 0, 0, 94.68733899572783]
Vestimate is  94.68733899572783
Machine 1's move
[[0. 0. 1.]
 [0. 1. 0.]
 [2. 0. 0.]]
Moves array [4, 6, 2]
Machine 2's move
[[0. 0. 1.]
 [0. 1. 0.]
 [2. 2. 0.]]
feature_list is 

Moves array [4, 8, 2, 1, 6]
Game Over
Machine1 won
Game counter 513
length of f1 3
weights after update 64.52452250255784 11.214119350415025 -15.18495182386259 8.419241844669477 -5.431585521310419 19.142718951810423 0.5
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
feature_list is [0, 0, 4, 0, 0, 0, 98.20148988123574]
Vestimate is  98.20148988123574
Machine 1's move
[[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]
Moves array [4]
Machine 2's move
[[0. 0. 0.]
 [0. 1. 2.]
 [0. 0. 0.]]
feature_list is [1, 0, 4, 1, 0, 0, 103.98402371034037]
Vestimate is  103.98402371034037
Machine 1's move
[[1. 0. 0.]
 [0. 1. 2.]
 [0. 0. 0.]]
Moves array [4, 5, 0]
Machine 2's move
[[1. 2. 0.]
 [0. 1. 2.]
 [0. 0. 0.]]
feature_list is [0, 0, 3, 0, 1, 0, 108.9249669883767]
Vestimate is  108.9249669883767
Machine 1's move
[[1. 2. 0.]
 [0. 1. 2.]
 [0. 0. 1.]]
Moves array [4, 5, 0, 1, 8]
Game Over
Machine1 won
Game counter 514
length of f1 3
weights after update 63.60523071579028 10.725182927270875 -15.18495182386259 5.7506834441330

feature_list is [1, 0, 3, 1, 0, 0, 87.28362096167758]
Vestimate is  87.28362096167758
Machine 1's move
[[1. 0. 0.]
 [0. 1. 0.]
 [2. 0. 0.]]
Moves array [4, 6, 0]
Machine 2's move
[[1. 0. 0.]
 [0. 1. 0.]
 [2. 0. 2.]]
feature_list is [1, 0, 2, 1, 0, 0, 83.6253637377686]
Vestimate is  83.6253637377686
Machine 1's move
[[1. 0. 0.]
 [0. 1. 0.]
 [2. 1. 2.]]
Moves array [4, 6, 0, 8, 7]
Machine 2's move
[[1. 0. 2.]
 [0. 1. 0.]
 [2. 1. 2.]]
feature_list is [2, 0, 0, 0, 0, 0, 89.16089266614225]
Vestimate is  89.16089266614225
Machine 1's move
[[1. 0. 2.]
 [0. 1. 1.]
 [2. 1. 2.]]
Moves array [4, 6, 0, 8, 7, 2, 5]
Machine 2's move
[[1. 2. 2.]
 [0. 1. 1.]
 [2. 1. 2.]]
feature_list is [0, 0, 0, 0, 1, 0, 89.49255088817522]
Vestimate is  89.49255088817522
Machine 1's move
[[1. 2. 2.]
 [1. 1. 1.]
 [2. 1. 2.]]
Moves array [4, 6, 0, 8, 7, 2, 5, 1, 3]
Game Over
Machine1 won
Game counter 533
length of f1 5
weights after update 68.87227085868751 10.840525916973364 -30.724585190300964 4.663620032490705 -1.98

feature_list is [0, 0, 3, 0, 1, 0, 103.70128091831796]
Vestimate is  103.70128091831796
Machine 1's move
[[0. 0. 1.]
 [2. 1. 0.]
 [1. 2. 0.]]
Moves array [4, 3, 2, 7, 6]
Game Over
Machine1 won
Game counter 553
length of f1 3
weights after update 72.252464992481 9.17987434385232 -26.681397368490146 3.8887678514427093 -4.758593223850547 15.322976984346035 0.5
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
feature_list is [0, 0, 4, 0, 0, 0, 87.80753639825183]
Vestimate is  87.80753639825183
Machine 1's move
[[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]
Moves array [4]
Machine 2's move
[[0. 0. 0.]
 [2. 1. 0.]
 [0. 0. 0.]]
feature_list is [1, 0, 3, 0, 0, 0, 93.09864289066144]
Vestimate is  93.09864289066144
Machine 1's move
[[1. 0. 0.]
 [2. 1. 0.]
 [0. 0. 0.]]
Moves array [4, 3, 0]
Machine 2's move
[[1. 0. 0.]
 [2. 1. 0.]
 [0. 0. 2.]]
feature_list is [2, 0, 1, 1, 0, 0, 89.74238830777779]
Vestimate is  89.74238830777779
Machine 1's move
[[1. 0. 1.]
 [2. 1. 0.]
 [0. 0. 2.]]
Moves array [4, 3, 0, 8, 2]
Machine 2

feature_list is [0, 0, 4, 0, 0, 0, 96.30452997701943]
Vestimate is  96.30452997701943
Machine 1's move
[[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]
Moves array [4]
Machine 2's move
[[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 2.]]
feature_list is [1, 0, 3, 1, 0, 0, 97.88866457223445]
Vestimate is  97.88866457223445
Machine 1's move
[[0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 2.]]
Moves array [4, 8, 2]
Machine 2's move
[[0. 0. 1.]
 [0. 1. 0.]
 [0. 2. 2.]]
feature_list is [0, 0, 3, 0, 1, 0, 104.11748257070026]
Vestimate is  104.11748257070026
Machine 1's move
[[0. 0. 1.]
 [0. 1. 0.]
 [1. 2. 2.]]
Moves array [4, 8, 2, 7, 6]
Game Over
Machine1 won
Game counter 574
length of f1 3
weights after update 76.16825528464429 9.457285419260044 -26.681397368490146 3.6998471741042405 -2.1200116197456036 11.69757313612638 0.5
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
feature_list is [0, 0, 4, 0, 0, 0, 90.96764398106126]
Vestimate is  90.96764398106126
Machine 1's move
[[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]
Moves array [4]
Machine 2's move
[

feature_list is [1, 0, 4, 1, 0, 0, 97.28936023910337]
Vestimate is  97.28936023910337
Machine 1's move
[[0. 0. 1.]
 [2. 1. 0.]
 [0. 0. 0.]]
Moves array [4, 3, 2]
Machine 2's move
[[0. 2. 1.]
 [2. 1. 0.]
 [0. 0. 0.]]
feature_list is [3, 0, 1, 1, 0, 0, 101.68635316338872]
Vestimate is  101.68635316338872
Machine 1's move
[[0. 2. 1.]
 [2. 1. 0.]
 [0. 0. 1.]]
Moves array [4, 3, 2, 1, 8]
Machine 2's move
[[2. 2. 1.]
 [2. 1. 0.]
 [0. 0. 1.]]
feature_list is [2, 0, 0, 0, 1, 0, 103.39105066496815]
Vestimate is  103.39105066496815
Machine 1's move
[[2. 2. 1.]
 [2. 1. 0.]
 [1. 0. 1.]]
Moves array [4, 3, 2, 1, 8, 0, 6]
Game Over
Machine1 won
Game counter 595
length of f1 4
weights after update 80.57902848912371 6.071437817917656 -22.577193249807245 3.5449334301001083 -1.6498182641076045 9.156006265647735 0.5
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
feature_list is [0, 0, 4, 0, 0, 0, 94.75876220952415]
Vestimate is  94.75876220952415
Machine 1's move
[[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]
Moves array [4

feature_list is [0, 0, 4, 0, 0, 0, 93.9521021067122]
Vestimate is  93.9521021067122
Machine 1's move
[[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]
Moves array [4]
Machine 2's move
[[0. 0. 2.]
 [0. 1. 0.]
 [0. 0. 0.]]
feature_list is [0, 0, 5, 2, 0, 0, 93.53052294750239]
Vestimate is  93.53052294750239
Machine 1's move
[[0. 0. 2.]
 [0. 1. 0.]
 [1. 0. 0.]]
Moves array [4, 2, 6]
Machine 2's move
[[0. 0. 2.]
 [0. 1. 0.]
 [1. 2. 0.]]
feature_list is [0, 0, 3, 1, 0, 0, 86.91098614540968]
Vestimate is  86.91098614540968
Machine 1's move
[[0. 1. 2.]
 [0. 1. 0.]
 [1. 2. 0.]]
Moves array [4, 2, 6, 7, 1]
Machine 2's move
[[0. 1. 2.]
 [2. 1. 0.]
 [1. 2. 0.]]
feature_list is [0, 0, 1, 0, 0, 0, 80.29144934331697]
Vestimate is  80.29144934331697
Machine 1's move
[[0. 1. 2.]
 [2. 1. 1.]
 [1. 2. 0.]]
Moves array [4, 2, 6, 7, 1, 3, 5]
Machine 2's move
[[0. 1. 2.]
 [2. 1. 1.]
 [1. 2. 2.]]
feature_list is [0, 0, 0, 0, 0, 0, 75.73789842218522]
Vestimate is  75.73789842218522
Machine 1's move
[[1. 1. 2.]
 [2. 1. 1.]

Machine 2's move
[[0. 0. 0.]
 [0. 1. 2.]
 [0. 0. 0.]]
feature_list is [1, 0, 4, 1, 0, 0, 93.34056413770588]
Vestimate is  93.34056413770588
Machine 1's move
[[1. 0. 0.]
 [0. 1. 2.]
 [0. 0. 0.]]
Moves array [4, 5, 0]
Machine 2's move
[[1. 0. 0.]
 [0. 1. 2.]
 [0. 0. 2.]]
feature_list is [2, 0, 2, 1, 0, 0, 92.00759781350554]
Vestimate is  92.00759781350554
Machine 1's move
[[1. 0. 1.]
 [0. 1. 2.]
 [0. 0. 2.]]
Moves array [4, 5, 0, 8, 2]
Machine 2's move
[[1. 0. 1.]
 [0. 1. 2.]
 [0. 2. 2.]]
feature_list is [2, 0, 0, 0, 1, 0, 98.57141267642804]
Vestimate is  98.57141267642804
Machine 1's move
[[1. 0. 1.]
 [0. 1. 2.]
 [1. 2. 2.]]
Moves array [4, 5, 0, 8, 2, 7, 6]
Game Over
Machine1 won
Game counter 635
length of f1 4
weights after update 70.75695407132093 8.479361153174773 -22.577193249807245 5.091697467172372 -0.9337547197080882 13.56920048962625 0.5
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
feature_list is [0, 0, 4, 0, 0, 0, 91.12374394001043]
Vestimate is  91.12374394001043
Machine 1's move
[[

[[0. 1. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Moves array [1]
Machine 2's move
[[0. 1. 2.]
 [0. 0. 0.]
 [0. 0. 0.]]
feature_list is [0, 0, 3, 2, 0, 0, 75.14136281842686]
Vestimate is  75.14136281842686
Machine 1's move
[[1. 1. 2.]
 [0. 0. 0.]
 [0. 0. 0.]]
Moves array [1, 2, 0]
Machine 2's move
[[1. 1. 2.]
 [0. 0. 0.]
 [0. 0. 2.]]
feature_list is [0, 0, 3, 2, 0, 0, 75.14136281842686]
Vestimate is  75.14136281842686
Machine 1's move
[[1. 1. 2.]
 [0. 0. 1.]
 [0. 0. 2.]]
Moves array [1, 2, 0, 8, 5]
Machine 2's move
[[1. 1. 2.]
 [2. 0. 1.]
 [0. 0. 2.]]
feature_list is [1, 0, 0, 1, 0, 0, 57.11024734404309]
Vestimate is  57.11024734404309
Machine 1's move
[[1. 1. 2.]
 [2. 1. 1.]
 [0. 0. 2.]]
Moves array [1, 2, 0, 8, 5, 3, 4]
Machine 2's move
[[1. 1. 2.]
 [2. 1. 1.]
 [0. 2. 2.]]
feature_list is [0, 0, 0, 0, 0, 0, 57.78577333674688]
Vestimate is  57.78577333674688
Machine 1's move
[[1. 1. 2.]
 [2. 1. 1.]
 [1. 2. 2.]]
Moves array [1, 2, 0, 8, 5, 3, 4, 7, 6]
Game Tie
Game counter 654
length of f1 5
weight

[[0. 2. 0.]
 [0. 1. 0.]
 [1. 0. 0.]]
Moves array [4, 1, 6]
Machine 2's move
[[0. 2. 0.]
 [2. 1. 0.]
 [1. 0. 0.]]
feature_list is [0, 0, 3, 0, 1, 0, 95.65652821531728]
Vestimate is  95.65652821531728
Machine 1's move
[[0. 2. 1.]
 [2. 1. 0.]
 [1. 0. 0.]]
Moves array [4, 1, 6, 3, 2]
Game Over
Machine1 won
Game counter 672
length of f1 3
weights after update 72.84220995084242 0.5676867082141925 -29.856996352373425 2.3535582486229942 7.484954983503949 20.086302217381622 0.5
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
feature_list is [0, 0, 4, 0, 0, 0, 82.2564429453344]
Vestimate is  82.2564429453344
Machine 1's move
[[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]
Moves array [4]
Machine 2's move
[[0. 0. 0.]
 [0. 1. 0.]
 [2. 0. 0.]]
feature_list is [0, 0, 5, 2, 0, 0, 99.57991116096528]
Vestimate is  99.57991116096528
Machine 1's move
[[0. 0. 1.]
 [0. 1. 0.]
 [2. 0. 0.]]
Moves array [4, 6, 2]
Machine 2's move
[[0. 0. 1.]
 [0. 1. 0.]
 [2. 0. 2.]]
feature_list is [1, 0, 2, 1, 0, 0, 85.60196813980656]
Vestimate i

[[0. 1. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Moves array [1]
Machine 2's move
[[2. 1. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
feature_list is [1, 0, 2, 1, 0, 0, 68.71328239084116]
Vestimate is  68.71328239084116
Machine 1's move
[[2. 1. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]
Moves array [1, 0, 4]
Machine 2's move
[[2. 1. 0.]
 [0. 1. 0.]
 [0. 0. 2.]]
feature_list is [2, 0, 1, 1, 0, 0, 76.3332506314603]
Vestimate is  76.3332506314603
Machine 1's move
[[2. 1. 0.]
 [0. 1. 0.]
 [1. 0. 2.]]
Moves array [1, 0, 4, 8, 6]
Machine 2's move
[[2. 1. 0.]
 [2. 1. 0.]
 [1. 0. 2.]]
feature_list is [1, 0, 0, 0, 1, 0, 85.66236693599744]
Vestimate is  85.66236693599744
Machine 1's move
[[2. 1. 1.]
 [2. 1. 0.]
 [1. 0. 2.]]
Moves array [1, 0, 4, 8, 6, 3, 2]
Game Over
Machine1 won
Game counter 691
length of f1 4
weights after update 68.57866750059361 9.531796844225777 -26.624728871749927 1.686814221962154 -1.6778994407108487 13.918986489700297 0.5
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
feature_list is [0, 0, 4, 0, 0, 0, 75.32592438844223]

Machine 2's move
[[0. 0. 0.]
 [0. 1. 0.]
 [0. 2. 0.]]
feature_list is [1, 0, 4, 1, 0, 0, 93.92575493242936]
Vestimate is  93.92575493242936
Machine 1's move
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 2. 0.]]
Moves array [4, 7, 0]
Machine 2's move
[[1. 0. 0.]
 [2. 1. 0.]
 [0. 2. 0.]]
feature_list is [0, 0, 3, 0, 1, 0, 99.11422385182009]
Vestimate is  99.11422385182009
Machine 1's move
[[1. 0. 0.]
 [2. 1. 0.]
 [0. 2. 1.]]
Moves array [4, 7, 0, 3, 8]
Game Over
Machine1 won
Game counter 711
length of f1 3
weights after update 71.87348511473563 6.213674944171008 -26.624728871749927 4.853229194057534 -2.6573984022269963 13.328163096243502 0.5
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
feature_list is [0, 0, 4, 0, 0, 0, 91.28640189096576]
Vestimate is  91.28640189096576
Machine 1's move
[[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]
Moves array [4]
Machine 2's move
[[0. 0. 0.]
 [0. 1. 0.]
 [2. 0. 0.]]
feature_list is [0, 0, 5, 2, 0, 0, 90.8248342805693]
Vestimate is  90.8248342805693
Machine 1's move
[[0. 0. 1.]
 [0. 1. 0

weights after update 76.02368253888763 8.967584903850742 -26.624728871749927 3.4322511165857956 -3.9390886413314306 11.724376822845759 0.5
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
feature_list is [0, 0, 4, 0, 0, 0, 89.75268700523081]
Vestimate is  89.75268700523081
Machine 1's move
[[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]
Moves array [4]
Machine 2's move
[[0. 0. 0.]
 [0. 1. 0.]
 [0. 2. 0.]]
feature_list is [1, 0, 3, 0, 0, 0, 95.28802079249576]
Vestimate is  95.28802079249576
Machine 1's move
[[0. 0. 0.]
 [0. 1. 0.]
 [1. 2. 0.]]
Moves array [4, 7, 6]
Machine 2's move
[[0. 0. 0.]
 [2. 1. 0.]
 [1. 2. 0.]]
feature_list is [0, 0, 3, 0, 1, 0, 98.04481271149076]
Vestimate is  98.04481271149076
Machine 1's move
[[0. 0. 1.]
 [2. 1. 0.]
 [1. 2. 0.]]
Moves array [4, 7, 6, 3, 2]
Game Over
Machine1 won
Game counter 733
length of f1 3
weights after update 76.05314125412062 8.5236707034058 -26.624728871749927 4.074160641011212 -3.9390886413314306 11.64421635979718 0.5
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
fea

Moves array [4]
Machine 2's move
[[0. 0. 0.]
 [0. 1. 0.]
 [2. 0. 0.]]
feature_list is [1, 0, 3, 1, 0, 0, 93.32312598409167]
Vestimate is  93.32312598409167
Machine 1's move
[[1. 0. 0.]
 [0. 1. 0.]
 [2. 0. 0.]]
Moves array [4, 6, 0]
Machine 2's move
[[1. 0. 0.]
 [0. 1. 0.]
 [2. 2. 0.]]
feature_list is [0, 0, 3, 0, 1, 0, 98.50383934219289]
Vestimate is  98.50383934219289
Machine 1's move
[[1. 0. 0.]
 [0. 1. 0.]
 [2. 2. 1.]]
Moves array [4, 6, 0, 7, 8]
Game Over
Machine1 won
Game counter 753
length of f1 3
weights after update 80.63256629609579 7.237742580565003 -22.354786010879003 3.057311448603819 -1.8187774591247063 9.827044088063332 0.5
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
feature_list is [0, 0, 4, 0, 0, 0, 92.86181209051107]
Vestimate is  92.86181209051107
Machine 1's move
[[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]
Moves array [4]
Machine 2's move
[[0. 0. 0.]
 [2. 1. 0.]
 [0. 0. 0.]]
feature_list is [1, 0, 4, 1, 0, 0, 98.28077721195136]
Vestimate is  98.28077721195136
Machine 1's move
[[0.

weights after update 70.12245238634804 4.252001977117892 -22.354786010879003 6.17584615570887 -3.305642960497876 11.77816157632715 0.5
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
feature_list is [0, 0, 4, 0, 0, 0, 94.82583700918352]
Vestimate is  94.82583700918352
Machine 1's move
[[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]
Moves array [4]
Machine 2's move
[[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 2.]]
feature_list is [0, 0, 5, 2, 0, 0, 94.39039724389664]
Vestimate is  94.39039724389664
Machine 1's move
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 2.]]
Moves array [4, 8, 0]
Machine 2's move
[[1. 0. 0.]
 [2. 1. 0.]
 [0. 0. 2.]]
feature_list is [0, 0, 3, 1, 0, 0, 85.34434789297678]
Vestimate is  85.34434789297678
Machine 1's move
[[1. 0. 0.]
 [2. 1. 1.]
 [0. 0. 2.]]
Moves array [4, 8, 0, 3, 5]
Machine 2's move
[[1. 0. 0.]
 [2. 1. 1.]
 [2. 0. 2.]]
feature_list is [1, 0, 1, 0, 0, 0, 80.5503005191748]
Vestimate is  80.5503005191748
Machine 1's move
[[1. 0. 0.]
 [2. 1. 1.]
 [2. 1. 2.]]
Moves array [4, 8, 0, 3, 5, 6, 7]
Machine 

Vestimate is  110.30680095143157
Machine 1's move
[[0. 2. 1.]
 [0. 1. 0.]
 [1. 2. 0.]]
Moves array [4, 1, 6, 7, 2]
Game Over
Machine1 won
Game counter 794
length of f1 3
weights after update 78.42491824486052 5.9163779949980775 -22.354786010879003 -1.0218080694471245 -2.2437859759835446 9.21580718449253 0.5
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
feature_list is [0, 0, 2, 0, 0, 0, 76.38130210596627]
Vestimate is  76.38130210596627
Machine 1's move
[[0. 1. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Moves array [1]
Machine 2's move
[[0. 1. 0.]
 [0. 0. 2.]
 [0. 0. 0.]]
feature_list is [1, 0, 2, 1, 0, 0, 80.0538941249808]
Vestimate is  80.0538941249808
Machine 1's move
[[0. 1. 1.]
 [0. 0. 2.]
 [0. 0. 0.]]
Moves array [1, 5, 2]
Machine 2's move
[[2. 1. 1.]
 [0. 0. 2.]
 [0. 0. 0.]]
feature_list is [2, 0, 0, 1, 0, 0, 88.01388825887314]
Vestimate is  88.01388825887314
Machine 1's move
[[2. 1. 1.]
 [0. 1. 2.]
 [0. 0. 0.]]
Moves array [1, 5, 2, 0, 4]
Machine 2's move
[[2. 1. 1.]
 [2. 1. 2.]
 [0. 0. 0.]]
feature_

Moves array [4, 0, 2, 5, 6]
Game Over
Machine1 won
Game counter 814
length of f1 3
weights after update 76.33622057852311 3.1582164226014777 -22.354786010879003 5.466421635364722 -1.0116050755472288 9.938214299880816 0.5
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
feature_list is [0, 0, 4, 0, 0, 0, 98.201907119982]
Vestimate is  98.201907119982
Machine 1's move
[[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]
Moves array [4]
Machine 2's move
[[0. 0. 0.]
 [0. 1. 2.]
 [0. 0. 0.]]
feature_list is [1, 0, 4, 1, 0, 0, 100.34851846703626]
Vestimate is  100.34851846703626
Machine 1's move
[[1. 0. 0.]
 [0. 1. 2.]
 [0. 0. 0.]]
Moves array [4, 5, 0]
Machine 2's move
[[1. 2. 0.]
 [0. 1. 2.]
 [0. 0. 0.]]
feature_list is [0, 0, 3, 0, 1, 0, 102.67369978449808]
Vestimate is  102.67369978449808
Machine 1's move
[[1. 2. 0.]
 [0. 1. 2.]
 [0. 0. 1.]]
Moves array [4, 5, 0, 1, 8]
Game Over
Machine1 won
Game counter 815
length of f1 3
weights after update 76.04417399883758 3.025810625348435 -22.354786010879003 4.67253723376053

Vestimate is  86.8597391983866
Machine 1's move
[[2. 0. 0.]
 [2. 1. 0.]
 [1. 0. 1.]]
Moves array [4, 0, 8, 3, 6]
Machine 2's move
[[2. 0. 0.]
 [2. 1. 2.]
 [1. 0. 1.]]
feature_list is [1, 0, 1, 0, 1, 0, 92.23989791359672]
Vestimate is  92.23989791359672
Machine 1's move
[[2. 0. 1.]
 [2. 1. 2.]
 [1. 0. 1.]]
Moves array [4, 0, 8, 3, 6, 5, 2]
Game Over
Machine1 won
Game counter 834
length of f1 4
weights after update 68.73365881183388 7.990907982915074 -22.354786010879003 7.1575683129935275 -4.423905475290463 13.277695274540838 0.5
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
feature_list is [0, 0, 4, 0, 0, 0, 97.363932063808]
Vestimate is  97.363932063808
Machine 1's move
[[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]
Moves array [4]
Machine 2's move
[[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 2.]]
feature_list is [0, 0, 5, 2, 0, 0, 95.67368942622059]
Vestimate is  95.67368942622059
Machine 1's move
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 2.]]
Moves array [4, 8, 0]
Machine 2's move
[[1. 0. 0.]
 [0. 1. 0.]
 [2. 0. 2.]]
feature

Machine 1's move
[[0. 0. 2.]
 [0. 1. 0.]
 [1. 0. 0.]]
Moves array [4, 2, 6]
Machine 2's move
[[2. 0. 2.]
 [0. 1. 0.]
 [1. 0. 0.]]
feature_list is [1, 0, 2, 1, 0, 0, 86.64039514806107]
Vestimate is  86.64039514806107
Machine 1's move
[[2. 1. 2.]
 [0. 1. 0.]
 [1. 0. 0.]]
Moves array [4, 2, 6, 0, 1]
Machine 2's move
[[2. 1. 2.]
 [0. 1. 0.]
 [1. 0. 2.]]
feature_list is [2, 0, 0, 0, 0, 0, 86.63168325856753]
Vestimate is  86.63168325856753
Machine 1's move
[[2. 1. 2.]
 [0. 1. 1.]
 [1. 0. 2.]]
Moves array [4, 2, 6, 0, 1, 8, 5]
Machine 2's move
[[2. 1. 2.]
 [0. 1. 1.]
 [1. 2. 2.]]
feature_list is [0, 0, 0, 0, 1, 0, 89.7629654590675]
Vestimate is  89.7629654590675
Machine 1's move
[[2. 1. 2.]
 [1. 1. 1.]
 [1. 2. 2.]]
Moves array [4, 2, 6, 0, 1, 8, 5, 7, 3]
Game Over
Machine1 won
Game counter 854
length of f1 5
weights after update 72.5578004626668 8.476024490077751 -22.354786010879003 5.224327732151547 -4.047570377250585 19.449164335068975 0.5
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
feature_list i

[[1. 0. 0.]
 [0. 1. 2.]
 [2. 0. 1.]]
Moves array [4, 6, 0, 5, 8]
Game Over
Machine1 won
Game counter 875
length of f1 3
weights after update 77.52605223654528 7.450683849521004 -22.354786010879003 4.899216959581435 -2.1647587823200163 13.178055575850966 0.5
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
feature_list is [0, 0, 4, 0, 0, 0, 97.12292007487102]
Vestimate is  97.12292007487102
Machine 1's move
[[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]
Moves array [4]
Machine 2's move
[[0. 2. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]
feature_list is [1, 0, 4, 1, 0, 0, 102.408845142072]
Vestimate is  102.408845142072
Machine 1's move
[[0. 2. 0.]
 [0. 1. 0.]
 [1. 0. 0.]]
Moves array [4, 1, 6]
Machine 2's move
[[2. 2. 0.]
 [0. 1. 0.]
 [1. 0. 0.]]
feature_list is [0, 0, 3, 0, 1, 0, 105.40175869114056]
Vestimate is  105.40175869114056
Machine 1's move
[[2. 2. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]
Moves array [4, 1, 6, 0, 2]
Game Over
Machine1 won
Game counter 876
length of f1 3
weights after update 77.0070933873704 6.8513679430036944

feature_list is [1, 0, 0, 0, 1, 0, 97.83269440939492]
Vestimate is  97.83269440939492
Machine 1's move
[[1. 0. 1.]
 [0. 1. 2.]
 [2. 2. 1.]]
Moves array [4, 7, 0, 5, 2, 6, 8]
Game Over
Machine1 won
Game counter 896
length of f1 4
weights after update 70.16055666493305 9.04566448405071 -22.354786010879003 5.230359973764464 -4.438971738837068 16.16910252210079 0.5
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
feature_list is [0, 0, 4, 0, 0, 0, 91.08199655999091]
Vestimate is  91.08199655999091
Machine 1's move
[[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]
Moves array [4]
Machine 2's move
[[0. 0. 2.]
 [0. 1. 0.]
 [0. 0. 0.]]
feature_list is [1, 0, 3, 1, 0, 0, 90.45832933144008]
Vestimate is  90.45832933144008
Machine 1's move
[[1. 0. 2.]
 [0. 1. 0.]
 [0. 0. 0.]]
Moves array [4, 2, 0]
Machine 2's move
[[1. 0. 2.]
 [0. 1. 0.]
 [0. 2. 0.]]
feature_list is [0, 0, 2, 0, 1, 0, 96.79037913456277]
Vestimate is  96.79037913456277
Machine 1's move
[[1. 0. 2.]
 [0. 1. 0.]
 [0. 2. 1.]]
Moves array [4, 2, 0, 7, 8]
Game 

weights after update 70.0924639052344 10.596803158903251 -22.354786010879003 3.536959460957167 -4.335012186090932 18.477925765305663 0.5
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
feature_list is [0, 0, 4, 0, 0, 0, 84.24030174906306]
Vestimate is  84.24030174906306
Machine 1's move
[[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]
Moves array [4]
Machine 2's move
[[0. 0. 0.]
 [0. 1. 0.]
 [2. 0. 0.]]
feature_list is [1, 0, 3, 1, 0, 0, 86.96513326091822]
Vestimate is  86.96513326091822
Machine 1's move
[[1. 0. 0.]
 [0. 1. 0.]
 [2. 0. 0.]]
Moves array [4, 6, 0]
Machine 2's move
[[1. 2. 0.]
 [0. 1. 0.]
 [2. 0. 0.]]
feature_list is [0, 0, 2, 0, 1, 0, 95.6443085924544]
Vestimate is  95.6443085924544
Machine 1's move
[[1. 2. 0.]
 [0. 1. 0.]
 [2. 0. 1.]]
Moves array [4, 6, 0, 1, 8]
Game Over
Machine1 won
Game counter 918
length of f1 3
weights after update 70.70938819209124 11.1104925955157 -22.354786010879003 5.829463773654338 -3.821322749478484 18.308677464364546 0.5
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
featur

Vestimate is  83.0603720937659
Machine 1's move
[[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]
Moves array [4]
Machine 2's move
[[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 2.]]
feature_list is [1, 0, 3, 1, 0, 0, 85.62708825271669]
Vestimate is  85.62708825271669
Machine 1's move
[[0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 2.]]
Moves array [4, 8, 2]
Machine 2's move
[[0. 0. 1.]
 [0. 1. 2.]
 [0. 0. 2.]]
feature_list is [0, 0, 3, 0, 1, 0, 99.80572793076108]
Vestimate is  99.80572793076108
Machine 1's move
[[0. 0. 1.]
 [0. 1. 2.]
 [1. 0. 2.]]
Moves array [4, 8, 2, 5, 6]
Game Over
Machine1 won
Game counter 938
length of f1 3
weights after update 61.44382011807004 14.46760851745995 -22.354786010879003 5.473693206823988 -4.342766199764686 20.73666350057744 0.5
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
feature_list is [0, 0, 4, 0, 0, 0, 83.338592945366]
Vestimate is  83.338592945366
Machine 1's move
[[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]
Moves array [4]
Machine 2's move
[[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 2.]]
feature_list is [1, 0, 3, 1

Vestimate is  87.84738134993069
Machine 1's move
[[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]
Moves array [4]
Machine 2's move
[[0. 0. 0.]
 [2. 1. 0.]
 [0. 0. 0.]]
feature_list is [1, 0, 4, 1, 0, 0, 92.65779552889181]
Vestimate is  92.65779552889181
Machine 1's move
[[0. 0. 1.]
 [2. 1. 0.]
 [0. 0. 0.]]
Moves array [4, 3, 2]
Machine 2's move
[[0. 0. 1.]
 [2. 1. 0.]
 [2. 0. 0.]]
feature_list is [2, 0, 2, 1, 0, 0, 90.37526808964353]
Vestimate is  90.37526808964353
Machine 1's move
[[1. 0. 1.]
 [2. 1. 0.]
 [2. 0. 0.]]
Moves array [4, 3, 2, 6, 0]
Machine 2's move
[[1. 0. 1.]
 [2. 1. 2.]
 [2. 0. 0.]]
feature_list is [1, 0, 1, 0, 1, 0, 97.28645972706381]
Vestimate is  97.28645972706381
Machine 1's move
[[1. 0. 1.]
 [2. 1. 2.]
 [2. 0. 1.]]
Moves array [4, 3, 2, 6, 0, 5, 8]
Game Over
Machine1 won
Game counter 959
length of f1 4
weights after update 68.8159637158168 9.540805099159565 -22.354786010879003 5.639031760686896 -2.3804658358069086 16.59374517716994 0.5
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
feat

weights after update 61.04360692396791 10.515522038628891 -22.354786010879003 5.252004412230713 -3.696146507102326 16.437698740165597 0.5
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
feature_list is [0, 0, 4, 0, 0, 0, 82.05162457289076]
Vestimate is  82.05162457289076
Machine 1's move
[[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]
Moves array [4]
Machine 2's move
[[0. 0. 0.]
 [2. 1. 0.]
 [0. 0. 0.]]
feature_list is [1, 0, 4, 1, 0, 0, 88.87100010441733]
Vestimate is  88.87100010441733
Machine 1's move
[[0. 0. 1.]
 [2. 1. 0.]
 [0. 0. 0.]]
Moves array [4, 3, 2]
Machine 2's move
[[0. 2. 1.]
 [2. 1. 0.]
 [0. 0. 0.]]
feature_list is [3, 0, 1, 1, 0, 0, 94.14603094498297]
Vestimate is  94.14603094498297
Machine 1's move
[[0. 2. 1.]
 [2. 1. 0.]
 [0. 0. 1.]]
Moves array [4, 3, 2, 1, 8]
Machine 2's move
[[0. 2. 1.]
 [2. 1. 0.]
 [2. 0. 1.]]
feature_list is [1, 0, 0, 0, 1, 0, 87.9968277027624]
Vestimate is  87.9968277027624
Machine 1's move
[[1. 2. 1.]
 [2. 1. 0.]
 [2. 0. 1.]]
Moves array [4, 3, 2, 1, 8, 6, 0]
Game 

## Execute below two blocks for playing / testing with human player

##### This is for making the moves of the human player

In [9]:
def human_move(moves_entered):
    move_entered = 0
    while (move_entered == 0):
        human_position = int(input("enter your move 1 - 9 ")) - 1
        if human_position > 8 or human_position < 0:
            print("Enter your move between 1 - 9")
        elif human_position not in moves_entered:
            #game_board[position // 3, position % 3] = 1
            move_entered = 2
            #clear_output()
            #print(game_board)
        else:
            print("Enter into a blank cell")
    return(human_position)

#### Pitting the human with the smart agent

In [24]:

#positions = []
winning_moves = [[0,1,2],[0,3,6],[0,4,8],[1,4,7],[2,5,8],[2,4,6],[3,4,5],[6,7,8]]
#start_index = 0


real_game_moves = []
machine_moves = []
human_moves = []
real_game_board = np.zeros([3,3])
#print(real_game_board)
print_game_board(real_game_board)


for i in range(0,9):
    GO = 0
    
    gb_copy = np.copy(real_game_board)
    
    machine_position, vestimate, feature_list = machine1_move(real_game_board, w0, w1, w2, w3, w4, w5, w6)
       
    #machine_position = machine_move(gb_copy.ravel())
    #print(machine_position)
    real_game_board[machine_position // 3, machine_position % 3] = 1
    clear_output()
    #print(real_game_board)
    print_game_board(real_game_board)
    real_game_moves.append(machine_position)
    machine_moves.append(machine_position)
    
    if len(machine_moves) > 2:
        for j in range(len(winning_moves)):
            
            machine_counter = [a for a in machine_moves if a in winning_moves[j]]
            if len(machine_counter)==3:
                print("Game Over")
                print("Machine won")
                GO = 1
                break
    
    if GO == 1:
        break
            
    elif len(machine_moves)+len(human_moves) == 9:
        print("Game Tie")
        break
      
    
    human_game_position = human_move(real_game_moves)
    real_game_board[human_game_position // 3, human_game_position % 3] = 2
    clear_output()
    #print(real_game_board)
    print_game_board(real_game_board)
    real_game_moves.append(human_game_position)
    human_moves.append(human_game_position)
    
    if len(human_moves) > 2:
        for h in range(len(winning_moves)):
            #machine_counter = 0
            human_counter = [b for b in human_moves if b in winning_moves[h]]
            if len(human_counter)==3:
                print("Game Over")
                print("Human won")
                GO = 1
                break
    
    if GO == 1:
        break   
    
    

     |     |     
  X  |     |  X  
_____|_____|_____
     |     |     
  O  |  X  |     
_____|_____|_____
     |     |     
  X  |  O  |  O  
     |     |     
Game Over
Machine won
