In [1]:
import numpy as np
import os
from random import randint
from IPython.display import display, clear_output


moves = []
human_moves = []
machine_moves = []
game_board = np.zeros([3,3])
print(game_board)
winning_moves = [[0,1,2],[0,3,6],[0,4,8],[1,4,7],[2,5,8],[2,4,6],[3,4,5],[6,7,8]]



def human_move():
    move_entered = 0
    while (move_entered == 0):
        position = int(input("enter your move 1 - 9 ")) - 1
        if position > 8 or position < 0:
            print("Enter your move between 1 - 9")
        elif position not in moves:
            game_board[position // 3, position % 3] = 1
            move_entered = 1
            #clear_output()
            print(game_board)
        else:
            print("Enter into a blank cell")
    return(position)
    
def machine_move():
    while(True):
        machine_position = randint(0,8)
        if machine_position not in moves:
            game_board[machine_position // 3, machine_position % 3] = 2
            moves.append(machine_position)
            
            #clear_output()
            print("Machine's move")
            print(game_board)
            break
    return(machine_position)



for i in range(0,9):
    GO = 0
    position = human_move()
    moves.append(position)
    human_moves.append(position)
    
    if len(human_moves) > 2:
        for j in range(len(winning_moves)):
            #human_counter = 0
            human_counter = [a for a in human_moves if a in winning_moves[j]]
            if len(human_counter)==3:
                print("Game Over")
                print("Human won")
                GO = 1
                break
    
    if GO == 1:
        break
        
    machine_position = machine_move()
    moves.append(machine_position)
    machine_moves.append(machine_position)
    
    if len(machine_moves) > 2:
        for h in range(len(winning_moves)):
            #machine_counter = 0
            machine_counter = [b for b in machine_moves if b in winning_moves[h]]
            if len(machine_counter)==3:
                print("Game Over")
                print("Machine won")
                GO = 1
                break
    
    if GO == 1:
        break   

[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]
enter your move 1 - 9 1
[[ 1.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]
Machine's move
[[ 1.  0.  0.]
 [ 0.  0.  0.]
 [ 2.  0.  0.]]
enter your move 1 - 9 4
[[ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 2.  0.  0.]]
Machine's move
[[ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 2.  2.  0.]]
enter your move 1 - 9 2
[[ 1.  1.  0.]
 [ 1.  0.  0.]
 [ 2.  2.  0.]]
Machine's move
[[ 1.  1.  0.]
 [ 1.  0.  0.]
 [ 2.  2.  2.]]
Game Over
Machine won


In [8]:
game_state = 1 * 1 * w1 + 2 * w2 + 6 * w3 + 0 * w4 + 5 * w5 + 12 * w6 + 14 * w7 + 0 * w8 + 9 * w9 + w0 = -100
w1 + 2 * w2 + 4 * w4 + 14 * w7 + 16 * w8 + 18 * w9 + w0 = 100

In [ ]:
Number of ones in Row 1 = x1
Number of twos in Row 1 = x2
Number of ones in Row 2 = x3
Number of twos in row 2 = x4
Number of ones in row 3 = x5
Number of twos in row 3 = x6

In [ ]:
Game state 1: w0 + w1 * 2 + w2 * 0 + w3 * 1 + w4 * 0 + 0 * w5 + 3 * w6 = 100
Game state 2: 