In [243]:
import numpy as np
import pandas as pd
import os
from random import randint
from IPython.display import display, clear_output


# moves = []
# machine1_moves = []
# machine2_moves = []
# game_board = np.zeros([3,3])
# print(game_board)
# winning_moves = [[0,1,2],[0,3,6],[0,4,8],[1,4,7],[2,5,8],[2,4,6],[3,4,5],[6,7,8]]


'''
def human_move():
    move_entered = 0
    while (move_entered == 0):
        position = int(input("enter your move 1 - 9 ")) - 1
        if position > 8 or position < 0:
            print("Enter your move between 1 - 9")
        elif position not in moves:
            game_board[position // 3, position % 3] = 1
            move_entered = 1
            #clear_output()
            print(game_board)
        else:
            print("Enter into a blank cell")
    return(position)
'''

  


'\ndef human_move():\n    move_entered = 0\n    while (move_entered == 0):\n        position = int(input("enter your move 1 - 9 ")) - 1\n        if position > 8 or position < 0:\n            print("Enter your move between 1 - 9")\n        elif position not in moves:\n            game_board[position // 3, position % 3] = 1\n            move_entered = 1\n            #clear_output()\n            print(game_board)\n        else:\n            print("Enter into a blank cell")\n    return(position)\n'

In [244]:
def machine1_move():
    while(True):
        machine1_position = randint(0,8)
        if machine1_position not in moves:
            #game_board[machine1_position // 3, machine1_position % 3] = 1
            moves.append(machine1_position)
            
            #clear_output()
            print("Machine 1's move")
            break
    return(machine1_position)



In [245]:

def machine2_move():
    while(True):
        machine2_position = randint(0,8)
        if machine2_position not in moves:
            #game_board[machine2_position // 3, machine2_position % 3] = 2
            moves.append(machine2_position)
            
            #clear_output()
            print("Machine 2's move")
            break
    return(machine2_position)



In [246]:

positions = []
winning_moves = [[0,1,2],[0,3,6],[0,4,8],[1,4,7],[2,5,8],[2,4,6],[3,4,5],[6,7,8]]
start_index = 0

for m in range(0,20):
    #np.zeros([3,3])
    
    
    moves = []
    machine1_moves = []
    machine2_moves = []
    game_board = np.zeros([3,3])
    print(game_board)
    
    for i in range(0,9):
        GO = 0
        machine1_position = machine1_move()
        game_board[machine1_position // 3, machine1_position % 3] = 1
        print(game_board)
        mc1 = np.copy(game_board)
        positions.append(mc1.ravel().tolist())
        moves.append(machine1_position)
        machine1_moves.append(machine1_position)
        machine1_counter = 0
        
        ## If more than one moves are made, then keep checking in the winning moves list
        
        if len(machine1_moves) > 2:
            for j in range(len(winning_moves)):
                #human_counter = 0
                machine1_counter = [a for a in machine1_moves if a in winning_moves[j]]
                if len(machine1_counter)==3:
                    print("Game Over")
                    print("Machine1 won")
                    GO = 1
                    break

        if GO == 1:
            for p in range(start_index,len(positions)):
                
         
                positions[p].extend([1])
            #print(positions)
            start_index = len(positions)
            break
        elif len(machine1_moves)+len(machine2_moves) ==9:
            print("Game Tie")
            for p in range(start_index,len(positions)):
                
         
                positions[p].extend([0])
            #print(positions)
            start_index = len(positions)
            
            break

        machine2_position = machine2_move()
        
        game_board[machine2_position // 3, machine2_position % 3] = 2
        print(game_board)
        mc2 = np.copy(game_board)
        positions.append(mc2.ravel().tolist())
        moves.append(machine2_position)
        machine2_moves.append(machine2_position)
        machine2_counter = 0
        if len(machine2_moves) > 2:
            for h in range(len(winning_moves)):
                #machine_counter = 0
                machine2_counter = [b for b in machine2_moves if b in winning_moves[h]]
                if len(machine2_counter)==3:
                    print("Game Over")
                    print("Machine2 won")
                    GO = 1
                    break

        if GO == 1:
            for p in range(start_index,len(positions)):
             
                positions[p].extend([2])
            #print(positions)
            start_index = len(positions)
            break   

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Machine 1's move
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 1.]]
Machine 2's move
[[0. 0. 0.]
 [0. 0. 0.]
 [2. 0. 1.]]
Machine 1's move
[[0. 0. 0.]
 [0. 1. 0.]
 [2. 0. 1.]]
Machine 2's move
[[2. 0. 0.]
 [0. 1. 0.]
 [2. 0. 1.]]
Machine 1's move
[[2. 0. 1.]
 [0. 1. 0.]
 [2. 0. 1.]]
Machine 2's move
[[2. 0. 1.]
 [2. 1. 0.]
 [2. 0. 1.]]
Game Over
Machine2 won
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Machine 1's move
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 1.]]
Machine 2's move
[[0. 0. 2.]
 [0. 0. 0.]
 [0. 0. 1.]]
Machine 1's move
[[0. 0. 2.]
 [0. 0. 0.]
 [0. 1. 1.]]
Machine 2's move
[[0. 0. 2.]
 [0. 0. 0.]
 [2. 1. 1.]]
Machine 1's move
[[0. 0. 2.]
 [0. 1. 0.]
 [2. 1. 1.]]
Machine 2's move
[[0. 0. 2.]
 [0. 1. 2.]
 [2. 1. 1.]]
Machine 1's move
[[0. 0. 2.]
 [1. 1. 2.]
 [2. 1. 1.]]
Machine 2's move
[[2. 0. 2.]
 [1. 1. 2.]
 [2. 1. 1.]]
Machine 1's move
[[2. 1. 2.]
 [1. 1. 2.]
 [2. 1. 1.]]
Game Over
Machine1 won
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Machine 1's move
[[0. 0. 0.]
 [0.

In [247]:
moves

[5, 5, 2, 2, 0, 0, 3, 3, 4, 4, 8, 8, 1, 1, 7, 7, 6, 6]

In [248]:
positions

[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 2],
 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 2.0, 0.0, 1.0, 2],
 [0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 2.0, 0.0, 1.0, 2],
 [2.0, 0.0, 0.0, 0.0, 1.0, 0.0, 2.0, 0.0, 1.0, 2],
 [2.0, 0.0, 1.0, 0.0, 1.0, 0.0, 2.0, 0.0, 1.0, 2],
 [2.0, 0.0, 1.0, 2.0, 1.0, 0.0, 2.0, 0.0, 1.0, 2],
 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1],
 [0.0, 0.0, 2.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1],
 [0.0, 0.0, 2.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1],
 [0.0, 0.0, 2.0, 0.0, 0.0, 0.0, 2.0, 1.0, 1.0, 1],
 [0.0, 0.0, 2.0, 0.0, 1.0, 0.0, 2.0, 1.0, 1.0, 1],
 [0.0, 0.0, 2.0, 0.0, 1.0, 2.0, 2.0, 1.0, 1.0, 1],
 [0.0, 0.0, 2.0, 1.0, 1.0, 2.0, 2.0, 1.0, 1.0, 1],
 [2.0, 0.0, 2.0, 1.0, 1.0, 2.0, 2.0, 1.0, 1.0, 1],
 [2.0, 1.0, 2.0, 1.0, 1.0, 2.0, 2.0, 1.0, 1.0, 1],
 [0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1],
 [0.0, 0.0, 0.0, 0.0, 2.0, 1.0, 0.0, 0.0, 0.0, 1],
 [0.0, 0.0, 0.0, 0.0, 2.0, 1.0, 0.0, 0.0, 1.0, 1],
 [0.0, 0.0, 0.0, 0.0, 2.0, 1.0, 2.0, 0.0, 1.0, 1],
 [0.0, 1.0, 0.0, 0.0, 2.0, 1.0,

In [249]:
game_data = pd.DataFrame(positions)

In [250]:
cols = ('pos1','pos2','pos3','pos4','pos5','pos6','pos7','pos8','pos9','Outcome')
game_data.columns=cols

In [257]:
#game_data

In [252]:
from sklearn import datasets
from sklearn import metrics
from sklearn.naive_bayes import GaussianNB

In [232]:
game_data[game_data.columns.difference(["Outcome"])]

pos1  pos2  pos3  pos4  pos5  pos6  pos7  pos8  pos9
0    0.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
1    0.0   1.0   0.0   0.0   0.0   0.0   0.0   2.0   0.0
2    0.0   1.0   0.0   1.0   0.0   0.0   0.0   2.0   0.0
3    0.0   1.0   0.0   1.0   0.0   2.0   0.0   2.0   0.0
4    0.0   1.0   0.0   1.0   0.0   2.0   0.0   2.0   1.0
5    0.0   1.0   0.0   1.0   2.0   2.0   0.0   2.0   1.0
6    0.0   1.0   1.0   1.0   2.0   2.0   0.0   2.0   1.0
7    0.0   1.0   1.0   1.0   2.0   2.0   2.0   2.0   1.0
8    1.0   1.0   1.0   1.0   2.0   2.0   2.0   2.0   1.0
9    1.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
10   1.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   2.0
11   1.0   0.0   0.0   0.0   0.0   0.0   1.0   0.0   2.0
12   1.0   0.0   2.0   0.0   0.0   0.0   1.0   0.0   2.0
13   1.0   0.0   2.0   0.0   0.0   0.0   1.0   1.0   2.0
14   1.0   0.0   2.0   0.0   2.0   0.0   1.0   1.0   2.0
15   1.0   1.0   2.0   0.0   2.0   0.0   1.0   1.0   2.0
16   1.0   1.0   2.0   2.0   2.0   0.0   1.0   1.0   2.0
17   1.0   1.0   2.0   2.0   2.0   1.0   1.0   1.0   2.0

In [253]:
model = GaussianNB()
model.fit(game_data[game_data.columns.difference(["Outcome"])], game_data['Outcome'])

GaussianNB(priors=None)

In [254]:
expected = game_data["Outcome"]
predicted = model.predict(test_set)

In [255]:
predicted

array([2, 1, 2, 0, 1, 2, 1])

In [236]:
test_list = [[0,1,1,0,0,0,0,0,0],[0,1,0,1,0,0,0,0,0],[0,1,0,0,1,0,0,0,0],[0,1,0,0,0,1,0,0,0],[0,1,0,0,0,0,1,0,0],[0,1,0,0,0,0,0,1,0],[0,1,1,0,0,0,0,0,1]]

In [237]:
test_set = pd.DataFrame(test_list)

In [239]:
cols = ('pos1','pos2','pos3','pos4','pos5','pos6','pos7','pos8','pos9')
test_set.columns=cols

In [256]:
test_set

pos1  pos2  pos3  pos4  pos5  pos6  pos7  pos8  pos9
0     0     1     1     0     0     0     0     0     0
1     0     1     0     1     0     0     0     0     0
2     0     1     0     0     1     0     0     0     0
3     0     1     0     0     0     1     0     0     0
4     0     1     0     0     0     0     1     0     0
5     0     1     0     0     0     0     0     1     0
6     0     1     1     0     0     0     0     0     1

In [313]:

#positions = []
winning_moves = [[0,1,2],[0,3,6],[0,4,8],[1,4,7],[2,5,8],[2,4,6],[3,4,5],[6,7,8]]
#start_index = 0

    

game_moves = []
machine_moves = []
human_moves = []
game_board = np.zeros([3,3])
print(game_board)


for i in range(0,9):
    GO = 0
    
    human_game_position = human_move()
    game_board[human_game_position // 3, human_game_position % 3] = 1
    game_moves.append(human_game_position)
    human_moves.append(human_game_position)
    
    if len(human_moves) > 2:
        for h in range(len(winning_moves)):
            #machine_counter = 0
            human_counter = [b for b in human_moves if b in winning_moves[h]]
            if len(human_counter)==3:
                print("Game Over")
                print("Human won")
                GO = 1
                break
    
    if GO == 1:
        break   
    
    gb_copy = np.copy(game_board)
    
    machine_position = machine_move(gb_copy.ravel())
    game_board[machine1_position // 3, machine1_position % 3] = 2
    game_moves.append(machine_position)
    machine_moves.append(machine_position)
    
    if len(machine_moves) > 2:
        for j in range(len(winning_moves)):
            
            machine_counter = [a for a in machine_moves if a in winning_moves[j]]
            if len(machine_counter)==3:
                print("Game Over")
                print("Machine won")
                GO = 1
                break
    
    if GO == 1:
        break

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
enter your move 1 - 9 1
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


ValueError: Expected 2D array, got 1D array instead:
array=[1. 2. 0. 0. 0. 0. 0. 0. 0.].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [310]:
def human_move():
    move_entered = 0
    while (move_entered == 0):
        human_position = int(input("enter your move 1 - 9 ")) - 1
        if human_position > 8 or human_position < 0:
            print("Enter your move between 1 - 9")
        elif human_position not in game_moves:
            #game_board[position // 3, position % 3] = 1
            move_entered = 2
            #clear_output()
            print(game_board)
        else:
            print("Enter into a blank cell")
    return(human_position)

In [312]:
def machine_move(board_state):
    model_output = []
    #while(True):
        #machine1_position = randint(0,8)
    choices = np.where(board_state==0)[0]

    for x in np.nditer(choices):
        board_state_copy = np.copy(board_state)
        board_state_copy[x]=2
        model_output.append(model.predict(board_state_copy))

    machine_position = model_output.argmax()
    #moves.append(machine_position)
    print("Machine's move")
    return(machine_position)
            
#         if machine1_position not in moves:
            
#             #game_board[machine1_position // 3, machine1_position % 3] = 1
#             moves.append(machine1_position)
            
#             #clear_output()
#             print("Machine 1's move")
            #break
    




In [294]:
b = np.array([1,23,0,9,2,5,0,10,1,2,0])

In [295]:
choice = np.where(b==0)[0]

In [288]:
choice[0]

2

In [290]:
[b[i]=2 for i in choice]

SyntaxError: invalid syntax (<ipython-input-290-8281e8ffca34>, line 1)

In [296]:

for x in np.nditer(choice):
    a = np.copy(b)
    a[x]=2
    model_output.append(predict(a))
    print(a)

[ 1 23  2  9  2  5  0 10  1  2  0]
[ 1 23  0  9  2  5  2 10  1  2  0]
[ 1 23  0  9  2  5  0 10  1  2  2]


In [297]:
a.argmax()

1

In [309]:
moves

[5, 5, 2, 2, 0, 0, 3, 3, 4, 4, 8, 8, 1, 1, 7, 7, 6, 6]